/*
    [DLU]
        2024-10-23
    [DATABASE FILE]
        /private/var/wireless/Library/Databases/DataUsage.sqlite
*/

SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    datetime(ZLIVEUSAGE.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZLIVEUSAGE.ZTIMESTAMP(UTC)',
    datetime(ZPROCESS.ZFIRSTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZPROCESS.ZFIRSTTIMESTAMP(UTC)',
    datetime(ZPROCESS.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZPROCESS.ZTIMESTAMP(UTC)',
    ZPROCESS.ZPROCNAME AS 'ZPROCESS.ZPROCNAME',
    ZPROCESS.ZBUNDLENAME AS 'ZPROCESS.ZBUNDLENAME',
    Z_PRIMARYKEY.Z_NAME as 'Z_PRIMARYKEY.Z_NAME',
    ZLIVEUSAGE.ZWIFIIN AS 'ZLIVEUSAGE.ZWIFIIN',
    ZLIVEUSAGE.ZWIFIOUT AS 'ZLIVEUSAGE.ZWIFIOUT',
    ZLIVEUSAGE.ZWWANIN AS 'ZLIVEUSAGE.ZWWANIN',
    ZLIVEUSAGE.ZWWANOUT AS 'ZLIVEUSAGE.ZWWANOUT',

    /* Source for each line of data */
    '/private/var/wireless/Library/Databases/DataUsage.sqlite; Table: ZLIVEUSAGE(Z_PK:' || ZLIVEUSAGE.Z_PK || '), ' || 'Table: ZPROCESS(Z_PK:' || ZPROCESS.Z_PK || ')' AS 'DATA_SOURCE'


FROM ZLIVEUSAGE
    LEFT JOIN ZPROCESS ON ZLIVEUSAGE.ZHASPROCESS = ZPROCESS.Z_PK
    LEFT JOIN Z_PRIMARYKEY ON ZPROCESS.Z_ENT = Z_PRIMARYKEY.Z_ENT


WHERE
    ZPROCESS.ZPROCNAME LIKE '%whisper%'


ORDER BY
    ZLIVEUSAGE.ZTIMESTAMP ASC
