/*
    [DLU]
        23-Jul-2025
    [DATABASE FILE]
        /private/var/wireless/Library/Databases/DataUsage.sqlite
*/

SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',

    CASE
        WHEN ZLIVEUSAGE.ZTIMESTAMP IS NULL THEN '[N/A]'
        ELSE datetime(ZLIVEUSAGE.ZTIMESTAMP + 978307200, 'UNIXEPOCH')
    END AS 'ZLIVEUSAGE.ZTIMESTAMP(UTC)',

    datetime(ZPROCESS.ZFIRSTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZPROCESS.ZFIRSTTIMESTAMP(UTC)',
    datetime(ZPROCESS.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZPROCESS.ZTIMESTAMP(UTC)',

    ZPROCESS.ZPROCNAME AS 'ZPROCESS.ZPROCNAME',
    ZPROCESS.ZBUNDLENAME AS 'ZPROCESS.ZBUNDLENAME',
    printf("%,d", ZLIVEUSAGE.ZWIFIIN) AS 'ZLIVEUSAGE.ZWIFIIN(BYTES)',
    printf("%,d", ZLIVEUSAGE.ZWIFIOUT) AS 'ZLIVEUSAGE.ZWIFIOUT(BYTES)',
    printf("%,d", ZLIVEUSAGE.ZWWANIN) AS 'ZLIVEUSAGE.ZWWANIN(BYTES)',
    printf("%,d", ZLIVEUSAGE.ZWWANOUT) AS 'ZLIVEUSAGE.ZWWANOUT(BYTES)',

    /* Source for each line of data */
    'Table: ZLIVEUSAGE(Z_PK:' || ZLIVEUSAGE.Z_PK || '), ' || 'Table: ZPROCESS(Z_PK:' || ZPROCESS.Z_PK || ')' AS 'DATA_SOURCE'


FROM ZLIVEUSAGE
    LEFT JOIN ZPROCESS ON ZLIVEUSAGE.ZHASPROCESS = ZPROCESS.Z_PK
    -- LEFT JOIN Z_PRIMARYKEY ON ZPROCESS.Z_ENT = Z_PRIMARYKEY.Z_ENT


WHERE
    ZPROCESS.ZPROCNAME LIKE '%compress%' OR
    ZPROCESS.ZBUNDLENAME LIKE '%compress%'


ORDER BY
    ZLIVEUSAGE.ZTIMESTAMP ASC
