/*
File located at: \private\var\networkd\db\netusage.sqlite
*/

SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    ZPROCESS.Z_PK AS 'ZPROCESS.Z_PK',

    datetime(ZPROCESS.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZPROCESS.ZTIMESTAMP(UTC)',
    datetime(ZPROCESS.ZFIRSTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZPROCESS.ZFIRSTTIMESTAMP(UTC)',
    datetime(ZLIVEUSAGE.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZLIVEUSAGE.ZTIMESTAMP(UTC)',

    ZPROCESS.ZBUNDLENAME AS 'ZPROCESS.ZBUNDLENAME',
    ZPROCESS.ZPROCNAME AS 'ZPROCESS.ZPROCNAME',
    printf("%,d", ZLIVEUSAGE.ZWIFIIN) AS 'ZLIVEUSAGE.ZWIFIIN(BYTES)',
    printf("%,d", ZLIVEUSAGE.ZWIFIOUT) AS 'ZLIVEUSAGE.ZWIFIOUT(BYTES)',
    printf("%,d", ZLIVEUSAGE.ZWWANIN) AS 'ZLIVEUSAGE.ZWWANIN(BYTES)',
    printf("%,d", ZLIVEUSAGE.ZWWANOUT) AS 'ZLIVEUSAGE.ZWWANOUT(BYTES)',
    ZLIVEUSAGE.ZWIREDIN AS 'ZLIVEUSAGE.ZWIREDIN',
    ZLIVEUSAGE.ZWIREDOUT AS 'ZLIVEUSAGE.ZWIREDOUT',
    ZLIVEUSAGE.ZXIN AS 'ZLIVEUSAGE.ZXIN',
    ZLIVEUSAGE.ZXOUT AS 'ZLIVEUSAGE.ZXOUT',

    /* Source for each line of data */
    'Table: ZLIVEUSAGE(Z_PK: ' || ZLIVEUSAGE.Z_PK || ')' AS 'DATA_SOURCE'


FROM ZLIVEUSAGE
    LEFT JOIN ZPROCESS ON ZPROCESS.Z_PK = ZLIVEUSAGE.ZHASPROCESS


WHERE
    ZPROCESS.ZBUNDLENAME LIKE '%compress%'


ORDER BY
    ZLIVEUSAGE.Z_PK ASC
