SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    ZLIVEROUTEPERF.Z_PK AS 'ZLIVEROUTEPERF.Z_PK',
    ZNETWORKATTACHMENT.Z_PK AS 'ZNETWORKATTACHMENT.Z_PK',

    datetime(ZLIVEROUTEPERF.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZLIVEROUTEPERF.ZTIMESTAMP(UTC)',
    datetime(ZNETWORKATTACHMENT.ZFIRSTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZNETWORKATTACHMENT.ZFIRSTTIMESTAMP(UTC)',
    datetime(ZNETWORKATTACHMENT.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZNETWORKATTACHMENT.ZTIMESTAMP(UTC)',

    CASE ZLIVEROUTEPERF.ZKIND
        WHEN 1 THEN '1  [WI-FI]'
        WHEN 2 THEN '2  [CELLULAR]'
        ELSE ZLIVEROUTEPERF.ZKIND
    END 'ZLIVEROUTEPERF.ZKIND',

    printf("%,d", ZLIVEROUTEPERF.ZBYTESIN) AS 'ZLIVEROUTEPERF.ZBYTESIN',
    printf("%,d", ZLIVEROUTEPERF.ZBYTESOUT) AS 'ZLIVEROUTEPERF.ZBYTESOUT',
    ZLIVEROUTEPERF.ZPACKETSIN AS 'ZLIVEROUTEPERF.ZPACKETSIN',
    ZLIVEROUTEPERF.ZPACKETSOUT AS 'ZLIVEROUTEPERF.ZPACKETSOUT',
    ZLIVEROUTEPERF.ZCONNATTEMPTS AS 'ZLIVEROUTEPERF.ZCONNATTEMPTS',
    ZLIVEROUTEPERF.ZCONNSUCCESSES AS ' ZLIVEROUTEPERF.ZCONNSUCCESSES',
    ZNETWORKATTACHMENT.ZIDENTIFIER AS 'ZNETWORKATTACHMENT.ZIDENTIFIER',
    ZNETWORKATTACHMENT.ZISKNOWNGOOD AS 'ZNETWORKATTACHMENT.ZISKNOWNGOOD',

    hex(ZNETWORKATTACHMENT.ZNETSIGNATURE) AS 'ZNETWORKATTACHMENT.ZNETSIGNATURE(HEX)',

    ZNETWORKATTACHMENT.ZOVERALLSTAYMEAN AS 'ZNETWORKATTACHMENT.ZOVERALLSTAYMEAN',
    ZNETWORKATTACHMENT.ZOVERALLSTAYVAR AS 'ZNETWORKATTACHMENT.ZOVERALLSTAYVAR',
    ZLIVEROUTEPERF.ZOVERALLSTAY AS ' ZLIVEROUTEPERF.ZOVERALLSTAY',
    ZLIVEROUTEPERF.ZOVERALLSTAYM2 AS 'ZLIVEROUTEPERF.ZOVERALLSTAYM2',

    /* Source for each line of data */
    'Table: ZZLIVEROUTEPERF(Z_PK:' || ZLIVEROUTEPERF.Z_PK || ')' AS 'DATA_SOURCE'


FROM ZLIVEROUTEPERF
    LEFT JOIN ZNETWORKATTACHMENT ON ZLIVEROUTEPERF.ZHASNETWORKATTACHMENT = ZNETWORKATTACHMENT.Z_PK


ORDER BY
    ZLIVEROUTEPERF.ZTIMESTAMP ASC
