SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    ZPROCESS.Z_PK AS 'ZPROCESS.Z_PK',

    datetime(ZPROCESS.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZPROCESS.ZTIMESTAMP(UTC)',
    datetime(ZPROCESS.ZFIRSTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZPROCESS.ZFIRSTTIMESTAMP(UTC)',

    ZPROCESS.ZPROCNAME AS 'ZPROCESS.ZPROCNAME',
    ZPROCESS.ZBUNDLENAME AS 'ZPROCESS.ZBUNDLENAME',

    /* Source for each line of data */
    'Table: ZPROCESS(Z_PK: ' || ZPROCESS.Z_PK || ')' AS 'DATA_SOURCE'


FROM ZPROCESS


-- WHERE
--     ZPROCESS.ZBUNDLENAME LIKE '%whisper%'


ORDER BY
    ZPROCESS.ZTIMESTAMP ASC
