/*
[DLU]
    05-Sep-2025
[Database Metadata]
    DATABASE=RMAdminStore-Local.sqlite, RMAdminStore-Cloud.sqlite
*/

SELECT

    DISTINCT
        ROW_NUMBER() OVER() AS 'RECORD_NUMBER',

        datetime(ZUSAGEBLOCK.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'ZUSAGEBLOCK.ZSTARTDATE(UTC)',

        ZUSAGEBLOCK.ZSCREENTIMEINSECONDS AS 'ZUSAGEBLOCK.ZSCREENTIMEINSECONDS',
        (ZUSAGEBLOCK.ZSCREENTIMEINSECONDS / 60.00) AS 'SCREENTIME(Minutes)',
        ZCOREUSER.ZGIVENNAME AS 'ZCOREUSER.ZGIVENNAME',
        ZCOREUSER.ZFAMILYNAME AS 'ZCOREUSER.ZFAMILYNAME',
        ZCOREDEVICE.ZNAME AS 'ZCOREDEVICE.ZNAME',

        CASE ZCOREDEVICE.ZPLATFORM
            WHEN 0 THEN '0 [Unknown]'
            WHEN 1 THEN '1 [macOS]'
            WHEN 2 THEN '2 [iOS]'
            WHEN 4 THEN '4 [Apple Watch]'
            ELSE ZCOREDEVICE.ZPLATFORM
        END AS 'ZCOREDEVICE.ZPLATFORM',

        ZCOREDEVICE.ZIDENTIFIER AS 'ZCOREDEVICE.ZIDENTIFIER',
        ZCOREDEVICE.ZLOCALUSERDEVICESTATE AS 'ZCOREDEVICE.ZLOCALUSERDEVICESTATE',

        datetime(ZUSAGEBLOCK.ZLONGESTSESSIONSTARTDATE + 978307200, 'UNIXEPOCH') AS 'ZUSAGEBLOCK.ZLONGESTSESSIONSTARTDATE(UTC)',
        datetime(ZUSAGEBLOCK.ZLONGESTSESSIONENDDATE + 978307200, 'UNIXEPOCH') AS 'ZUSAGEBLOCK.ZLONGESTSESSIONENDDATE(UTC)',
        datetime(ZUSAGEBLOCK.ZLASTEVENTDATE + 978307200, 'UNIXEPOCH') AS 'ZUSAGEBLOCK.ZLASTEVENTDATE(UTC)',

        (ZUSAGEBLOCK.ZLONGESTSESSIONENDDATE - ZUSAGEBLOCK.ZLONGESTSESSIONSTARTDATE) AS 'LONGESTSESSIONTIME(Seconds)',
        ((ZUSAGEBLOCK.ZLONGESTSESSIONENDDATE - ZUSAGEBLOCK.ZLONGESTSESSIONSTARTDATE) / 60.00) AS 'LONGESTSESSIONTIME(Minutes)',
        ZCOREUSER.ZFAMILYMEMBERTYPE AS 'ZCOREUSER.ZFAMILYMEMBERTYPE',
        ZCOREUSER.ZAPPLEID AS 'ZCOREUSER.ZAPPLEID',
        ZCOREUSER.ZDSID AS 'ZCOREUSER.ZDSID',
        ZCOREUSER.ZALTDSID AS 'ZCOREUSER.ZALTDSID'


FROM ZUSAGETIMEDITEM
    LEFT JOIN ZUSAGECATEGORY ON ZUSAGECATEGORY.Z_PK = ZUSAGETIMEDITEM.ZCATEGORY
    LEFT JOIN ZUSAGEBLOCK ON ZUSAGECATEGORY.ZBLOCK = ZUSAGEBLOCK.Z_PK
    LEFT JOIN ZUSAGE ON ZUSAGEBLOCK.ZUSAGE = ZUSAGE.Z_PK
    LEFT JOIN ZCOREUSER ON ZUSAGE.ZUSER = ZCOREUSER.Z_PK
    LEFT JOIN ZCOREDEVICE ON ZUSAGE.ZDEVICE = ZCOREDEVICE.Z_PK


ORDER BY
    ZUSAGEBLOCK.ZSTARTDATE ASC