/*
[Database Metadata]
DATABASE=RMAdminStore-Local.sqlite, RMAdminStore-Cloud.sqlite
*/

SELECT

    DISTINCT
        ROW_NUMBER() OVER() AS 'RecordNo.',
        datetime(ZUSAGEBLOCK.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'StartDateTime(UTC)',
        ZUSAGEBLOCK.ZSCREENTIMEINSECONDS AS 'ScreenTime(Seconds)',
        ZUSAGEBLOCK.ZSCREENTIMEINSECONDS / 60.00 AS 'ScreenTime(Minutes)',
        ZCOREUSER.ZGIVENNAME AS 'GivenName',
        ZCOREUSER.ZFAMILYNAME AS 'FamilyName',
        ZCOREDEVICE.ZNAME AS 'Name',

        CASE ZCOREDEVICE.ZPLATFORM
            WHEN 0 THEN 'Unknown'
            WHEN 1 THEN 'macOS'
            WHEN 2 THEN 'iOS'
            WHEN 4 THEN 'AppleWatch'
            ELSE ZCOREDEVICE.ZPLATFORM
        END AS 'DevicePlatform',

        ZCOREDEVICE.ZIDENTIFIER AS 'DeviceID',
        ZCOREDEVICE.ZLOCALUSERDEVICESTATE AS 'LocalUserDeviceState',
        datetime(ZUSAGEBLOCK.ZLONGESTSESSIONSTARTDATE + 978307200, 'UNIXEPOCH') AS 'LongestSessionStartDateTime(UTC)',
        datetime(ZUSAGEBLOCK.ZLONGESTSESSIONENDDATE + 978307200, 'UNIXEPOCH') AS 'LongestSessionEndDateTime(UTC)',
        datetime(ZUSAGEBLOCK.ZLASTEVENTDATE + 978307200, 'UNIXEPOCH') AS 'LastEventDateTime(UTC)',
        (ZUSAGEBLOCK.ZLONGESTSESSIONENDDATE - ZUSAGEBLOCK.ZLONGESTSESSIONSTARTDATE) AS 'LongestSessionTime(Seconds)',
        (ZUSAGEBLOCK.ZLONGESTSESSIONENDDATE - ZUSAGEBLOCK.ZLONGESTSESSIONSTARTDATE) / 60.00 AS 'LongestSessionTime(Minutes)',
        ZCOREUSER.ZFAMILYMEMBERTYPE AS 'FamilyMemberType',
        ZCOREUSER.ZAPPLEID AS 'AppleID',
        ZCOREUSER.ZDSID AS 'DSID',
        ZCOREUSER.ZALTDSID AS 'AltDSID'


FROM ZUSAGETIMEDITEM
    LEFT JOIN ZUSAGECATEGORY ON ZUSAGECATEGORY.Z_PK = ZUSAGETIMEDITEM.ZCATEGORY
    LEFT JOIN ZUSAGEBLOCK ON ZUSAGECATEGORY.ZBLOCK = ZUSAGEBLOCK.Z_PK
    LEFT JOIN ZUSAGE ON ZUSAGEBLOCK.ZUSAGE = ZUSAGE.Z_PK
    LEFT JOIN ZCOREUSER ON ZUSAGE.ZUSER = ZCOREUSER.Z_PK
    LEFT JOIN ZCOREDEVICE ON ZUSAGE.ZDEVICE = ZCOREDEVICE.Z_PK


ORDER BY
    ZUSAGEBLOCK.ZSTARTDATE ASC