/*
[DLU]
    20-Apr-2026
[FILE PATH]
    \private\var\mobile\Library\Application Support\com.apple.remotemanagementd
[FILE NAMES]
    RMAdminStore-Local.sqlite & RMAdminStore-Cloud.sqlite
*/

SELECT

    ROW_NUMBER() OVER() AS 'record_number',

    datetime(ZUSAGEBLOCK.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'ZUSAGEBLOCK.zstartdate(utc)',
    datetime(ZUSAGEBLOCK.ZLASTEVENTDATE + 978307200, 'UNIXEPOCH') AS 'ZUSAGEBLOCK.zlasteventdate(utc)',

    ZUSAGETIMEDITEM.ZTOTALTIMEINSECONDS AS 'ZUSAGETIMEDITEM.ztotaltimeinseconds',
    ZUSAGETIMEDITEM.ZTOTALTIMEINSECONDS / 60.00 AS 'ztotaltime(minutes)',
    ZUSAGETIMEDITEM.ZBUNDLEIDENTIFIER AS 'ZUSAGETIMEDITEM.zbundleidentifier',

    CASE ZUSAGECATEGORY.ZIDENTIFIER
        WHEN 'DH0011' THEN 'Unspecified 1 [DH0011]'
        WHEN 'DH0012' THEN 'Unspecified 2 [DH0012]'
        WHEN 'DH0013' THEN 'Unspecified 3 [DH0013]'
        WHEN 'DH1001' THEN 'Games [DH1001]'
        WHEN 'DH1002' THEN 'Social Networking [DH1002]'
        WHEN 'DH1003' THEN 'Entertainment [DH1003]'
        WHEN 'DH1004' THEN 'Creativity [DH1004]'
        WHEN 'DH1005' THEN 'Productivity [DH1005]'
        WHEN 'DH1006' THEN 'Education [DH1006]'
        WHEN 'DH1007' THEN 'Reading/Reference [DH1007]'
        WHEN 'DH1008' THEN 'Health/Fitness [DH1008]'
        WHEN 'DH1009' THEN 'Other [DH1009]'
        ELSE ZUSAGECATEGORY.ZIDENTIFIER
    END AS 'ZUSAGECATEGORY.zidentifier',

    ZUSAGECOUNTEDITEM.ZNUMBEROFNOTIFICATIONS AS 'ZUSAGECOUNTEDITEM.znumberofnotifications',
    ZUSAGECOUNTEDITEM.ZNUMBEROFPICKUPS AS 'ZUSAGECOUNTEDITEM.znumberofpickups',
    ZUSAGEBLOCK.ZNUMBEROFPICKUPSWITHOUTAPPLICATIONUSAGE AS 'ZUSAGEBLOCK.znumberofpickupswithoutapplicationusage',
    ZCOREDEVICE.ZNAME AS 'ZCOREDEVICE.zname',
    ZCOREDEVICE.ZIDENTIFIER AS 'ZCOREDEVICE.zidentifier',

    CASE ZCOREDEVICE.ZPLATFORM
        WHEN 0 THEN 'Unknown [0]'
        WHEN 1 THEN 'macOS [1]'
        WHEN 2 THEN 'iOS [2]'
        WHEN 4 THEN 'Apple Watch [4]'
        ELSE ZCOREDEVICE.ZPLATFORM
    END AS 'ZCOREDEVICE.zplatform',

    ZCOREUSER.ZAPPLEID AS 'ZCOREUSER.zappleid',
    ZCOREUSER.ZDSID AS 'ZCOREUSER.zdsid',
    ZCOREUSER.ZALTDSID AS 'ZCOREUSER.zaltdsid',
    ZCOREUSER.ZGIVENNAME || ' ' || ZCOREUSER.ZFAMILYNAME AS 'ZCOREUSER.zgivenname',
    ZCOREUSER.ZFAMILYMEMBERTYPE AS 'ZCOREUSER.zfamilymembertype',

    /* Source for each line of data */
    'Table: ZUSAGEGETIMEDITEM (Z_PK:' || ZUSAGETIMEDITEM.Z_PK || ')' AS 'data_source'


FROM ZUSAGETIMEDITEM
    LEFT JOIN ZUSAGECATEGORY ON ZUSAGECATEGORY.Z_PK = ZUSAGETIMEDITEM.ZCATEGORY
    LEFT JOIN ZUSAGEBLOCK ON ZUSAGEBLOCK.Z_PK = ZUSAGECATEGORY.ZBLOCK
    LEFT JOIN ZUSAGE ON ZUSAGE.Z_PK = ZUSAGEBLOCK.ZUSAGE
    LEFT JOIN ZCOREDEVICE ON ZCOREDEVICE.Z_PK = ZUSAGE.ZDEVICE
    LEFT JOIN ZCOREUSER ON ZCOREUSER.Z_PK = ZUSAGE.ZUSER
    LEFT JOIN ZUSAGECOUNTEDITEM ON ZUSAGECOUNTEDITEM.ZBLOCK = ZUSAGECATEGORY.ZBLOCK AND ZUSAGECOUNTEDITEM.ZBUNDLEIDENTIFIER = ZUSAGETIMEDITEM.ZBUNDLEIDENTIFIER


WHERE
    ZUSAGETIMEDITEM.ZBUNDLEIDENTIFIER LIKE '%whatsapp%'


ORDER BY
    ZUSAGEBLOCK.ZSTARTDATE ASC


--ZUC.ZTOTALTIMEINSECONDS AS 'Total_Time (from ZUC)',
--ZUSAGEBLOCK.ZSCREENTIMEINSECONDS AS 'Screen_Time (from ZUSAGEBLOCK)',
