/*
Copied from https://www.mac4n6.com/blog/2018/8/5/knowledge-is-power-using-the-knowledgecdb-database-on-macos-and-ios-to-determine-precise-user-and-application-usage

[DLU]
    05-Sep-2025
[DATABASE PATH]
    /private/var/mobile/Library/CoreDuet/Knowledge/knowledgeC.db
*/


SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER.',
    ZOBJECT.Z_PK AS 'ZOBJECT.Z_PK',
    ZOBJECT.ZSOURCE AS 'ZOBJECT.ZSOURCE',

    datetime(ZOBJECT.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'ZOBJECT.ZCREATIONDATE(UTC)',

    CASE ZOBJECT.ZSTARTDAYOFWEEK
        WHEN 1 THEN '1 [Sunday]'
        WHEN 2 THEN '2 [Monday]'
        WHEN 3 THEN '3 [Tuesday]'
        WHEN 4 THEN '4 [Wednesday]'
        WHEN 5 THEN '5 [Thursday]'
        WHEN 6 THEN '6 [Friday]'
        WHEN 7 THEN '7 [Saturday]'
    END 'ZOBJECT.ZSTARTDAYOFWEEK',

    datetime(ZOBJECT.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'ZOBJECT.ZSTARTDATE(UTC)',
    datetime(ZOBJECT.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'ZOBJECT.ZENDDATE(UTC)',

    (ZOBJECT.ZENDDATE - ZOBJECT.ZSTARTDATE) AS 'USAGE(SEC)',
    ZSOURCE.ZDEVICEID AS 'ZSOURCE.ZDEVICEID',
    ZOBJECT.ZSTREAMNAME AS 'ZOBJECT.ZSTREAMNAME',
    ZOBJECT.ZVALUESTRING AS 'ZOBJECT.ZVALUESTRING',
    ZSTRUCTUREDMETADATA.Z_DKAPPLICATIONACTIVITYMETADATAKEY__ACTIVITYTYPE AS 'ACTIVITYTYPE',
    ZSTRUCTUREDMETADATA.Z_DKAPPLICATIONACTIVITYMETADATAKEY__TITLE AS 'TITLE',
    ZSTRUCTUREDMETADATA.Z_DKAPPLICATIONACTIVITYMETADATAKEY__USERACTIVITYREQUIREDSTRING AS 'USERACTIVITYREQUIREDSTRING',

    datetime(ZSTRUCTUREDMETADATA.Z_DKAPPLICATIONACTIVITYMETADATAKEY__EXPIRATIONDATE + 978307200, 'UNIXEPOCH') AS 'EXPIRATIONDATE(UTC)',

    ZSTRUCTUREDMETADATA.Z_DKINTENTMETADATAKEY__INTENTCLASS AS 'INTENTCLASS',
    ZSTRUCTUREDMETADATA.Z_DKINTENTMETADATAKEY__INTENTVERB AS 'INTENTVERB',
    ZSTRUCTUREDMETADATA.Z_DKINTENTMETADATAKEY__SERIALIZEDINTERACTION AS 'SERIALIZEDINTERACTION',
    ZSOURCE.ZBUNDLEID AS 'ZSOURCE.ZBUNDLEID',

    /* Source for each line of data */
    'knowledgeC.db; Table: ZOBJECT(Z_PK:' || ZOBJECT.Z_PK || ')' AS 'DATA_SOURCE'


FROM ZOBJECT
    LEFT JOIN ZSTRUCTUREDMETADATA ON ZOBJECT.ZSTRUCTUREDMETADATA = ZSTRUCTUREDMETADATA.Z_PK
    LEFT JOIN ZSOURCE ON ZOBJECT.ZSOURCE = ZSOURCE.Z_PK


WHERE
    ZSTREAMNAME IS '/app/activity'
    OR
    ZSTREAMNAME IS '/app/inFocus'
    OR
    ZSTREAMNAME IS '/app/intents'
    -- AND
    -- ZBUNDLEID IS 'com.toyopagroup.picaboo'


ORDER BY
    ZOBJECT.ZSTARTDATE ASC