/*
    Copied from https://www.mac4n6.com/blog/2018/8/5/knowledge-is-power-using-the-knowledgecdb-database-on-macos-and-ios-to-determine-precise-user-and-application-usage

    [DLU]
        2023-10-20
    [DATABASE PATH]
        /private/var/mobile/Library/CoreDuet/Knowledge/knowledgeC.db
*/


SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER.',
    ZOBJECT.Z_PK AS 'ZOBJECT.Z_PK',
    ZOBJECT.ZSOURCE AS 'ZOBJECT.ZSOURCE',
    datetime(ZOBJECT.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'ZOBJECT.ZCREATIONDATE(UTC)',

    CASE ZOBJECT.ZSTARTDAYOFWEEK
        WHEN '1' THEN 'Sunday'
        WHEN '2' THEN 'Monday'
        WHEN '3' THEN 'Tuesday'
        WHEN '4' THEN 'Wednesday'
        WHEN '5' THEN 'Thursday'
        WHEN '6' THEN 'Friday'
        WHEN '7' THEN 'Saturday'
    END 'ZOBJECT.ZSTARTDAYOFWEEK',

    datetime(ZOBJECT.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'ZOBJECT.ZSTARTDATE(UTC)',
    datetime(ZOBJECT.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'ZOBJECT.ZENDDATE(UTC)',

    (ZOBJECT.ZENDDATE-ZOBJECT.ZSTARTDATE) AS 'USAGE(SEC)',
    ZSOURCE.ZDEVICEID AS 'ZSOURCE.ZDEVICEID',
    ZOBJECT.ZSTREAMNAME AS 'ZOBJECT.ZSTREAMNAME',
    ZOBJECT.ZVALUESTRING AS 'ZOBJECT.ZVALUESTRING',
    ZSTRUCTUREDMETADATA.Z_DKAPPLICATIONACTIVITYMETADATAKEY__ACTIVITYTYPE AS 'AcitivityType',
    ZSTRUCTUREDMETADATA.Z_DKAPPLICATIONACTIVITYMETADATAKEY__TITLE AS 'Title',
    ZSTRUCTUREDMETADATA.Z_DKAPPLICATIONACTIVITYMETADATAKEY__USERACTIVITYREQUIREDSTRING AS 'ActivityString',
    datetime(ZSTRUCTUREDMETADATA.Z_DKAPPLICATIONACTIVITYMETADATAKEY__EXPIRATIONDATE + 978307200, 'UNIXEPOCH') AS 'ExpirationDateTime(UTC)',
    ZSTRUCTUREDMETADATA.Z_DKINTENTMETADATAKEY__INTENTCLASS AS 'IntentClass',
    ZSTRUCTUREDMETADATA.Z_DKINTENTMETADATAKEY__INTENTVERB AS 'IntentVerb',
    ZSTRUCTUREDMETADATA.Z_DKINTENTMETADATAKEY__SERIALIZEDINTERACTION AS 'SerializedInteraction',
    ZSOURCE.ZBUNDLEID AS 'Bundle ID',

    /* Source for each line of data */
    '/private/var/mobile/Library/CoreDuet/Knowledge/knowledgeC.db; Table: ZOBJECT(Z_PK:' || ZOBJECT.Z_PK || ')' AS 'DATA_SOURCE'


FROM ZOBJECT
    LEFT JOIN ZSTRUCTUREDMETADATA ON ZOBJECT.ZSTRUCTUREDMETADATA = ZSTRUCTUREDMETADATA.Z_PK
    LEFT JOIN ZSOURCE ON ZOBJECT.ZSOURCE = ZSOURCE.Z_PK


WHERE
    ZSTREAMNAME IS '/app/activity' OR
    ZSTREAMNAME IS '/app/inFocus' OR
    ZSTREAMNAME IS '/app/intents' AND
    ZBUNDLEID IS 'com.toyopagroup.picaboo'


ORDER BY
    ZOBJECT.ZSTARTDATE ASC