/*
[DLU]
    05-Sep-2025
[DATABASE PATH]
    /private/var/mobile/Library/CoreDuet/Knowledge/knowledgeC.db
*/

SELECT

    ROW_NUMBER() OVER() AS 'ROW_NUMBER',
    ZOBJECT.Z_PK AS 'ZOBJECT.Z_PK',

    datetime(ZOBJECT.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'ZOBJECT.ZCREATIONDATE(UTC)'
    datetime(ZOBJECT.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'ZOBJECT.ZSTARTDATE(UTC)',
    datetime(ZOBJECT.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'ZOBJECT.ZENDDATE(UTC)',

    (ZOBJECT.ZSECONDSFROMGMT / 3600) AS 'GMTOFFSET(HOURS)',

    CASE ZOBJECT.ZSTARTDAYOFWEEK
        WHEN 1 THEN '1 [Sunday]'
        WHEN 2 THEN '2 [Monday]'
        WHEN 3 THEN '3 [Tuesday]'
        WHEN 4 THEN '4 [Wednesday]'
        WHEN 5 THEN '5 [Thursday]'
        WHEN 6 THEN '6 [Friday]'
        WHEN 7 THEN '7 [Saturday]'
        ELSE ZOBJECT.ZSTARTDAYOFWEEK
    END 'ZOBJECT.ZSTARTDAYOFWEEK',

    (ZOBJECT.ZENDDATE - ZOBJECT.ZSTARTDATE) AS 'USAGE(SECONDS)',
    (ZOBJECT.ZENDDATE - ZOBJECT.ZSTARTDATE) / 60.00 AS 'USAGE(MINUTES)',
    ZOBJECT.ZSTREAMNAME AS 'ZOBJECT.ZSTREAMNAME',
    --ZOBJECT.ZVALUESTRING AS 'Value String',
    ZSTRUCTUREDMETADATA.Z_DKAUDIOMETADATAKEY__IDENTIFIER AS 'AUDIOIDENTIFIER',
    ZSTRUCTUREDMETADATA.Z_DKAUDIOMETADATAKEY__PORTNAME AS 'AUDIOPORTNAME',
    ZSTRUCTUREDMETADATA.Z_DKAUDIOMETADATAKEY__PORTTYPE AS 'AUDIOPORTTYPE',
    ZSTRUCTUREDMETADATA.Z_DKBLUETOOTHMETADATAKEY__ADDRESS AS 'BLUETOOTHADDRESS',
    ZSTRUCTUREDMETADATA.Z_DKBLUETOOTHMETADATAKEY__NAME AS 'BLUETOOTHNAME',
    ZSTRUCTUREDMETADATA.Z_DKNOWPLAYINGMETADATAKEY__ARTIST AS 'NOWPLAYINGARTIST',
    ZSTRUCTUREDMETADATA.Z_DKNOWPLAYINGMETADATAKEY__TITLE AS 'NOWPLAYINGTITLE',
    ZSTRUCTUREDMETADATA.Z_DKNOWPLAYINGMETADATAKEY__ALBUM AS 'NOWPLAYINGALBUM',
    ZSTRUCTUREDMETADATA.Z_DKNOWPLAYINGMETADATAKEY__GENRE AS 'NOWPLAYINGGENRE',
    ZSTRUCTUREDMETADATA.Z_DKNOWPLAYINGMETADATAKEY__DURATION AS 'NOWPLAYINGDURATION(SECONDS)',

    /* Source for each line of data */
    'knowledgeC.db; Table: ZOBJECT(Z_PK:' || ZOBJECT.Z_PK || ')' AS 'DATA_SOURCE'


FROM ZOBJECT
    LEFT JOIN ZSTRUCTUREDMETADATA ON ZOBJECT.ZSTRUCTUREDMETADATA = ZSTRUCTUREDMETADATA.Z_PK
    LEFT JOIN ZSOURCE ON ZOBJECT.ZSOURCE = ZSOURCE.Z_PK


WHERE
    ZSTREAMNAME LIKE '/audio%' OR
    ZSTREAMNAME LIKE '/bluetooth%' OR
    ZSTREAMNAME LIKE '/media%'


ORDER BY
    ZOBJECT.ZSTARTDATE DESC
