/*
[DLU]
    05-Sep-2025
[DATABASE PATH]
    /private/var/mobile/Library/CoreDuet/Knowledge/knowledgeC.db
*/

SELECT

    ROW_NUMBER() OVER() AS 'ROW_NUMBER',
    ZOBJECT.Z_PK AS 'ZOBJECT.Z_PK',

    CASE ZOBJECT.ZSTARTDAYOFWEEK
        WHEN '1' THEN '1 [Sunday]'
        WHEN '2' THEN '2 [Monday]'
        WHEN '3' THEN '3 [Tuesday]'
        WHEN '4' THEN '4 [Wednesday]'
        WHEN '5' THEN '5 [Thursday]'
        WHEN '6' THEN '6 [Friday]'
        WHEN '7' THEN '7 [Saturday]'
        ELSE ZOBJECT.ZSTARTDAYOFWEEK
    END AS 'ZOBJECT.ZSTARTDAYOFWEEK',

    datetime(ZOBJECT.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'ZOBJECT.ZSTARTDATE(UTC)',
    datetime(ZOBJECT.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'ZOBJECT.ZENDDATE(UTC)',
    (ZOBJECT.ZSECONDSFROMGMT / 3600) AS 'ZOBJECT.ZSECONDSFROMGMT',
    (ZOBJECT.ZENDDATE - ZOBJECT.ZSTARTDATE) AS 'USAGE(Seconds)',
    ROUND(((ZOBJECT.ZENDDATE - ZOBJECT.ZSTARTDATE) / 60.00), 4) AS 'USAGE(Minutes)',
    ZOBJECT.ZSTREAMNAME AS 'ZOBJECT.ZSTREAMNAME',

    CASE ZOBJECT.ZVALUEINTEGER
        WHEN '0.0' THEN '0.0 [False]'
        WHEN '1.0' THEN '1.0 [True]'
        ELSE ZOBJECT.ZVALUEINTEGER
    END AS 'ZOBJECT.ZVALUEINTEGER',

    datetime(ZOBJECT.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'ZOBJECT.ZCREATIONDATE(UTC)'

    /* Source for each line of data */
    'knowledgeC.db; Table: ZOBJECT(Z_PK:' || ZOBJECT.Z_PK || ')' AS 'DATA_SOURCE'


FROM ZOBJECT
    LEFT JOIN ZSTRUCTUREDMETADATA on ZOBJECT.ZSTRUCTUREDMETADATA = ZSTRUCTUREDMETADATA.Z_PK
    LEFT JOIN ZSOURCE on ZOBJECT.ZSOURCE = ZSOURCE.Z_PK


WHERE
    ZSTREAMNAME LIKE '/device%'
    --ZSTREAMNAME LIKE '/device/batteryPercentage'
    --or ZSTREAMNAME LIKE '/device/batterySaver'
    --or ZSTREAMNAME LIKE '/device/isLocked'
    --or ZSTREAMNAME LIKE '/device/isPluggedIn'


ORDER BY
    ZOBJECT.ZSTARTDATE DESC
