/*
  DLU: 2024-10-17
  [VERSION]
    Tested on iOS 18
  [SMS]
    FILE PATH = /private/var/mobile/Library/CoreDuet/People/interactionC.db
*/


SELECT
    ROW_NUMBER() OVER() AS 'RecordNo.',
    ZINTERACTIONS.Z_PK AS 'InteractionsPK',

    CASE ZINTERACTIONS.ZDIRECTION
        WHEN 0 THEN 'Incoming'
        WHEN 1 THEN 'Outgoing'
        ELSE ZINTERACTIONS.ZDIRECTION
    END AS 'Direction',

    ZINTERACTIONS.ZBUNDLEID AS 'BundleID',
    ZINTERACTIONS.ZDOMAINIDENTIFIER AS 'DomainIdentifier',
    ZINTERACTIONS.ZGROUPNAME AS 'GroupName',
    ZINTERACTIONS.ZSENDER AS 'Sender',
    Z_2INTERACTIONRECIPIENT.Z_2RECIPIENTS AS 'InteractionRecipients',
    ZCONTACTS.ZDISPLAYNAME AS 'ContactDisplayName',
    ZCONTACTS.ZIDENTIFIER AS 'ContactsIdentifier',
    ZINTERACTIONS.ZCONTENTURL AS 'ContentURL',
    datetime(ZINTERACTIONS.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'StartDateTime(UTC)',
    datetime(ZINTERACTIONS.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'EndDateTime(UTC)',
    datetime(ZINTERACTIONS.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'CreationDateTime(UTC)',
    datetime(ZINTERACTIONS.ZUPDATEDATE + 978307200, 'UNIXEPOCH') AS 'UpdateDateTime(UTC)',
    ZCONTACTS.ZINCOMINGRECIPIENTCOUNT AS 'IncomingRecipientCount',
    datetime(ZCONTACTS.ZFIRSTINCOMINGRECIPIENTDATE + 978307200, 'UNIXEPOCH') AS 'FirstIncomingRecipientDateTime(UTC)',
    ZCONTACTS.ZINCOMINGSENDERCOUNT AS 'IncomingSenderCount',
    datetime(ZCONTACTS.ZFIRSTINCOMINGSENDERDATE + 978307200, 'UNIXEPOCH') AS 'FirstIncomingSenderDateTime(UTC)',
    ZCONTACTS.ZOUTGOINGRECIPIENTCOUNT AS 'OutgoingRecipientCount',
    datetime(ZCONTACTS.ZFIRSTOUTGOINGRECIPIENTDATE + 978307200, 'UNIXEPOCH') AS 'FirstOutgoingRecipientDateTime(UTC)',

    CASE
        WHEN ZCONTACTS.ZLASTINCOMINGRECIPIENTDATE IS 0 THEN NULL
        ELSE datetime(ZCONTACTS.ZLASTINCOMINGRECIPIENTDATE + 978307200, 'UNIXEPOCH')
    END AS 'LastIncomingRecipientDateTime(UTC)',

    datetime(ZCONTACTS.ZLASTINCOMINGSENDERDATE + 978307200, 'UNIXEPOCH') AS 'LastIncomingSenderDateTime(UTC)',
    datetime(ZCONTACTS.ZLASTOUTGOINGRECIPIENTDATE + 978307200, 'UNIXEPOCH') AS 'LastOutgoingRecipientDateTime(UTC)',

    --Source for each line of data
    '/private/var/mobile/Library/CoreDuet/People/interactionC.db' AS 'DatabaseFile',
    'Table: ZINTERACTIONS(Z_PK: ' || ZINTERACTIONS.Z_PK || ')' AS 'DataSource'

FROM ZINTERACTIONS

    LEFT JOIN Z_2INTERACTIONRECIPIENT ON ZINTERACTIONS.Z_PK = Z_2INTERACTIONRECIPIENT.Z_3INTERACTIONRECIPIENT
    LEFT JOIN ZCONTACTS ON ZINTERACTIONS.ZSENDER = ZCONTACTS.Z_PK

WHERE
    --To filter between date/time points
    ZINTERACTIONS.ZSTARTDATE BETWEEN 750312000 AND 750449160

ORDER BY ZINTERACTIONS.ZSTARTDATE ASC
