
-- changed album name due to iOS 14.x change.

SELECT
    ROW_NUMBER() OVER() AS 'RecordNo.',

    ZASSET.Z_PK AS 'IndexNo.',

    ZASSET.ZDIRECTORY AS 'Directory',

    ZASSET.ZFILENAME AS 'FileName',

    ZADDITIONALASSETATTRIBUTES.ZORIGINALFILENAME AS 'OriginalFileName',

    CASE ZASSET.ZKINDZUNIFORMTYPEIDENTIFIER
        WHEN '0' THEN 'Photo'
        WHEN '1' THEN 'Video'
        ELSE ZASSET.ZKINDZUNIFORMTYPEIDENTIFIER
    END AS 'FileType',

    ZASSET.ZUNIFORMTYPEIDENTIFIER AS 'MIMEType',

    CASE ZASSET.ZFAVORITE
        WHEN '0' THEN 'No'
        WHEN '1' THEN 'Yes'
        ELSE ZASSET.ZFAVORITE
    END AS 'Favorite',

    CASE
        WHEN LENGTH(ZASSET.ZDATECREATED) = 18 THEN datetime((ZASSET.ZDATECREATED / 1000000000) + 978307200, 'UNIXEPOCH')
        WHEN LENGTH(ZASSET.ZDATECREATED) = 9 THEN datetime(ZASSET.ZDATECREATED + 978307200, 'UNIXEPOCH')
        ELSE ZASSET.ZDATECREATED
    END AS 'DateCreated(UTC)',

    datetime(ZASSET.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'Date Added (UTC)',

    datetime(ZASSET.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'ModificationDate(UTC)',

    CASE
        WHEN ZADDITIONALASSETATTRIBUTES.ZEXIFTIMESTAMPSTRING IS NULL THEN 'n/a'
        ELSE ZADDITIONALASSETATTRIBUTES.ZEXIFTIMESTAMPSTRING
    END AS 'EXIFTimeStamp(UTC)',

    CASE
        WHEN ZASSET.ZTRASHEDDATE IS NULL THEN 'n/a'
        ELSE datetime(ZASSET.ZTRASHEDDATE + 978307200, 'UNIXEPOCH')
    END AS 'FileTrashDate(UTC)',

    ZADDITIONALASSETATTRIBUTES.ZVIEWCOUNT AS 'ViewCount',

    ZADDITIONALASSETATTRIBUTES.ZSHARECOUNT AS 'ShareCount',

    CASE
        WHEN ZASSET.ZLASTSHAREDDATE IS NULL THEN 'n/a'
        ELSE datetime(ZASSET.ZLASTSHAREDDATE + 978307200, 'UNIXEPOCH')
    END AS 'LastSharedDate(UTC)',

    ZADDITIONALASSETATTRIBUTES.ZPLAYCOUNT AS 'PlayCount',

    CASE ZASSET.ZHIDDEN
        WHEN '0' THEN 'No'
        WHEN '1' THEN 'Yes'
        ELSE 'Contact Examiner'
    END 'IsHidden',

    ZASSET.ZDURATION AS 'Duration(seconds)',

    ZADDITIONALASSETATTRIBUTES.ZIMPORTEDBY AS 'ImportedBy',
    
    ZADDITIONALASSETATTRIBUTES.ZCAMERACAPTUREDEVICE AS 'CameraCaptureDevice',
    
    ZADDITIONALASSETATTRIBUTES.ZORIGINALFILESIZE AS 'OriginalFileSize',

    ZADDITIONALASSETATTRIBUTES.ZORIGINALHEIGHT AS 'OriginalHeight',

    ZADDITIONALASSETATTRIBUTES.ZORIGINALWIDTH AS 'OriginalWidth',

    ZASSET.ZTHUMBNAILINDEX AS 'ThumbnailIndex',

    CASE
        WHEN ZADDITIONALASSETATTRIBUTES.ZCREATORBUNDLEID IS NULL THEN 'n/a'
        ELSE ZADDITIONALASSETATTRIBUTES.ZCREATORBUNDLEID
    END AS 'CreatorBundle',

    CASE
        WHEN ZADDITIONALASSETATTRIBUTES.ZEDITORBUNDLEID IS NULL THEN 'n/a'
        ELSE ZADDITIONALASSETATTRIBUTES.ZEDITORBUNDLEID
    END AS 'EditorBundle',

    ZADDITIONALASSETATTRIBUTES.ZLOCATIONHASH AS 'LocationHash',

    ZADDITIONALASSETATTRIBUTES.ZMASTERFINGERPRINT AS 'MasterFingerPrint',

    CASE ZASSET.ZLATITUDE
        WHEN '-180.0' THEN 'n/a'
        ELSE ZASSET.ZLATITUDE
    END 'LATITUDE',

    CASE ZASSET.ZLONGITUDE
        WHEN '-180.0' THEN 'n/a'
        ELSE ZASSET.ZLONGITUDE
    END 'LONGITUDE'

FROM ZASSET
    JOIN ZADDITIONALASSETATTRIBUTES ON ZASSET.Z_PK = ZADDITIONALASSETATTRIBUTES.ZASSET

ORDER BY ZASSET.ZADDEDDATE ASC

/*

To get info for specific media files, enter the file name below

DO NOT put "OR" after the last file name

*/

-- WHERE (
--     ZFILENAME LIKE 'IMG 9007.JPG' OR
--     ZFILENAME LIKE 'IMG 9014.GIF' OR
--     ZFILENAME LIKE 'IMG 9037.JPG' OR
--     ZFILENAME LIKE 'IMG 9049.PNG' OR
--     ZFILENAME LIKE 'IMG 9058.JPG' OR
--     ZFILENAME LIKE 'IMG 9064.JPG' OR
--     ZFILENAME LIKE 'IMG 9092.JPG' OR
--     ZFILENAME LIKE 'IMG 9095.JPG' OR
--     ZFILENAME LIKE 'IMG 9123.PNG' OR
--     ZFILENAME LIKE 'IMG 9253.JPG'
--    )

/*
Use 'DESC' for decending order (most recent date on top)
Use 'ASC' for acending order (most recent date on bottom)
*/

