SELECT
    /* Add a row number at the beggining of each row */
    ROW_NUMBER() OVER() AS 'Row #',
    ZASSET.Z_PK AS 'ZASSET.Z_PK',
    ZASSET.ZADDITIONALATTRIBUTES AS 'Add Attributes Key',
    ZASSET.ZDIRECTORY AS 'Directory',
    ZASSET.ZFILENAME AS 'File Name',
    CASE ZASSET.ZKIND
        WHEN 0 THEN 'Photo'
        WHEN 1 THEN 'Video'
        ELSE ZASSET.ZKIND
    END AS 'File Type',
    ZASSET.ZUNIFORMTYPEIDENTIFIER AS 'MIME Type',
    CASE
        WHEN LENGTH(ZASSET.ZDATECREATED) = 18 THEN datetime((ZASSET.ZDATECREATED / 1000000000) + 978307200, 'UNIXEPOCH')
        WHEN LENGTH(ZASSET.ZDATECREATED) = 9 THEN datetime(ZASSET.ZDATECREATED + 978307200, 'UNIXEPOCH')
        ELSE datetime(ZASSET.ZDATECREATED + 978307200, 'UNIXEPOCH')
    END AS 'Date Created (UTC)',
    ZADDITIONALASSETATTRIBUTES.ZEXIFTIMESTAMPSTRING AS 'EXIF TimeStamp',
    datetime(ZADDITIONALASSETATTRIBUTES.ZSCENEANALYSISTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'Scene Analysis TimeStamp (UTC)',
    datetime(ZASSET.ZANALYSISSTATEMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'Analysis State Modification Date (UTC)',
    datetime(ZASSET.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'Add Date (UTC)',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALFILENAME AS 'Original Filename',
    ZGENERICALBUM.ZTITLE AS 'Album Title',
    ZADDITIONALASSETATTRIBUTES.ZCREATORBUNDLEID AS 'Creator Bundle ID',
    ZADDITIONALASSETATTRIBUTES.ZEDITORBUNDLEID AS 'Editor Bundle ID',
    CASE ZASSET.ZSAVEDASSETTYPE
        WHEN 0 THEN 'Saved from other source'
        WHEN 2 THEN 'Photo Streams Data'
        WHEN 3 THEN 'Made/saved with this device'
        WHEN 4 THEN 'Default row'
        WHEN 7 THEN 'Deleted'
        ELSE ZASSET.ZSAVEDASSETTYPE
    END AS 'Saved Asset Type',
    CASE
        WHEN ZASSET.ZFACEAREAPOINTS > 0 THEN 'Yes'
        ELSE ZASSET.ZFACEAREAPOINTS 
    END AS 'Face Detected in Photo',
    ZPERSON.ZDISPLAYNAME AS 'Display Name',
    ZPERSON.ZFULLNAME AS 'Full Name',
    ZPERSON.ZFACECOUNT AS 'Face Count',
    ZDETECTEDFACE.ZPERSON AS 'Person',
    ZPERSON.ZCONTACTMATCHINGDICTIONARY AS 'Contact Blob',
    ZPERSON.ZPERSONUUID as 'Person UUID',
    ZDETECTEDFACE.ZASSET AS 'Detected Face Asset',
    ZDETECTEDFACE.ZQUALITYMEASURE AS 'Detected Face Quality',
    CASE ZDETECTEDFACE.ZAGETYPE
        WHEN 1 THEN 'Baby/Toddler'
        WHEN 2 THEN 'Baby/Toddler'
        WHEN 3 THEN 'Child/YoungAdult'
        WHEN 4 THEN 'YoungAdult/Adult'
        WHEN 5 THEN 'Adult'
        ELSE ZDETECTEDFACE.ZAGETYPE
    END AS 'Age Type Estimate',
    CASE ZDETECTEDFACE.ZGENDERTYPE
        WHEN 1 THEN 'Male'
        WHEN 2 THEN 'Female'
        ELSE ZDETECTEDFACE.ZGENDERTYPE
    END AS 'Gender',
    CASE ZDETECTEDFACE.ZGLASSESTYPE
        WHEN 1 THEN 'Eye'
        WHEN 2 THEN 'Sun'
        WHEN 3 THEN 'None'
        ELSE ZDETECTEDFACE.ZGLASSESTYPE
    END AS 'Glasses Type',
    CASE ZDETECTEDFACE.ZFACIALHAIRTYPE
        WHEN 1 THEN 'None'
        WHEN 2 THEN 'Beard/Mustache'
        WHEN 3 THEN 'Goatee'
        WHEN 5 THEN 'Stubble'
        ELSE ZDETECTEDFACE.ZFACIALHAIRTYPE
    END AS 'Facial Hair Type',
    CASE ZDETECTEDFACE.ZHAIRTYPE
        WHEN 2 THEN 'Bald'
        WHEN 3 THEN 'Not Bald'
        ELSE ZDETECTEDFACE.ZHAIRTYPE
    END AS 'Baldness',
    ZASSET.ZORIGINALCOLORSPACE AS 'Color Space',
    ZASSET.ZDURATION AS 'Duration (Seconds)',
    ZASSET.ZVIDEOCPDURATIONVALUE AS 'Video Duration',
    CASE ZASSET.ZCOMPLETE
        WHEN 1 THEN 'Yes'
        ELSE 'Contact Examiner'
    END AS 'Complete',
    CASE ZASSET.ZVISIBILITYSTATE
        WHEN 0 THEN 'Visible'
        WHEN 1 THEN 'Photo Streams Data'
        WHEN 2 THEN 'Burst'
        ELSE ZASSET.ZVISIBILITYSTATE
    END AS 'VisibilityState',
    CASE ZASSET.ZFAVORITE 
        WHEN 0 THEN 'No'
        WHEN 1 THEN 'Yes'
        ELSE 'Contact Examiner'
    END AS 'Favorite',
    CASE ZASSET.ZHIDDEN
        WHEN 0 THEN 'Not Hidden'
        WHEN 1 THEN 'File Hidden'
        ELSE ZASSET.ZHIDDEN
    END AS 'Hidden File',
    CASE ZASSET.ZTRASHEDSTATE
        WHEN 1 THEN 'In Trash'
        WHEN 0 THEN 'Not In Trash'
        ELSE ZASSET.ZTRASHEDSTATE
    END AS 'Trash State',
    CASE
        WHEN ZASSET.ZTRASHEDDATE IS NULL THEN 'n/a'
        ELSE datetime(ZASSET.ZTRASHEDDATE + 978307200, 'UNIXEPOCH')
    END AS 'File Trash Date (UTC)',
    ZADDITIONALASSETATTRIBUTES.ZVIEWCOUNT AS 'View Count',
    ZADDITIONALASSETATTRIBUTES.ZPLAYCOUNT AS 'Play Count',
    ZADDITIONALASSETATTRIBUTES.ZSHARECOUNT AS 'Share Count',
    datetime(ZASSET.ZLASTSHAREDDATE + 978307200, 'UNIXEPOCH') AS 'Last Shared Date (UTC)',
    datetime(ZASSET.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'File Modification Date (UTC)',
    CASE ZASSET.ZHASADJUSTMENTS
        WHEN 0 THEN 'No'
        WHEN 1 THEN 'Yes'
        ELSE ZASSET.ZHASADJUSTMENTS
    END AS 'Has Adjustments',
    datetime(ZASSET.ZADJUSTMENTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'Adjustments Time Stamp (UTC)',
    printf("%,d", ZADDITIONALASSETATTRIBUTES.ZORIGINALFILESIZE) AS 'Original File Size (bytes)',
    ZADDITIONALASSETATTRIBUTES.ZCAMERACAPTUREDEVICE AS 'Camera Capture Device',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALHEIGHT AS 'Original File Height',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALWIDTH AS 'Original File Width',
    ZASSET.ZHEIGHT AS 'File Height',
    ZASSET.ZWIDTH AS 'File Width',
    CASE ZADDITIONALASSETATTRIBUTES.ZORIGINALORIENTATION 
        WHEN 1 THEN 'Horizontal (Left)'
        WHEN 3 THEN 'Horizontal (Right)'
        WHEN 6 THEN 'Vertical (Up)'
        WHEN 8 THEN 'Vertical (Down)'
        ELSE ZASSET.ZORIENTATION
    END AS 'Original Orientation',
    CASE ZASSET.ZORIENTATION
        WHEN 1 THEN 'Horizontal (Left)'
        WHEN 3 THEN 'Horizontal (Right)'
        WHEN 6 THEN 'Vertical (Up)'
        WHEN 8 THEN 'Vertical (Down)'
        ELSE ZASSET.ZORIENTATION
    END AS 'Orientation',
    ZADDITIONALASSETATTRIBUTES.ZTIMEZONENAME AS 'Time Zone Name',
    ZADDITIONALASSETATTRIBUTES.ZTIMEZONEOFFSET AS 'Time Zone Offset',
    ZADDITIONALASSETATTRIBUTES.ZINFERREDTIMEZONEOFFSET AS 'Inferred Time Zone Offset',
    ZASSET.ZLOCATIONDATA AS 'File Location Data',
    CASE ZASSET.ZLATITUDE
        WHEN -180.0 THEN 'n/a'
        ELSE ZASSET.ZLATITUDE
    END 'LATITUDE',
    CASE ZASSET.ZLONGITUDE
        WHEN -180.0 THEN 'n/a'
        ELSE ZASSET.ZLONGITUDE
    END 'LONGITUDE',
    CASE ZADDITIONALASSETATTRIBUTES.ZSHIFTEDLOCATIONISVALID
        WHEN 0 THEN 'No'
        WHEN 1 THEN 'Yes'
        ELSE ZADDITIONALASSETATTRIBUTES.ZSHIFTEDLOCATIONISVALID
    END AS 'Shifted Location Valid',
    CASE ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATAISVALID
        WHEN 0 THEN 'No'
        WHEN 1 THEN 'Yes'
        ELSE ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATAISVALID
    END AS 'Reverse Location Data Is Valid',
    ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATA AS 'Org File Reverse Location Data',
    ZASSET.ZTHUMBNAILINDEX AS 'Thumbnail Index',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILWIDTH AS 'Embedded Thumbnail Width',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILHEIGHT AS 'Embedded Thumbnail Height',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILOFFSET AS 'Embedded Thumbnail Offset',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILLENGTH AS 'Embedded Thumbnail Length',
    ZASSET.ZMOMENT AS 'Moment PK',
    ZMOMENT.ZTITLE AS 'Moment Title',
    datetime(ZMOMENT.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'Moment Start Date (UTC)',
    datetime(ZMOMENT.ZREPRESENTATIVEDATE + 978307200, 'UNIXEPOCH') AS 'Moment Representative Date (UTC)',
    datetime(ZMOMENT.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'Moment Modification Date (UTC)',
    datetime(ZMOMENT.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'Moment End Date (UTC)',
    CASE ZMOMENT.ZAPPROXIMATELATITUDE
        WHEN -180.0 THEN 'n/a'
        ELSE ZMOMENT.ZAPPROXIMATELATITUDE
    END AS 'Moment Approx. Latitude',
    CASE ZMOMENT.ZAPPROXIMATELONGITUDE
        WHEN -180.0 THEN 'n/a'
        ELSE ZMOMENT.ZAPPROXIMATELONGITUDE
    END AS 'Moment Approx. Longitude',
    ZASSET.ZUUID AS 'UUID',
    ZASSET.ZMEDIAGROUPUUID AS 'Media Group UUID',
    ZASSET.ZCLOUDASSETGUID AS 'Cloud Asset GUID',
    ZADDITIONALASSETATTRIBUTES.ZPUBLICGLOBALUUID AS 'Public Global UUID',
    ZADDITIONALASSETATTRIBUTES.ZMASTERFINGERPRINT AS 'Master Fingerprint',
    ZADDITIONALASSETATTRIBUTES.ZADJUSTEDFINGERPRINT AS 'Adjusted Fingerprint',
    /* Source for each line of data */
    'File: \private\var\mobile\Library\Photos\Syndication.photolibrary\database\Photos.sqlite; Table: ZASSET(Z_PK: ' || ZASSET.Z_PK || ')' AS 'Data Source'

FROM ZASSET
    LEFT JOIN ZMOMENT ON ZASSET.ZMOMENT = ZMOMENT.Z_PK
    JOIN ZADDITIONALASSETATTRIBUTES ON ZASSET.ZADDITIONALATTRIBUTES = ZADDITIONALASSETATTRIBUTES.Z_PK
    LEFT JOIN ZDETECTEDFACE ON ZADDITIONALASSETATTRIBUTES.ZASSET = ZDETECTEDFACE.ZASSET
    LEFT JOIN ZPERSON ON ZPERSON.Z_PK = ZDETECTEDFACE.ZPERSON
    LEFT JOIN Z_27ASSETS ON ZASSET.Z_PK = Z_27ASSETS.Z_3ASSETS
    LEFT JOIN ZGENERICALBUM ON ZGENERICALBUM.Z_PK = Z_27ASSETS.Z_27ALBUMS

ORDER BY ZASSET.Z_PK ASC
