/*
[Database Metadata]
DATABASE=RMAdminStore-Local.sqlite, RMAdminStore-Cloud.sqlite
*/

SELECT
        DISTINCT
        datetime(ZUSAGEBLOCK.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'HOUR',
        ZUSAGEBLOCK.ZSCREENTIMEINSECONDS AS 'SCREENTIME (SECONDS)',
        ZUSAGEBLOCK.ZSCREENTIMEINSECONDS / 60.00 AS 'SCREENTIME (MINUTES)',
        ZCOREUSER.ZGIVENNAME AS 'GIVEN NAME',
        ZCOREUSER.ZFAMILYNAME AS 'FAMILY NAME',
        ZCOREDEVICE.ZNAME AS 'NAME',
        CASE ZCOREDEVICE.ZPLATFORM
            WHEN 0 THEN 'Unknown'
            WHEN 1 THEN 'macOS'
            WHEN 2 THEN 'iOS'
            WHEN 4 THEN 'Apple Watch'
            ELSE ZPLATFORM
        END AS PLATFORM,
        ZCOREDEVICE.ZIDENTIFIER AS 'DEVICE ID',
        ZCOREDEVICE.ZLOCALUSERDEVICESTATE AS 'LOCAL USER DEVICE STATE',
        datetime(ZUSAGEBLOCK.ZLONGESTSESSIONSTARTDATE + 978307200, 'UNIXEPOCH') AS 'LONGEST SESSION START',
        datetime(ZUSAGEBLOCK.ZLONGESTSESSIONENDDATE + 978307200, 'UNIXEPOCH') AS 'LONGEST SESSION END',
        datetime(ZUSAGEBLOCK.ZLASTEVENTDATE + 978307200, 'UNIXEPOCH') AS 'LAST EVENT DATE',
        (ZLONGESTSESSIONENDDATE-ZLONGESTSESSIONSTARTDATE) AS 'LONGEST SESSION TIME (SECONDS)',
        (ZLONGESTSESSIONENDDATE-ZLONGESTSESSIONSTARTDATE) / 60.00 AS 'LONGEST SESSION TIME (MINUTES)',
        ZCOREUSER.ZFAMILYMEMBERTYPE AS 'FAMILY MEMBER TYPE',
        ZCOREUSER.ZAPPLEID AS 'APPLE ID',
        ZCOREUSER.ZDSID AS 'DSID',
        ZCOREUSER.ZALTDSID AS 'ALT DSID'

    FROM ZUSAGETIMEDITEM
        LEFT JOIN ZUSAGECATEGORY ON ZUSAGECATEGORY.Z_PK == ZUSAGETIMEDITEM.ZCATEGORY
        LEFT JOIN ZUSAGEBLOCK ON ZUSAGECATEGORY.ZBLOCK == ZUSAGEBLOCK.Z_PK
        LEFT JOIN ZUSAGE ON ZUSAGEBLOCK.ZUSAGE == ZUSAGE.Z_PK
        LEFT JOIN ZCOREUSER ON ZUSAGE.ZUSER == ZCOREUSER.Z_PK
        LEFT JOIN ZCOREDEVICE ON ZUSAGE.ZDEVICE == ZCOREDEVICE.Z_PK