SELECT
    /* Add a row number at the beggining of each row */
    ROW_NUMBER() OVER() AS 'Row #',
    ZGENERICASSET.Z_PK AS 'Asset ZPK',
    ZGENERICASSET.ZADDITIONALATTRIBUTES AS 'Add Attributes Key',
    ZDETECTEDFACE.ZASSET AS 'Detected Face Asset',
    CASE ZGENERICASSET.ZKIND
        WHEN 0 THEN 'Photo'
        WHEN 1 THEN 'Video'
        ELSE ZGENERICASSET.ZKIND
    END AS 'File Type',
    ZGENERICASSET.ZUNIFORMTYPEIDENTIFIER AS 'MIME Type',
    CASE
        WHEN LENGTH(ZGENERICASSET.ZDATECREATED) = 18 THEN datetime((ZGENERICASSET.ZDATECREATED / 1000000000) + 978307200, 'UNIXEPOCH')
        WHEN LENGTH(ZGENERICASSET.ZDATECREATED) = 9 THEN datetime(ZGENERICASSET.ZDATECREATED + 978307200, 'UNIXEPOCH')
        ELSE ZGENERICASSET.ZDATECREATED
    END AS 'Date Created (UTC)',
    ZADDITIONALASSETATTRIBUTES.ZEXIFTIMESTAMPSTRING AS 'EXIF TimeStamp',
    datetime(ZADDITIONALASSETATTRIBUTES.ZSCENEANALYSISTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'Scene Analysis TimeStamp (UTC)',
    datetime(ZGENERICASSET.ZANALYSISSTATEMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'Analysis State Modification Date (UTC)',
    datetime(ZGENERICASSET.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'Add Date (UTC)',
    ZGENERICASSET.ZFILENAME AS 'File Name',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALFILENAME AS 'Original Filename',
    ZGENERICALBUM.ZTITLE AS 'Album Title',
    ZADDITIONALASSETATTRIBUTES.ZCREATORBUNDLEID AS 'Creator Bundle ID',
    ZADDITIONALASSETATTRIBUTES.ZEDITORBUNDLEID AS 'Editor Bundle ID',
    ZGENERICASSET.ZDIRECTORY AS 'Directory',
    CASE ZGENERICASSET.ZSAVEDASSETTYPE
        WHEN 0 THEN 'Saved from other source'
        WHEN 2 THEN 'Photo Streams Data'
        WHEN 3 THEN 'Made/saved with this device'
        WHEN 4 THEN 'Default row'
        WHEN 7 THEN 'Deleted'
        ELSE ZGENERICASSET.ZSAVEDASSETTYPE
    END AS 'Saved Asset Type',
    CASE
        WHEN ZGENERICASSET.ZFACEAREAPOINTS > 0 THEN 'Yes'
        ELSE ZGENERICASSET.ZFACEAREAPOINTS
    END AS 'Face Detected in Photo',
    ZPERSON.ZDISPLAYNAME AS 'Display Name',
    ZPERSON.ZFULLNAME AS 'Full Name',
    ZPERSON.ZFACECOUNT AS 'Face Count',
    ZDETECTEDFACE.ZPERSON AS 'Person',
    ZPERSON.ZCONTACTMATCHINGDICTIONARY AS 'Contact Blob',
    ZPERSON.ZPERSONUUID as 'Person UUID',
    ZDETECTEDFACE.ZQUALITYMEASURE AS 'Detected Face Quality',
    CASE ZDETECTEDFACE.ZAGETYPE
        WHEN 1 THEN 'Baby/Toddler'
        WHEN 2 THEN 'Baby/Toddler'
        WHEN 3 THEN 'Child/Young Adult'
        WHEN 4 THEN 'Young Adult/Adult'
        WHEN 5 THEN 'Adult'
        ELSE ZDETECTEDFACE.ZAGETYPE
    END AS 'Age Type Estimate',
    CASE ZDETECTEDFACE.ZGENDERTYPE
        WHEN 1 THEN 'Male'
        WHEN 2 THEN 'Female'
        ELSE ZDETECTEDFACE.ZGENDERTYPE
    END AS 'Gender',
    CASE ZDETECTEDFACE.ZGLASSESTYPE
        WHEN 3 THEN 'None'
        WHEN 2 THEN 'Sun'
        WHEN 1 THEN 'Eye'
        ELSE ZDETECTEDFACE.ZGLASSESTYPE
    END AS 'Glasses Type',
    CASE ZDETECTEDFACE.ZFACIALHAIRTYPE
        WHEN 1 THEN 'None'
        WHEN 2 THEN 'Beard/Mustache'
        WHEN 3 THEN 'Goatee'
        WHEN 5 THEN 'Stubble'
        ELSE ZDETECTEDFACE.ZFACIALHAIRTYPE
    END AS 'Facial Hair Type',
    CASE ZDETECTEDFACE.ZBALDTYPE
        WHEN 2 THEN 'Bald'
        WHEN 3 THEN 'Not Bald'
        ELSE ZDETECTEDFACE.ZBALDTYPE
    END AS 'Baldness',
    ZGENERICASSET.ZORIGINALCOLORSPACE AS 'Color Space',
    ZGENERICASSET.Zduration AS 'Duration',
    ZGENERICASSET.Zvideocpdurationvalue AS 'Video Duration',
    CASE ZGENERICASSET.ZCOMPLETE
        WHEN 1 THEN 'Yes'
        ELSE ZGENERICASSET.ZCOMPLETE
    END AS 'Complete',
    CASE ZGENERICASSET.ZVISIBILITYSTATE
        WHEN 0 THEN 'Visible'
        WHEN 1 THEN 'Photo Streams Data'
        WHEN 2 THEN 'Burst'
        ELSE ZGENERICASSET.ZVISIBILITYSTATE
    END AS 'VisibilityState',
    CASE ZGENERICASSET.ZFAVORITE
        WHEN 0 THEN 'No'
        WHEN 1 THEN 'Yes'
        ELSE ZGENERICASSET.ZFAVORITE
    END AS 'Favorite',
    CASE ZGENERICASSET.zhidden
        WHEN 0 THEN 'Not Hidden'
        WHEN 1 THEN 'File Hidden'
        ELSE ZGENERICASSET.zhidden
    END AS 'Hidden File',
    CASE ZGENERICASSET.ZTRASHEDSTATE
        WHEN 1 THEN 'In Trash'
        WHEN 0 THEN 'Not In Trash'
        ELSE ZGENERICASSET.ZTRASHEDSTATE
    END AS 'Trash State',
    CASE
        WHEN ZGENERICASSET.ZTRASHEDDATE IS NULL THEN 'n/a'
        ELSE datetime(ZGENERICASSET.ZTRASHEDDATE + 978307200, 'UNIXEPOCH')
    END AS 'File Trash Date (UTC)',
    ZADDITIONALASSETATTRIBUTES.ZVIEWCOUNT AS 'View Count',
    ZADDITIONALASSETATTRIBUTES.ZPLAYCOUNT AS 'Play Count',
    ZADDITIONALASSETATTRIBUTES.ZSHARECOUNT AS 'Share Count',
    datetime(ZGENERICASSET.ZLASTSHAREDDATE + 978307200, 'UNIXEPOCH') AS 'Last Shared Date (UTC)',
    datetime(ZGENERICASSET.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'File Modification Date (UTC)',
    CASE ZGENERICASSET.ZHASADJUSTMENTS
        WHEN 0 THEN 'No'
        WHEN 1 THEN 'Yes'
        ELSE ZGENERICASSET.ZHASADJUSTMENTS
    END AS 'Has Adjustments',
    datetime(ZGENERICASSET.ZADJUSTMENTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'Adjustments Time Stamp (UTC)',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALFILESIZE AS 'Original File Size',
    ZGENERICASSET.ZHEIGHT AS 'File Height',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALHEIGHT AS 'Org File Height',
    ZGENERICASSET.ZWIDTH AS 'File Width',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALWIDTH AS 'Org File Width',
    ZADDITIONALASSETATTRIBUTES.ZCAMERACAPTUREDEVICE AS 'Camera Capture Device',
    CASE ZGENERICASSET.ZORIENTATION
        WHEN 1 THEN 'Horizontal (Left)'
        WHEN 3 THEN 'Horizontal (Right)'
        WHEN 6 THEN 'Vertical (Up)'
        WHEN 8 THEN 'Vertical (Down)'
        ELSE ZGENERICASSET.ZORIENTATION
    END AS 'Orientation',
    CASE ZADDITIONALASSETATTRIBUTES.ZORIGINALORIENTATION 
        WHEN 1 THEN 'Horizontal (Left)'
        WHEN 3 THEN 'Horizontal (Right)'
        WHEN 6 THEN 'Vertical (Up)'
        WHEN 8 THEN 'Vertical (Down)'
        ELSE ZGENERICASSET.ZORIENTATION
    END AS 'Org Orientation',
    ZADDITIONALASSETATTRIBUTES.ZTIMEZONENAME AS 'Time Zone Name',
    ZADDITIONALASSETATTRIBUTES.ZTIMEZONEOFFSET AS 'Time Zone Offset',
    ZADDITIONALASSETATTRIBUTES.ZINFERREDTIMEZONEOFFSET AS 'Inferred Time Zone Offset',
    ZGENERICASSET.ZLOCATIONDATA AS 'File Location Data',
    CASE ZGENERICASSET.ZLATITUDE
        WHEN -180.0 THEN 'n/a'
        ELSE ZGENERICASSET.ZLATITUDE
    END 'LATITUDE',
    CASE ZGENERICASSET.ZLONGITUDE
        WHEN -180.0 THEN 'n/a'
        ELSE ZGENERICASSET.ZLONGITUDE
    END 'LONGITUDE',
    CASE ZADDITIONALASSETATTRIBUTES.ZSHIFTEDLOCATIONISVALID
        WHEN 0 THEN 'No'
        WHEN 1 THEN 'Yes'
        ELSE ZADDITIONALASSETATTRIBUTES.ZSHIFTEDLOCATIONISVALID
    END AS 'Shifted Location Valid',
    CASE ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATAISVALID
        WHEN 0 THEN 'No Check Scene Analysis'
        WHEN 1 THEN 'Yes Check Scene Analysis'
        ELSE ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATAISVALID
    END AS 'Reverse Location Data Is Valid',
    ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATA AS 'Org File Reverse Location Data',
    ZGENERICASSET.Zthumbnailindex AS 'Thumbnail Index',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILWIDTH AS 'Embedded Thumbnail Width',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILHEIGHT AS 'Embedded Thumbnail Height',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILOFFSET AS 'Embedded Thumbnail Offset',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILLENGTH AS 'Embedded Thumbnail Length',
    ZGENERICASSET.ZMOMENT AS 'Moment PK',
    ZMOMENT.ZTITLE AS 'Moment Title',
    datetime(ZMOMENT.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'Moment Start Date (UTC)',
    datetime(ZMOMENT.Zrepresentativedate + 978307200, 'UNIXEPOCH') AS 'Moment Representative Date (UTC)',
    datetime(ZMOMENT.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'Moment Modification Date (UTC)',
    datetime(ZMOMENT.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'Moment End Date (UTC)',
    CASE ZMOMENT.ZTRASHEDSTATE
        WHEN 1 THEN 'In Trash'
        WHEN 0 THEN 'Not In Trash'
        ELSE ZMOMENT.ZTRASHEDSTATE
    END AS 'Moment Trash State',
    CASE ZMOMENT.Zapproximatelatitude
        WHEN -180.0 THEN 'n/a'
        ELSE ZMOMENT.Zapproximatelatitude
    END AS 'Moment Approx. Latitude',
    CASE ZMOMENT.Zapproximatelongitude 
        WHEN -180.0 THEN 'n/a'
        ELSE ZMOMENT.Zapproximatelongitude 
    END AS 'Moment Approx. Longitude',
    ZGENERICASSET.ZUUID AS 'UUID',
    ZGENERICASSET.ZMEDIAGROUPUUID AS 'Media Group UUID',
    ZGENERICASSET.ZCLOUDASSETGUID AS 'Cloud Asset GUID',
    ZADDITIONALASSETATTRIBUTES.ZPUBLICGLOBALUUID AS 'Public Global UUID',
    ZADDITIONALASSETATTRIBUTES.ZMASTERFINGERPRINT AS 'Master Fingerprint',
    ZADDITIONALASSETATTRIBUTES.ZADJUSTEDFINGERPRINT AS 'Adjusted Fingerprint'

FROM ZGENERICASSET
    LEFT JOIN
        ZMOMENT ON ZGENERICASSET.ZMOMENT = ZMOMENT.Z_PK
    JOIN
        ZADDITIONALASSETATTRIBUTES ON ZGENERICASSET.ZADDITIONALATTRIBUTES = ZADDITIONALASSETATTRIBUTES.Z_PK
    LEFT JOIN
        ZDETECTEDFACE ON ZADDITIONALASSETATTRIBUTES.ZASSET = ZDETECTEDFACE.ZASSET
    LEFT JOIN
        ZPERSON ON ZPERSON.Z_PK = ZDETECTEDFACE.ZPERSON
    LEFT JOIN
        Z_26ASSETS ON ZGENERICASSET.Z_PK = Z_26ASSETS.Z_34ASSETS
    LEFT JOIN
        ZGENERICALBUM ON ZGENERICALBUM.Z_PK = Z_26ASSETS.Z_26ALBUMS

ORDER BY ZGENERICASSET.Z_PK ASC
