SELECT
    ROW_NUMBER() OVER() AS 'Record No.',
    ZPROCESS.Z_PK AS 'ZPROCESS Z_PK'
    datetime(ZPROCESS.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'Timestamp (UTC)',
    datetime(ZPROCESS.ZTIMESTAMP + 978307200, 'UNIXEPOCH', 'localtime') AS 'Timestamp (Local)',
    datetime(ZPROCESS.ZFIRSTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'Process First Timestamp (UTC)',
    datetime(ZPROCESS.ZFIRSTTIMESTAMP + 978307200, 'UNIXEPOCH', 'localtime') AS 'Process First Timestamp (Local)',
    ZPROCESS.ZPROCNAME AS 'Process Name',
    ZPROCESS.ZBUNDLENAME AS 'Bundle ID',

FROM ZPROCESS

WHERE 'BUNDLE ID' LIKE '%whisper%'

ORDER BY ZPROCESS.ZTIMESTAMP ASC
