/*
File located at: \private\var\networkd\db\netusage.sqlite
*/

SELECT
    ROW_NUMBER() OVER() AS 'Row #',
    datetime(ZPROCESS.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'PROCESS TIMESTAMP',
    datetime(ZLIVEUSAGE.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'LIVE USAGE TIMESTAMP',
    ZPROCESS.ZBUNDLENAME AS 'Bundle ID',
    ZPROCESS.ZPROCNAME AS 'Process Name',
    ZLIVEUSAGE.ZWIFIIN AS 'WIFI IN',
    ZLIVEUSAGE.ZWIFIOUT AS 'WIFI OUT',
    ZLIVEUSAGE.ZWWANIN AS 'WWAN IN',
    ZLIVEUSAGE.ZWWANOUT AS 'WWAN OUT',
    ZLIVEUSAGE.ZWIREDIN AS 'WIRED IN',
    ZLIVEUSAGE.ZWIREDOUT AS 'WIRED OUT',
    ZLIVEUSAGE.ZXIN AS 'X IN',
    ZLIVEUSAGE.ZXOUT AS 'X OUT',
    'File: \private\var\networkd\db\netusage.sqlite; Table: ZLIVEUSAGE(Z_PK: ' || ZLIVEUSAGE.Z_PK || ')' AS 'Data Source'

FROM ZLIVEUSAGE
    LEFT JOIN ZPROCESS ON ZPROCESS.Z_PK = ZLIVEUSAGE.ZHASPROCESS

-- WHERE 'BUNDLE ID' LIKE '%whatsapp%'

ORDER BY ZLIVEUSAGE.Z_PK ASC
