/*
[Module Metadata]
AUTHOR=[@mikespon]
MODULE_NOTES=Signification Locations

[Database Metadata]
DATABASE=Cloud-V2.sqlite
DATABASEPATH=/private/var/root/Library/Caches/locationd/
PLATFORM=iOS
VERSION=iOS 16.6 (20G75)
*/

SELECT
    ROW_NUMBER() OVER() AS 'Record No.',
    ZRTADDRESSMO.Z_PK AS 'ZRTADDRESSMO.Z_PK',
    ZRTADDRESSMO.ZMAPITEM AS 'ZRTADDRESSMO.ZMAPITEM',
    ZRTMAPITEMMO.Z_PK AS 'ZRTMAPITEMMO.Z_PK',
    ZRTMAPITEMMO.ZADDRESS AS 'ZRTMAPITEMMO.ZADDRESS',
    strftime('%Y-%m-%dT%H:%M:%SZ', datetime(ZRTADDRESSMO.ZCREATIONDATE + 978307200, 'UNIXEPOCH')) AS 'Address Creation Date (UTC)',
    strftime('%Y-%m-%dT%H:%M:%SZ', datetime(ZRTADDRESSMO.ZCREATIONDATE + 978307200, 'UNIXEPOCH', 'localtime')) AS 'Address Creation Date (Local)',
    strftime('%Y-%m-%dT%H:%M:%SZ', datetime(ZRTADDRESSMO.ZEXPIRATIONDATE + 978307200, 'UNIXEPOCH')) AS 'Address Expire Date (UTC)',
    strftime('%Y-%m-%dT%H:%M:%SZ', datetime(ZRTADDRESSMO.ZEXPIRATIONDATE + 978307200, 'UNIXEPOCH', 'localtime')) AS 'Address Expire Date (Local)',
    ZRTADDRESSMO.ZSUBTHOROUGHFARE || ' ' || ZRTADDRESSMO.ZTHOROUGHFARE || ', ' || ZRTADDRESSMO.ZLOCALITY || ', ' || ZRTADDRESSMO.ZADMINISTRATIVEAREA || ' ' || ZRTADDRESSMO.ZPOSTALCODE || ' ' || ZRTADDRESSMO.ZCOUNTRYCODE AS 'Address',
    ZRTMAPITEMMO.ZLATITUDE AS 'ZRTMAPITEMMO.ZLATITUDE',
    ZRTMAPITEMMO.ZLONGITUDE AS 'ZRTMAPITEMMO.ZLONGITUDE',
    ZRTMAPITEMMO.ZUNCERTAINTY AS 'ZRTMAPITEMMO.ZUNCERTAINTY'

FROM ZRTADDRESSMO
    LEFT JOIN ZRTMAPITEMMO ON ZRTADDRESSMO.ZMAPITEM = ZRTMAPITEMMO.ZADDRESS

ORDER BY ZRTADDRESSMO.ZCREATIONDATE DESC