SELECT
    ROW_NUMBER() OVER() AS 'Row #',
    ZPROCESS.Z_PK AS 'ZPROCESS TABLE ID'
    datetime(ZPROCESS.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'TIMESTAMP',
    datetime(ZPROCESS.ZFIRSTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'PROCESS FIRST TIMESTAMP',
    ZPROCESS.ZPROCNAME AS 'PROCESS NAME',
    ZPROCESS.ZBUNDLENAME AS 'BUNDLE ID',

FROM ZPROCESS

WHERE 'BUNDLE ID' LIKE '%whisper%'

ORDER BY ZPROCESS.ZTIMESTAMP ASC
