/*
File Path = \private\var\mobile\Library\Application Support\com.apple.remotemanagementd
File Names = RMAdminStore-Local.sqlite & RMAdminStore-Cloud.sqlite
*/

SELECT
    ROW_NUMBER() OVER() AS 'Record',
    datetime(ZUSAGEBLOCK.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'Start Date (UTC)',
    datetime(ZUSAGEBLOCK.ZLASTEVENTDATE + 978307200, 'UNIXEPOCH') AS 'End Date (UTC)',
    ZUSAGETIMEDITEM.ZTOTALTIMEINSECONDS AS 'App Usage Time (seconds)',
    ZUSAGETIMEDITEM.ZTOTALTIMEINSECONDS / 60.00 AS 'App Usage Time (minutes)',
    ZUSAGETIMEDITEM.ZBUNDLEIDENTIFIER AS 'Bundle ID',
    CASE ZUSAGECATEGORY.ZIDENTIFIER
        WHEN 'DH0011' THEN 'Unspecified1'
        WHEN 'DH0012' THEN 'Unspecified2'
        WHEN 'DH0013' THEN 'Unspecified3'
        WHEN 'DH1001' THEN 'Games'
        WHEN 'DH1002' THEN 'Social Networking'
        WHEN 'DH1003' THEN 'Entertainment'
        WHEN 'DH1004' THEN 'Creativity'
        WHEN 'DH1005' THEN 'Productivity'
        WHEN 'DH1006' THEN 'Education'
        WHEN 'DH1007' THEN 'Reading & Reference'
        WHEN 'DH1008' THEN 'Health & Fitness'
        WHEN 'DH1009' THEN 'Other'
        ELSE ZUSAGECATEGORY.ZIDENTIFIER
    END AS 'CATEGORY ID',
    ZUSAGECOUNTEDITEM.ZNUMBEROFNOTIFICATIONS AS 'Notifications',
    ZUSAGECOUNTEDITEM.ZNUMBEROFPICKUPS AS 'Pickups',
    ZUSAGEBLOCK.ZNUMBEROFPICKUPSWITHOUTAPPLICATIONUSAGE AS 'Pickups (No App Usage)',
    ZCOREDEVICE.ZNAME AS 'Device Name',
    ZCOREDEVICE.ZIDENTIFIER AS 'Device ID',
    CASE ZCOREDEVICE.ZPLATFORM
        WHEN 0 THEN 'Unknown'
        WHEN 1 THEN 'macOS'
        WHEN 2 THEN 'iOS'
        WHEN 4 THEN 'Apple Watch'
        ELSE ZCOREDEVICE.ZPLATFORM
    END AS 'Platform',
    ZCOREUSER.ZAPPLEID AS 'Apple ID',
    ZCOREUSER.ZDSID AS 'DSID',
    ZCOREUSER.ZALTDSID AS 'ALT DSID',
    ZCOREUSER.ZGIVENNAME || ' ' || ZCOREUSER.ZFAMILYNAME AS 'Full Name',
    ZCOREUSER.ZFAMILYMEMBERTYPE AS 'Family Type',
    'Table: ZUSAGEGETIMEDITEM (Z_PK: ' || ZUSAGETIMEDITEM.Z_PK || ')' AS 'Data Source'

FROM ZUSAGETIMEDITEM
    LEFT JOIN ZUSAGECATEGORY ON ZUSAGECATEGORY.Z_PK = ZUSAGETIMEDITEM.ZCATEGORY
    LEFT JOIN ZUSAGEBLOCK ON ZUSAGEBLOCK.Z_PK = ZUSAGECATEGORY.ZBLOCK
    LEFT JOIN ZUSAGE ON ZUSAGE.Z_PK = ZUSAGEBLOCK.ZUSAGE
    LEFT JOIN ZCOREDEVICE ON ZCOREDEVICE.Z_PK = ZUSAGE.ZDEVICE
    LEFT JOIN ZCOREUSER ON ZCOREUSER.Z_PK = ZUSAGE.ZUSER
    LEFT JOIN ZUSAGECOUNTEDITEM ON ZUSAGECOUNTEDITEM.ZBLOCK = ZUSAGECATEGORY.ZBLOCK AND ZUSAGECOUNTEDITEM.ZBUNDLEIDENTIFIER = ZUSAGETIMEDITEM.ZBUNDLEIDENTIFIER

WHERE ZUSAGETIMEDITEM.ZBUNDLEIDENTIFIER LIKE '%whatsapp%'

ORDER BY ZUSAGEBLOCK.ZSTARTDATE ASC


--ZUC.ZTOTALTIMEINSECONDS AS 'Total_Time (from ZUC)',
--ZUSAGEBLOCK.ZSCREENTIMEINSECONDS AS 'Screen_Time (from ZUSAGEBLOCK)',
