SELECT
    ROW_NUMBER() OVER() AS 'Row #',
    ZGENERICALBUM.Z_PK AS 'Index #',
    ZGENERICALBUM.ZTITLE AS 'Album Title',
    ZGENERICASSET.ZDIRECTORY AS 'Directory',
    ZGENERICASSET.ZFILENAME AS 'File Name',
    ZGENERICASSET.ZUNIFORMTYPEIDENTIFIER AS 'File Type',
    CASE ZGENERICASSET.ZFAVORITE
        WHEN '0' THEN 'No'
        WHEN '1' THEN 'Yes'
        ELSE ZGENERICASSET.ZFAVORITE
    END 'Favorite',
    ZGENERICASSET.ZDURATION AS 'Duration (seconds)',
    CASE
        WHEN LENGTH(ZGENERICASSET.ZDATECREATED) = 18
            THEN datetime((ZGENERICASSET.ZDATECREATED / 1000000000) + 978307200, 'UNIXEPOCH')
        WHEN LENGTH(ZGENERICASSET.ZDATECREATED) = 9
            THEN datetime(ZGENERICASSET.ZDATECREATED + 978307200, 'UNIXEPOCH')
        ELSE ZGENERICASSET.ZDATECREATED
    END AS 'Date Created (UTC)',
    CASE
        WHEN LENGTH(ZGENERICASSET.ZADDEDDATE) = 18
            THEN datetime((ZGENERICASSET.ZADDEDDATE / 1000000000) + 978307200, 'UNIXEPOCH')
        WHEN LENGTH(ZGENERICASSET.ZADDEDDATE) = 9
            THEN datetime(ZGENERICASSET.ZADDEDDATE + 978307200, 'UNIXEPOCH')
        ELSE ZGENERICASSET.ZADDEDDATE
    END AS 'Date Added (UTC)',
    CASE
        WHEN LENGTH(ZGENERICASSET.ZMODIFICATIONDATE) = 18
            THEN datetime((ZGENERICASSET.ZMODIFICATIONDATE / 1000000000) + 978307200, 'UNIXEPOCH')
        WHEN LENGTH(ZGENERICASSET.ZMODIFICATIONDATE) = 9
            THEN datetime(ZGENERICASSET.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH')
        ELSE ZGENERICASSET.ZMODIFICATIONDATE
    END AS 'Modification Date (UTC)',
    CASE
        WHEN LENGTH(ZGENERICASSET.ZTRASHEDDATE) = 18
            THEN datetime((ZGENERICASSET.ZTRASHEDDATE / 1000000000) + 978307200, 'UNIXEPOCH')
        WHEN LENGTH(ZGENERICASSET.ZTRASHEDDATE) = 9
            THEN datetime(ZGENERICASSET.ZTRASHEDDATE + 978307200, 'UNIXEPOCH')
        ELSE ZGENERICASSET.ZTRASHEDDATE
    END AS 'Trashed Date (UTC)',
    ZGENERICASSET.ZTHUMBNAILINDEX AS 'Thumbnail Index',
    CASE ZGENERICASSET.ZLATITUDE
        WHEN '-180.0' THEN 'n/a'
        ELSE ZGENERICASSET.ZLATITUDE
    END 'LATITUDE',
    CASE ZGENERICASSET.ZLONGITUDE
        WHEN '-180.0' THEN 'n/a'
        ELSE ZGENERICASSET.ZLONGITUDE
    END 'LONGITUDE'

FROM ZGENERICASSET
    INNER JOIN
        (ZGENERICALBUM INNER JOIN Z_26ASSETS ON ZGENERICALBUM.Z_PK = Z_26ASSETS.Z_26ALBUMS) ON ZGENERICASSET.Z_PK = Z_26ASSETS.Z_34ASSETS

ORDER BY ZGENERICALBUM.Z_PK
