SELECT
    ROW_NUMBER() OVER() AS 'Row #',
    ZOBJECT.Z_PK AS 'Table ID',
    CASE ZOBJECT.ZSTARTDAYOFWEEK
        WHEN '1' THEN 'Sunday'
        WHEN '2' THEN 'Monday'
        WHEN '3' THEN 'Tuesday'
        WHEN '4' THEN 'Wednesday'
        WHEN '5' THEN 'Thursday'
        WHEN '6' THEN 'Friday'
        WHEN '7' THEN 'Saturday'
        ELSE ZOBJECT.ZSTARTDAYOFWEEK
    END AS 'Day of Week',
    datetime(ZOBJECT.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'Start Time (UTC)',
    datetime(ZOBJECT.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'End Time (UTC)',
    (ZOBJECT.ZSECONDSFROMGMT / 3600) AS 'Device GMT Offset',
    (ZOBJECT.ZENDDATE - ZOBJECT.ZSTARTDATE) AS 'Usage (Seconds)',
    (ZOBJECT.ZENDDATE - ZOBJECT.ZSTARTDATE) / 60.00 AS 'Usage (Minutes)',
    ZOBJECT.ZSTREAMNAME AS 'Stream Name',
    --ZOBJECT.ZVALUESTRING AS 'Value String',
    ZSTRUCTUREDMETADATA.Z_DKAUDIOMETADATAKEY__IDENTIFIER AS 'Audio Identifier',
    ZSTRUCTUREDMETADATA.Z_DKAUDIOMETADATAKEY__PORTNAME AS 'Audio Port Name',
    ZSTRUCTUREDMETADATA.Z_DKAUDIOMETADATAKEY__PORTTYPE AS 'Audio Port Type',
    ZSTRUCTUREDMETADATA.Z_DKBLUETOOTHMETADATAKEY__ADDRESS AS 'Bluetooth Address',
    ZSTRUCTUREDMETADATA.Z_DKBLUETOOTHMETADATAKEY__NAME AS 'Bluetooth Name',
    ZSTRUCTUREDMETADATA.Z_DKNOWPLAYINGMETADATAKEY__ARTIST AS 'Now Playing Artist',
    ZSTRUCTUREDMETADATA.Z_DKNOWPLAYINGMETADATAKEY__TITLE AS 'Now Playing Title',
    ZSTRUCTUREDMETADATA.Z_DKNOWPLAYINGMETADATAKEY__ALBUM AS 'Now Playing Album',
    ZSTRUCTUREDMETADATA.Z_DKNOWPLAYINGMETADATAKEY__GENRE AS 'Now Playing Genre',
    ZSTRUCTUREDMETADATA.Z_DKNOWPLAYINGMETADATAKEY__DURATION AS 'Now Playing Duration (Seconds)',
    datetime(ZOBJECT.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'Entry Creation Date (UTC)'

FROM ZOBJECT
    LEFT JOIN
        ZSTRUCTUREDMETADATA ON ZOBJECT.ZSTRUCTUREDMETADATA = ZSTRUCTUREDMETADATA.Z_PK
    LEFT JOIN
        ZSOURCE ON ZOBJECT.ZSOURCE = ZSOURCE.Z_PK

WHERE
    ZSTREAMNAME LIKE '/audio%' OR
    ZSTREAMNAME LIKE '/bluetooth%' OR
    ZSTREAMNAME LIKE '/media%'

ORDER BY ZOBJECT.ZSTARTDATE DESC
