/* [Module Metadata]
AUTHOR=Sarah Edwards/mac4n6.com/@iamevltwin
MODULE_NOTES=Call History

[Database Metadata]
DATABASE=CallHistory.storedata
PLATFORM=IOS,MACOS
VERSIONS=8,9,10,11,12,13,10.13,10.14,10.15

[Query Metadata]
QUERY_NAME=call_history
ACTIVITY=Call History
KEY_TIMESTAMP=TIMESTAMP
*/

-- [SQL Query iOS 10.13, 10.14, 10.15]
SELECT
    ZCALLRECORD.Z_PK AS 'Table ID',
    DATETIME (ZCALLRECORD.ZDATE + 978307200, 'UNIXEPOCH') AS 'Call Start Time (UTC)',
    DATETIME ((ZCALLRECORD.ZDATE + 978307200) + ZCALLRECORD.ZDURATION, 'UNIXEPOCH') AS 'Call End Time (UTC)',
    ZCALLRECORD.ZDURATION AS 'Duration (Seconds)',
    CASE ZCALLRECORD.ZANSWERED
        WHEN 0 THEN 'NOT Answered'
        WHEN 1 THEN 'Answered'
        ELSE 'Contact Examiner for Further'
    END AS 'Answered Status',
    ZCALLRECORD.ZADDRESS AS 'Contact Number',
    ZCALLRECORD.ZDISCONNECTED_CAUSE AS 'Disconnected Cause',
    ZCALLRECORD.ZCALLTYPE AS 'Call Type',
    CASE ZCALLRECORD.ZORIGINATED
        WHEN 0 THEN 'Incoming Call'
        WHEN 1 THEN 'Outgoing Call'
        ELSE 'Contact Examiner for Further'
    END AS 'Call Direction',
    ZCALLRECORD.ZISO_COUNTRY_CODE AS 'Country Code',
    ZCALLRECORD.ZLOCATION AS 'Location',
    CASE ZCALLRECORD.ZSERVICE_PROVIDER
        WHEN 'com.apple.Telephony' THEN 'Phone App'
        WHEN 'com.apple.FaceTime' THEN 'FaceTime Call'
        ELSE 'Contact Examiner for Further'
    END AS 'Service Provider'
FROM ZCALLRECORD
ORDER BY ZCALLRECORD.Z_PK DESC


-- [SQL Query iOS 9, 10, 11, 12, 13]
SELECT
    DATETIME ( ZDATE + 978307200, 'UNIXEPOCH' ) AS 'TIMESTAMP',
    ZADDRESS AS 'ADDRESS',
    ZANSWERED AS 'WAS ANSWERED',
    ZCALLTYPE AS 'CALL TYPE',
    ZORIGINATED AS 'ORIGINATED',
    ZDURATION/60.00 AS 'DURATION (IN MINUTES)',
    ZDURATION AS 'DURATION (IN SECONDS)',
    ZISO_COUNTRY_CODE AS 'ISO COUNTRY CODE',
    ZLOCATION AS 'LOCATION',
    ZSERVICE_PROVIDER AS 'SERVICE PROVIDER',
    ZCALLRECORD.Z_PK AS 'ZCALLRECORD TABLE ID'
FROM ZCALLRECORD


-- [SQL Query iOS 8]
SELECT
    DATETIME ( ZDATE+978307200,'UNIXEPOCH' ) AS 'TIMESTAMP',
    ZADDRESS AS 'ADDRESS',
    ZANSWERED AS 'WAS ANSWERED',
    ZCALLTYPE AS 'CALL TYPE',
    ZORIGINATED AS 'ORIGINATED',
    ZDURATION/60.00 AS 'DURATION (IN MINUTES)',
    ZDURATION AS 'DURATION (IN SECONDS)',
    ZISO_COUNTRY_CODE AS 'ISO COUNTRY CODE',
    ZCALLRECORD.Z_PK AS 'ZCALLRECORD TABLE ID'
FROM ZCALLRECORD
