/*
File located at: \private\var\wireless\Library\Databases\DataUsage.sqlite
                 \private\var\wireless\Library\Databases\CellularUsage.db
*/

SELECT
    ROW_NUMBER() OVER() AS 'Record #',
    datetime(ZLIVEUSAGE.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'TIMESTAMP',
    datetime(ZPROCESS.ZFIRSTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'PROCESS FIRST TIMESTAMP',
    datetime(ZPROCESS.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'PROCESS TIMESTAMP',
    ZPROCESS.ZPROCNAME AS 'PROCESS NAME',
    ZPROCESS.ZBUNDLENAME AS 'BUNDLE ID',
    Z_PRIMARYKEY.Z_NAME as 'Type',
    ZLIVEUSAGE.ZWIFIIN AS 'WIFI IN',
    ZLIVEUSAGE.ZWIFIOUT AS 'WIFI OUT',
    ZLIVEUSAGE.ZWWANIN AS 'WWAN IN',
    ZLIVEUSAGE.ZWWANOUT AS 'WWAN OUT',
    'File: \private\var\wireless\Library\Databases\DataUsage.sqlite; Table: ZLIVEUSAGE(Z_PK: ' || ZLIVEUSAGE.Z_PK || '), ' || 'Table: ZPROCESS(Z_PK: ' || ZPROCESS.Z_PK || ')' AS 'Data Source'

FROM ZLIVEUSAGE
    LEFT JOIN ZPROCESS ON ZLIVEUSAGE.ZHASPROCESS = ZPROCESS.Z_PK
    LEFT JOIN Z_PRIMARYKEY ON ZPROCESS.Z_ENT = Z_PRIMARYKEY.Z_ENT

-- WHERE 'PROCESS NAME' LIKE '%whisper%'

ORDER BY 'TIMESTAMP' ASC
