SELECT
    ROW_NUMBER() OVER() AS 'RecordNo.',
    datetime(ZLIVEROUTEPERF.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'LiveRoutePrefTimestamp(UTC)',
    datetime(ZLIVEROUTEPERF.ZTIMESTAMP + 978307200, 'UNIXEPOCH', 'localtime') AS 'LiveRoutePrefTimestamp(Local)',
    datetime(ZNETWORKATTACHMENT.ZFIRSTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'FirstNetworkAttachment(UTC)',
    datetime(ZNETWORKATTACHMENT.ZFIRSTTIMESTAMP + 978307200, 'UNIXEPOCH', 'localtime') AS 'FirstNetworkAttachment(Local)',
    datetime(ZNETWORKATTACHMENT.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'NetworkAttachmentTimestamp(UTC)',
    datetime(ZNETWORKATTACHMENT.ZTIMESTAMP + 978307200, 'UNIXEPOCH', 'localtime') AS 'NetworkAttachmentTimestamp(Local)',
    CASE ZLIVEROUTEPERF.ZKIND
        WHEN 1 THEN 'WI-FI'
        WHEN 2 THEN 'CELLULAR'
        ELSE ZLIVEROUTEPERF.ZKIND
    END 'NetworkType',
    ZLIVEROUTEPERF.ZBYTESIN AS 'BytesIn',
    ZLIVEROUTEPERF.ZBYTESOUT AS 'BytesOut',
    ZLIVEROUTEPERF.ZPACKETSIN AS 'PacketsIn',
    ZLIVEROUTEPERF.ZPACKETSOUT AS 'PacketsOut',
    ZLIVEROUTEPERF.ZCONNATTEMPTS AS 'ConnectionAttempts',
    ZLIVEROUTEPERF.ZCONNSUCCESSES AS 'ConnectionSuccesses',
    ZNETWORKATTACHMENT.ZIDENTIFIER AS 'NetworkIdentifier',
    ZNETWORKATTACHMENT.ZISKNOWNGOOD AS 'IsKnownGood',
    HEX(ZNETWORKATTACHMENT.ZNETSIGNATURE) AS 'NetSignature(HEX)',
    ZNETWORKATTACHMENT.ZOVERALLSTAYMEAN AS 'OverallStayMean(NetworkAttachment)',
    ZNETWORKATTACHMENT.ZOVERALLSTAYVAR AS 'OverallStayVar(NetworkAttachment)',
    ZLIVEROUTEPERF.ZOVERALLSTAY AS 'OverallStayMean(LiveRoutePerf)',
    ZLIVEROUTEPERF.ZOVERALLSTAYM2 AS 'OverallStayM2(LiveRoutePerf)',
    'Table: ZZLIVEROUTEPERF(Z_PK:' || ZLIVEROUTEPERF.Z_PK || ')' AS 'DataSource'

FROM ZLIVEROUTEPERF
    LEFT JOIN ZNETWORKATTACHMENT ON ZLIVEROUTEPERF.ZHASNETWORKATTACHMENT = ZNETWORKATTACHMENT.Z_PK

ORDER BY 'Live Route Pref Timestamp' ASC
