/*
  DLU = 2024-10-15
*/

SELECT

    ROW_NUMBER() OVER () AS 'RowNo.',
    ZASSET.Z_PK AS 'IndexNo.',
    ZGENERICALBUM.ZTITLE AS 'AlbumTitle',
    ZASSET.ZDIRECTORY AS 'Directory',
    ZASSET.ZFILENAME AS 'FileName',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALFILENAME AS 'Original Filename',
    ZASSET.ZUNIFORMTYPEIDENTIFIER AS 'MIMEType',
    ZADDITIONALASSETATTRIBUTES.ZIMPORTEDBYBUNDLEIDENTIFIER AS 'ImportedByBundleID',

    CASE ZASSET.ZFAVORITE
        WHEN 0 THEN 'No'
        WHEN 1 THEN 'Yes'
        ELSE ZASSET.ZFAVORITE
    END AS 'Favorite',

    CASE ZASSET.ZHIDDEN
        WHEN 0 THEN 'NotHidden'
        WHEN 1 THEN 'Hidden'
        ELSE ZASSET.ZHIDDEN
    END AS 'IsFileHidden',

    datetime(ZASSET.ZDATECREATED + 978307200, 'UNIXEPOCH') AS 'DateCreated(UTC)',
    datetime(ZASSET.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'ModificationDate(UTC)',
    datetime(ZASSET.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'DateAdded(UTC)',

    CASE ZASSET.ZTRASHEDSTATE
        WHEN 1 THEN 'InTrash'
        WHEN 0 THEN 'NotInTrash'
        ELSE ZASSET.ZTRASHEDSTATE
    END AS 'Trash State',

    CASE
        WHEN ZASSET.ZTRASHEDDATE IS NULL THEN 'n/a'
        ELSE datetime(ZASSET.ZTRASHEDDATE + 978307200, 'UNIXEPOCH')
    END AS 'FileTrashDate(UTC)',


    CASE ZASSET.ZLATITUDE
        WHEN -180.0 THEN 'n/a'
        ELSE ZASSET.ZLATITUDE
    END 'LATITUDE',

    CASE ZASSET.ZLONGITUDE
        WHEN -180.0 THEN 'n/a'
        ELSE ZASSET.ZLONGITUDE
    END 'LONGITUDE'

FROM ZASSET

    JOIN ZADDITIONALASSETATTRIBUTES ON ZASSET.ZADDITIONALATTRIBUTES = ZADDITIONALASSETATTRIBUTES.Z_PK
    LEFT JOIN Z_29ASSETS ON ZASSET.Z_PK = Z_29ASSETS.Z_3ASSETS
    LEFT JOIN ZGENERICALBUM ON ZGENERICALBUM.Z_PK = Z_29ASSETS.Z_29ALBUMS

--WHERE ZASSET.ZHIDDEN IS "1"

ORDER BY ZGENERICALBUM.Z_PK