SELECT
    /* Add a row number at the beggining of each row */
    ROW_NUMBER() OVER() AS 'RecordNo.',
    ZGENERICASSET.Z_PK AS 'ZGENERICASSET.Z_PK',
    ZGENERICASSET.ZADDITIONALATTRIBUTES AS 'AddAttributesKey',
    ZDETECTEDFACE.ZASSET AS 'DetectedFaceAsset',
    CASE ZGENERICASSET.ZKIND
        WHEN 0 THEN 'Photo'
        WHEN 1 THEN 'Video'
        ELSE ZGENERICASSET.ZKIND
    END AS 'FileType',
    ZGENERICASSET.ZUNIFORMTYPEIDENTIFIER AS 'MIMEType',
    CASE
        WHEN LENGTH(ZGENERICASSET.ZDATECREATED) = 18 THEN
            datetime((ZGENERICASSET.ZDATECREATED / 1000000000) + 978307200, 'UNIXEPOCH')
        WHEN LENGTH(ZGENERICASSET.ZDATECREATED) = 9 THEN
            datetime(ZGENERICASSET.ZDATECREATED + 978307200, 'UNIXEPOCH')
        ELSE ZGENERICASSET.ZDATECREATED
    END AS 'DateCreated(UTC)',
    ZADDITIONALASSETATTRIBUTES.ZEXIFTIMESTAMPSTRING AS 'EXIFTimeStamp(UTC)',
    datetime(ZADDITIONALASSETATTRIBUTES.ZSCENEANALYSISTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'SceneAnalysisTimeStamp(UTC)',
    datetime(ZGENERICASSET.ZANALYSISSTATEMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'AnalysisStateModificationDate(UTC)',
    datetime(ZGENERICASSET.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'AddedDate(UTC)',
    ZGENERICASSET.ZFILENAME AS 'FileName',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALFILENAME AS 'OriginalFilename',
    ZGENERICALBUM.ZTITLE AS 'AlbumTitle',
    ZADDITIONALASSETATTRIBUTES.ZCREATORBUNDLEID AS 'CreatorBundleID',
    ZADDITIONALASSETATTRIBUTES.ZEDITORBUNDLEID AS 'EditorBundleID',
    ZGENERICASSET.ZDIRECTORY AS 'Directory',
    CASE ZGENERICASSET.ZSAVEDASSETTYPE
        WHEN 0 THEN 'SavedFromOtherSource'
        WHEN 2 THEN 'PhotoStreamsData'
        WHEN 3 THEN 'Made/SavedWithThisDevice'
        WHEN 4 THEN 'DefaultRow'
        WHEN 7 THEN 'Deleted'
        ELSE ZGENERICASSET.ZSAVEDASSETTYPE
    END AS 'SavedAssetType',
    CASE
        WHEN ZGENERICASSET.ZFACEAREAPOINTS > 0 THEN 'Yes'
        ELSE ZGENERICASSET.ZFACEAREAPOINTS
    END AS 'FaceDetectedInPhoto',
    ZPERSON.ZDISPLAYNAME AS 'DisplayName',
    ZPERSON.ZFULLNAME AS 'FullName',
    ZPERSON.ZFACECOUNT AS 'FaceCount',
    ZDETECTEDFACE.ZPERSON AS 'Person',
    ZPERSON.ZCONTACTMATCHINGDICTIONARY AS 'ContactBlob',
    ZPERSON.ZPERSONUUID as 'PersonUUID',
    ZDETECTEDFACE.ZQUALITYMEASURE AS 'DetectedFaceQuality',
    CASE ZDETECTEDFACE.ZAGETYPE
        WHEN 1 THEN 'Baby/Toddler'
        WHEN 2 THEN 'Baby/Toddler'
        WHEN 3 THEN 'Child/Young Adult'
        WHEN 4 THEN 'YoungAdult/Adult'
        WHEN 5 THEN 'Adult'
        ELSE ZDETECTEDFACE.ZAGETYPE
    END AS 'AgeTypeEstimate',
    CASE ZDETECTEDFACE.ZGENDERTYPE
        WHEN 1 THEN 'Male'
        WHEN 2 THEN 'Female'
        ELSE ZDETECTEDFACE.ZGENDERTYPE
    END AS 'Gender',
    CASE ZDETECTEDFACE.ZGLASSESTYPE
        WHEN 3 THEN 'None'
        WHEN 2 THEN 'Sun'
        WHEN 1 THEN 'Eye'
        ELSE ZDETECTEDFACE.ZGLASSESTYPE
    END AS 'Glasses Type',
    CASE ZDETECTEDFACE.ZFACIALHAIRTYPE
        WHEN 1 THEN 'None'
        WHEN 2 THEN 'Beard/Mustache'
        WHEN 3 THEN 'Goatee'
        WHEN 5 THEN 'Stubble'
        ELSE ZDETECTEDFACE.ZFACIALHAIRTYPE
    END AS 'FacialHairType',
    CASE ZDETECTEDFACE.ZBALDTYPE
        WHEN 2 THEN 'Bald'
        WHEN 3 THEN 'NotBald'
        ELSE ZDETECTEDFACE.ZBALDTYPE
    END AS 'Baldness',
    ZGENERICASSET.ZORIGINALCOLORSPACE AS 'ColorSpace',
    ZGENERICASSET.Zduration AS 'Duration',
    ZGENERICASSET.Zvideocpdurationvalue AS 'VideoDuration',
    CASE ZGENERICASSET.ZCOMPLETE
        WHEN 1 THEN 'Yes'
        ELSE ZGENERICASSET.ZCOMPLETE
    END AS 'Complete',
    CASE ZGENERICASSET.ZVISIBILITYSTATE
        WHEN 0 THEN 'Visible'
        WHEN 1 THEN 'PhotoStreamsData'
        WHEN 2 THEN 'Burst'
        ELSE ZGENERICASSET.ZVISIBILITYSTATE
    END AS 'VisibilityState',
    CASE ZGENERICASSET.ZFAVORITE
        WHEN 0 THEN 'No'
        WHEN 1 THEN 'Yes'
        ELSE ZGENERICASSET.ZFAVORITE
    END AS 'IsFavorite',
    CASE ZGENERICASSET.zhidden
        WHEN 0 THEN 'No Hidden'
        WHEN 1 THEN 'FileHidden'
        ELSE ZGENERICASSET.zhidden
    END AS 'HiddenFile',
    CASE ZGENERICASSET.ZTRASHEDSTATE
        WHEN 1 THEN 'InTrash'
        WHEN 0 THEN 'NotInTrash'
        ELSE ZGENERICASSET.ZTRASHEDSTATE
    END AS 'TrashState',
    CASE
        WHEN ZGENERICASSET.ZTRASHEDDATE IS NULL THEN 'N/A'
        ELSE datetime(ZGENERICASSET.ZTRASHEDDATE + 978307200, 'UNIXEPOCH')
    END AS 'FileTrashDate(UTC)',
    CASE
        WHEN ZGENERICASSET.ZTRASHEDDATE IS NULL THEN 'N/A'
        ELSE datetime(ZGENERICASSET.ZTRASHEDDATE + 978307200, 'UNIXEPOCH', 'localtime')
    END AS 'FileTrashDate(Local)',
    ZADDITIONALASSETATTRIBUTES.ZVIEWCOUNT AS 'ViewCount',
    ZADDITIONALASSETATTRIBUTES.ZPLAYCOUNT AS 'PlayCount',
    ZADDITIONALASSETATTRIBUTES.ZSHARECOUNT AS 'ShareCount',
    datetime(ZGENERICASSET.ZLASTSHAREDDATE + 978307200, 'UNIXEPOCH') AS 'LastSharedDate(UTC)',
    datetime(ZGENERICASSET.ZLASTSHAREDDATE + 978307200, 'UNIXEPOCH', 'localtime') AS 'LastSharedDate(Local)',
    datetime(ZGENERICASSET.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'FileModificationDate(UTC)',
    datetime(ZGENERICASSET.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH', 'localtime') AS 'FileModificationDate(Local)',
    CASE ZGENERICASSET.ZHASADJUSTMENTS
        WHEN 0 THEN 'No'
        WHEN 1 THEN 'Yes'
        ELSE ZGENERICASSET.ZHASADJUSTMENTS
    END AS 'HasAdjustments',
    datetime(ZGENERICASSET.ZADJUSTMENTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'AdjustmentsTimeStamp(UTC)',
    datetime(ZGENERICASSET.ZADJUSTMENTTIMESTAMP + 978307200, 'UNIXEPOCH', 'localtime') AS 'AdjustmentsTimeStamp(Local)',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALFILESIZE AS 'OriginalFileSize',
    ZGENERICASSET.ZHEIGHT AS 'FileHeight',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALHEIGHT AS 'OriginalFileHeight',
    ZGENERICASSET.ZWIDTH AS 'FileWidth',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALWIDTH AS 'OriginalFileWidth',
    ZADDITIONALASSETATTRIBUTES.ZCAMERACAPTUREDEVICE AS 'CameraCaptureDevice',
    CASE ZGENERICASSET.ZORIENTATION
        WHEN 1 THEN 'Horizontal(Left)'
        WHEN 3 THEN 'Horizontal(Right)'
        WHEN 6 THEN 'Vertical(Up)'
        WHEN 8 THEN 'Vertical(Down)'
        ELSE ZGENERICASSET.ZORIENTATION
    END AS 'Orientation',
    CASE ZADDITIONALASSETATTRIBUTES.ZORIGINALORIENTATION
        WHEN 1 THEN 'Horizontal(Left)'
        WHEN 3 THEN 'Horizontal(Right)'
        WHEN 6 THEN 'Vertical(Up)'
        WHEN 8 THEN 'Vertical(Down)'
        ELSE ZGENERICASSET.ZORIENTATION
    END AS 'OriginalOrientation',
    ZADDITIONALASSETATTRIBUTES.ZTIMEZONENAME AS 'TimeZoneName',
    ZADDITIONALASSETATTRIBUTES.ZTIMEZONEOFFSET AS 'TimeZoneOffset',
    ZADDITIONALASSETATTRIBUTES.ZINFERREDTIMEZONEOFFSET AS 'InferredTimeZoneOffset',
    ZGENERICASSET.ZLOCATIONDATA AS 'FileLocationData',
    CASE ZGENERICASSET.ZLATITUDE
        WHEN -180.0 THEN 'N/A'
        ELSE ZGENERICASSET.ZLATITUDE
    END 'Latitude',
    CASE ZGENERICASSET.ZLONGITUDE
        WHEN -180.0 THEN 'N/A'
        ELSE ZGENERICASSET.ZLONGITUDE
    END 'Longitude',
    CASE ZADDITIONALASSETATTRIBUTES.ZSHIFTEDLOCATIONISVALID
        WHEN 0 THEN 'No'
        WHEN 1 THEN 'Yes'
        ELSE ZADDITIONALASSETATTRIBUTES.ZSHIFTEDLOCATIONISVALID
    END AS 'ShiftedLocationValid',
    CASE ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATAISVALID
        WHEN 0 THEN 'NoCheckSceneAnalysis'
        WHEN 1 THEN 'YesCheckSceneAnalysis'
        ELSE ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATAISVALID
    END AS 'ReverseLocationDataIsValid',
    ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATA AS 'OriginalFileReverseLocationData',
    ZGENERICASSET.Zthumbnailindex AS 'ThumbnailIndex',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILWIDTH AS 'EmbeddedThumbnailWidth',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILHEIGHT AS 'EmbeddedThumbnailHeight',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILOFFSET AS 'EmbeddedThumbnailOffset',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILLENGTH AS 'EmbeddedThumbnailLength',
    ZGENERICASSET.ZMOMENT AS 'MomentPK',
    ZMOMENT.ZTITLE AS 'MomentTitle',
    datetime(ZMOMENT.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'MomentStartDate(UTC)',
    datetime(ZMOMENT.Zrepresentativedate + 978307200, 'UNIXEPOCH') AS 'MomentRepresentativeDate(UTC)',
    datetime(ZMOMENT.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'MomentModificationDate(UTC)',
    datetime(ZMOMENT.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'MomentEndDate(UTC)',
    CASE ZMOMENT.ZTRASHEDSTATE
        WHEN 1 THEN 'InTrash'
        WHEN 0 THEN 'NotInTrash'
        ELSE ZMOMENT.ZTRASHEDSTATE
    END AS 'MomentTrashState',
    CASE ZMOMENT.Zapproximatelatitude
        WHEN -180.0 THEN 'N/A'
        ELSE ZMOMENT.Zapproximatelatitude
    END AS 'MomentApproxLatitude',
    CASE ZMOMENT.Zapproximatelongitude
        WHEN -180.0 THEN 'N/A'
        ELSE ZMOMENT.Zapproximatelongitude
    END AS 'Momen ApproxLongitude',
    ZGENERICASSET.ZUUID AS 'UUID',
    ZGENERICASSET.ZMEDIAGROUPUUID AS 'MediaGroupUUID',
    ZGENERICASSET.ZCLOUDASSETGUID AS 'CloudAssetGUID',
    ZADDITIONALASSETATTRIBUTES.ZPUBLICGLOBALUUID AS 'PublicGlobalUUID',
    ZADDITIONALASSETATTRIBUTES.ZMASTERFINGERPRINT AS 'MasterFingerprint',
    ZADDITIONALASSETATTRIBUTES.ZADJUSTEDFINGERPRINT AS 'AdjustedFingerprint'

FROM ZGENERICASSET
    LEFT JOIN ZMOMENT ON ZGENERICASSET.ZMOMENT = ZMOMENT.Z_PK
    JOIN ZADDITIONALASSETATTRIBUTES ON ZGENERICASSET.ZADDITIONALATTRIBUTES = ZADDITIONALASSETATTRIBUTES.Z_PK
    LEFT JOIN ZDETECTEDFACE ON ZADDITIONALASSETATTRIBUTES.ZASSET = ZDETECTEDFACE.ZASSET
    LEFT JOIN ZPERSON ON ZPERSON.Z_PK = ZDETECTEDFACE.ZPERSON
    LEFT JOIN Z_26ASSETS ON ZGENERICASSET.Z_PK = Z_26ASSETS.Z_34ASSETS
    LEFT JOIN ZGENERICALBUM ON ZGENERICALBUM.Z_PK = Z_26ASSETS.Z_26ALBUMS

ORDER BY ZGENERICASSET.Z_PK ASC
