/*
Need to fix this query for iOS 14.  The album names have changed.
*/

SELECT
    ROW_NUMBER() OVER() AS 'RecordNo.',
    ZGENERICALBUM.Z_PK AS 'IndexNo.',
    ZGENERICALBUM.ZTITLE AS 'AlbumTitle',
    ZASSET.ZDIRECTORY AS 'Directory',
    ZASSET.ZFILENAME AS 'FileName',
    ZASSET.ZUNIFORMTYPEIDENTIFIER AS 'FileType',
    CASE ZASSET.ZFAVORITE
        WHEN 0 THEN 'No'
        WHEN 1 THEN 'Yes'
        ELSE ZASSET.ZFAVORITE
    END AS 'IsFavorite',
    ZASSET.ZDURATION AS 'Duration(seconds)',
    CASE
        WHEN LENGTH (ZASSET.ZDATECREATED) = 18 THEN datetime((ZASSET.ZDATECREATED / 1000000000) + 978307200, 'UNIXEPOCH')
        WHEN LENGTH (ZASSET.ZDATECREATED) = 9 THEN datetime(ZASSET.ZDATECREATED + 978307200, 'UNIXEPOCH')
        ELSE ZASSET.ZDATECREATED
    END AS 'DateCreated(UTC)',
    datetime(ZASSET.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'DateAdded(UTC)',
    datetime(ZASSET.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'ModificationDate(UTC)',
    datetime(ZASSET.ZTRASHEDDATE + 978307200, 'UNIXEPOCH') AS 'TrashedDate(UTC)',
    ZASSET.ZTHUMBNAILINDEX AS 'ThumbnailIndex',
    CASE ZASSET.ZLATITUDE
        WHEN '-180.0' THEN 'n/a'
        ELSE ZASSET.ZLATITUDE
    END 'Latitude',
    CASE ZASSET.ZLONGITUDE
        WHEN '-180.0' THEN 'n/a'
        ELSE ZASSET.ZLONGITUDE
    END 'Longitude'

FROM ZASSET
    INNER JOIN
        (ZGENERICALBUM INNER JOIN Z_26ASSETS ON ZGENERICALBUM.Z_PK = Z_26ASSETS.Z_26ALBUMS) ON ZASSET.Z_PK = Z_26ASSETS.Z_3ASSETS

ORDER BY ZGENERICALBUM.Z_PK
