SELECT
    ROW_NUMBER() OVER() AS 'RecordNo.',
    ZGENERICALBUM.Z_PK AS 'ZGENERICALBUM Z_PK',
    ZGENERICALBUM.ZTITLE AS 'AlbumTitle',
    ZGENERICASSET.ZDIRECTORY AS 'Directory',
    ZGENERICASSET.ZFILENAME AS 'FileName',
    ZGENERICASSET.ZUNIFORMTYPEIDENTIFIER AS 'FileType',
    CASE ZGENERICASSET.ZFAVORITE
        WHEN '0' THEN 'No'
        WHEN '1' THEN 'Yes'
        ELSE ZGENERICASSET.ZFAVORITE
    END 'IsFavorite',
    ZGENERICASSET.ZDURATION AS 'Duration(seconds)',
    CASE
        WHEN LENGTH(ZGENERICASSET.ZDATECREATED) = 18
            THEN datetime((ZGENERICASSET.ZDATECREATED / 1000000000) + 978307200, 'UNIXEPOCH')
        WHEN LENGTH(ZGENERICASSET.ZDATECREATED) = 9
            THEN datetime(ZGENERICASSET.ZDATECREATED + 978307200, 'UNIXEPOCH')
        ELSE ZGENERICASSET.ZDATECREATED
    END AS 'DateCreated(UTC)',
    CASE
        WHEN LENGTH(ZGENERICASSET.ZADDEDDATE) = 18
            THEN datetime((ZGENERICASSET.ZADDEDDATE / 1000000000) + 978307200, 'UNIXEPOCH')
        WHEN LENGTH(ZGENERICASSET.ZADDEDDATE) = 9
            THEN datetime(ZGENERICASSET.ZADDEDDATE + 978307200, 'UNIXEPOCH')
        ELSE ZGENERICASSET.ZADDEDDATE
    END AS 'DateAdded(UTC)',
    CASE
        WHEN LENGTH(ZGENERICASSET.ZMODIFICATIONDATE) = 18
            THEN datetime((ZGENERICASSET.ZMODIFICATIONDATE / 1000000000) + 978307200, 'UNIXEPOCH')
        WHEN LENGTH(ZGENERICASSET.ZMODIFICATIONDATE) = 9
            THEN datetime(ZGENERICASSET.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH')
        ELSE ZGENERICASSET.ZMODIFICATIONDATE
    END AS 'ModificationDate(UTC)',
    CASE
        WHEN LENGTH(ZGENERICASSET.ZTRASHEDDATE) = 18
            THEN datetime((ZGENERICASSET.ZTRASHEDDATE / 1000000000) + 978307200, 'UNIXEPOCH')
        WHEN LENGTH(ZGENERICASSET.ZTRASHEDDATE) = 9
            THEN datetime(ZGENERICASSET.ZTRASHEDDATE + 978307200, 'UNIXEPOCH')
        ELSE ZGENERICASSET.ZTRASHEDDATE
    END AS 'TrashedDate(UTC)',
    ZGENERICASSET.ZTHUMBNAILINDEX AS 'ThumbnailIndex',
    CASE ZGENERICASSET.ZLATITUDE
        WHEN '-180.0' THEN 'N/A'
        ELSE ZGENERICASSET.ZLATITUDE
    END 'Latitude',
    CASE ZGENERICASSET.ZLONGITUDE
        WHEN '-180.0' THEN 'N/A'
        ELSE ZGENERICASSET.ZLONGITUDE
    END 'Longitude'

FROM ZGENERICASSET
    INNER JOIN (ZGENERICALBUM INNER JOIN Z_26ASSETS ON ZGENERICALBUM.Z_PK = Z_26ASSETS.Z_26ALBUMS) ON ZGENERICASSET.Z_PK = Z_26ASSETS.Z_34ASSETS

ORDER BY ZGENERICALBUM.Z_PK
