SELECT
    ROW_NUMBER() OVER() AS 'RecordNo.',
    PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME.BundleID AS 'BundleID',
    PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME.ScreenOnTime AS 'Focus(Seconds)',
    PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME.BackgroundTime AS 'Background(Seconds)',
    datetime (PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME.timestamp, 'UNIXEPOCH') AS 'Timestamp(UTC)',
    datetime (PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME.timestamp, 'UNIXEPOCH', 'localtime') AS 'Timestamp(Local)',
    'Table: PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME(ID: ' || PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME.ID || ')' AS 'DataSource'

FROM PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME

--WHERE BundleID LIKE '%whatsapp%'

ORDER BY PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME.timestamp ASC
