/*
File Path = \private\var\mobile\Library\Application Support\com.apple.remotemanagementd
File Names = RMAdminStore-Local.sqlite & RMAdminStore-Cloud.sqlite
*/

SELECT
    ROW_NUMBER() OVER() AS 'RecordNo.',
    datetime(ZUSAGEBLOCK.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'StartDate(UTC)',
    datetime(ZUSAGEBLOCK.ZSTARTDATE + 978307200, 'UNIXEPOCH', 'localtime') AS 'StartDate(Local)',
    datetime(ZUSAGEBLOCK.ZLASTEVENTDATE + 978307200, 'UNIXEPOCH') AS 'EndDate(UTC)',
    datetime(ZUSAGEBLOCK.ZLASTEVENTDATE + 978307200, 'UNIXEPOCH', 'localtime') AS 'EndDate(Local)',
    ZUSAGETIMEDITEM.ZTOTALTIMEINSECONDS AS 'AppUsageTime(seconds)',
    ZUSAGETIMEDITEM.ZTOTALTIMEINSECONDS / 60.00 AS 'AppUsageTime(minutes)',
    ZUSAGETIMEDITEM.ZBUNDLEIDENTIFIER AS 'BundleID',
    CASE ZUSAGECATEGORY.ZIDENTIFIER
        WHEN 'DH0011' THEN 'Unspecified1'
        WHEN 'DH0012' THEN 'Unspecified2'
        WHEN 'DH0013' THEN 'Unspecified3'
        WHEN 'DH1001' THEN 'Games'
        WHEN 'DH1002' THEN 'SocialNetworking'
        WHEN 'DH1003' THEN 'Entertainment'
        WHEN 'DH1004' THEN 'Creativity'
        WHEN 'DH1005' THEN 'Productivity'
        WHEN 'DH1006' THEN 'Education'
        WHEN 'DH1007' THEN 'Reading/Reference'
        WHEN 'DH1008' THEN 'Health/Fitness'
        WHEN 'DH1009' THEN 'Other'
        ELSE ZUSAGECATEGORY.ZIDENTIFIER
    END AS 'CategoryID',
    ZUSAGECOUNTEDITEM.ZNUMBEROFNOTIFICATIONS AS 'Notifications',
    ZUSAGECOUNTEDITEM.ZNUMBEROFPICKUPS AS 'Pickups',
    ZUSAGEBLOCK.ZNUMBEROFPICKUPSWITHOUTAPPLICATIONUSAGE AS 'Pickups(NoAppUsage)',
    ZCOREDEVICE.ZNAME AS 'DeviceName',
    ZCOREDEVICE.ZIDENTIFIER AS 'DeviceID',
    CASE ZCOREDEVICE.ZPLATFORM
        WHEN 0 THEN 'Unknown'
        WHEN 1 THEN 'macOS'
        WHEN 2 THEN 'iOS'
        WHEN 4 THEN 'AppleWatch'
        ELSE ZCOREDEVICE.ZPLATFORM
    END AS 'DevicePlatform',
    ZCOREUSER.ZAPPLEID AS 'AppleID',
    ZCOREUSER.ZDSID AS 'DSID',
    ZCOREUSER.ZALTDSID AS 'AltDSID',
    ZCOREUSER.ZGIVENNAME || ' ' || ZCOREUSER.ZFAMILYNAME AS 'FullName',
    ZCOREUSER.ZFAMILYMEMBERTYPE AS 'FamilyType',
    'Table: ZUSAGEGETIMEDITEM (Z_PK:' || ZUSAGETIMEDITEM.Z_PK || ')' AS 'DataSource'

FROM ZUSAGETIMEDITEM
    LEFT JOIN ZUSAGECATEGORY ON ZUSAGECATEGORY.Z_PK = ZUSAGETIMEDITEM.ZCATEGORY
    LEFT JOIN ZUSAGEBLOCK ON ZUSAGEBLOCK.Z_PK = ZUSAGECATEGORY.ZBLOCK
    LEFT JOIN ZUSAGE ON ZUSAGE.Z_PK = ZUSAGEBLOCK.ZUSAGE
    LEFT JOIN ZCOREDEVICE ON ZCOREDEVICE.Z_PK = ZUSAGE.ZDEVICE
    LEFT JOIN ZCOREUSER ON ZCOREUSER.Z_PK = ZUSAGE.ZUSER
    LEFT JOIN ZUSAGECOUNTEDITEM ON ZUSAGECOUNTEDITEM.ZBLOCK = ZUSAGECATEGORY.ZBLOCK AND ZUSAGECOUNTEDITEM.ZBUNDLEIDENTIFIER = ZUSAGETIMEDITEM.ZBUNDLEIDENTIFIER

--WHERE ZUSAGETIMEDITEM.ZBUNDLEIDENTIFIER LIKE '%whatsapp%'

ORDER BY ZUSAGEBLOCK.ZSTARTDATE ASC


--ZUC.ZTOTALTIMEINSECONDS AS 'Total_Time (from ZUC)',
--ZUSAGEBLOCK.ZSCREENTIMEINSECONDS AS 'Screen_Time (from ZUSAGEBLOCK)',
