
SELECT
    ZWAADDRESSBOOKCONTACT.Z_PK AS 'ID',
    ZWAADDRESSBOOKCONTACT.ZGIVENNAME AS 'Given Name',
    ZWAADDRESSBOOKCONTACT.ZHIGHLIGHTEDNAME AS 'Highlighted Name',
    ZWAADDRESSBOOKCONTACT.ZFULLNAME AS 'Full Name',
    ZWAADDRESSBOOKCONTACT.ZABOUTTEXT AS 'About Text',
    datetime(ZWAADDRESSBOOKCONTACT.ZABOUTTIMESTAMP + 978307200, 'unixepoch') AS 'About Timestamp (UTC)',
    ZWAADDRESSBOOKCONTACT.ZPHONENUMBER AS 'Phone Number',
    CASE ZWAADDRESSBOOKCONTACT.ZPHONENUMBERLABEL
        WHEN '_$!<Work>!$_' THEN 'Work'
        WHEN '_$!<Mobile>!$_' THEN 'Mobile'
        WHEN '_$!<Home>!$_' THEN 'Home'
        WHEN '_$!<Other>!$_' THEN 'Other'
        ELSE ZWAADDRESSBOOKCONTACT.ZPHONENUMBERLABEL
    END AS 'Label',
    ZWAADDRESSBOOKCONTACT.ZWHATSAPPID AS 'WhatsApp ID'

FROM ZWAADDRESSBOOKCONTACT

order by ZWAADDRESSBOOKCONTACT.Z_PK ASC
