SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME.BundleID AS 'APPRUNTIME.BundleID',
    PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME.ScreenOnTime AS 'APPRUNTIME.ScreenOnTime(Seconds)',
    PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME.BackgroundTime AS 'APPRUNTIME.BackgroundTime(Seconds)',

    datetime (PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME.timestamp, 'UNIXEPOCH') AS 'APPRUNTIME.timestamp(UTC)',

    /* Source for each line of data */
    'Table: PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME(ID: ' || PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME.ID || ')' AS 'DATA_SOURCE'


FROM PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME


WHERE
    PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME.BundleID LIKE '%whatsapp%'


ORDER BY
    PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME.timestamp ASC
