SELECT

    ROW_NUMBER() OVER() AS 'RecordNo.',
    PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME.BundleID AS 'BundleID',
    PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME.ScreenOnTime AS 'Focus(Seconds)',
    PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME.BackgroundTime AS 'Background(Seconds)',
    datetime (PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME.timestamp, 'UNIXEPOCH') AS 'DateTimestamp(UTC)',

    /* Source for each line of data */
    'Table: PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME(ID: ' || PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME.ID || ')' AS 'DataSource'


FROM PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME


WHERE
    PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME.BundleID LIKE '%whatsapp%'


ORDER BY
    PLAPPTIMESERVICE_AGGREGATE_APPRUNTIME.timestamp ASC
