SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    ZRTWIFIACCESSPOINTMO.Z_PK AS 'ZRTWIFIACCESSPOINTMO.Z_PK',

    strftime('%Y-%m-%dT%H:%M:%SZ', datetime(ZRTWIFIACCESSPOINTMO.ZDATE + 978307200, 'UNIXEPOCH')) AS 'ZRTWIFIACCESSPOINTMO.ZDATE(UTC)',

    ZRTWIFIACCESSPOINTMO.ZCHANNEL AS 'ZRTWIFIACCESSPOINTMO.ZCHANNEL',
    ZRTWIFIACCESSPOINTMO.ZRSSI AS 'ZRTWIFIACCESSPOINTMO.ZRSSI',
    UPPER(ZRTWIFIACCESSPOINTMO.ZMAC) AS 'ZRTWIFIACCESSPOINTMO.ZMAC'


FROM ZRTWIFIACCESSPOINTMO


ORDER BY
    ZRTWIFIACCESSPOINTMO.ZDATE ASC