/*
[DLU]
    05-Sep-2025
*/

SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    ZRTADDRESSMO.Z_PK AS 'ADDRESS-Z_PK',
    ZRTMAPITEMMO.Z_PK AS 'MAPITEM-Z_PK',
    ZRTADDRESSMO.ZMAPITEM AS 'ZRTADDRESSMO.ZMAPITEM',
    ZRTMAPITEMMO.ZADDRESS AS 'ZRTMAPITEMMO.ZADDRESS',

    strftime('%Y-%m-%dT%H:%M:%SZ', datetime(ZRTADDRESSMO.ZCREATIONDATE + 978307200, 'UNIXEPOCH')) AS 'CREATION-DATE(UTC)',
    strftime('%Y-%m-%dT%H:%M:%SZ', datetime(ZRTADDRESSMO.ZEXPIRATIONDATE + 978307200, 'UNIXEPOCH')) AS 'EXPIRATION-DATE(UTC)',

    ZRTADDRESSMO.ZSUBTHOROUGHFARE || ' ' || ZRTADDRESSMO.ZTHOROUGHFARE || ', ' || ZRTADDRESSMO.ZLOCALITY || ', ' || ZRTADDRESSMO.ZADMINISTRATIVEAREA || ' ' || ZRTADDRESSMO.ZPOSTALCODE || ' ' || ZRTADDRESSMO.ZCOUNTRYCODE AS 'ITEM-ADDRESS',

    ZRTMAPITEMMO.ZLATITUDE AS 'Latitude',
    ZRTMAPITEMMO.ZLONGITUDE AS 'Longitude',
    RTRIM(LTRIM(CONCAT(ROUND(ZRTMAPITEMMO.ZLATITUDE, 6), ',', ROUND(ZRTMAPITEMMO.ZLONGITUDE, 6)))) AS 'Lat/Long(Merged)',

    ZRTMAPITEMMO.ZUNCERTAINTY AS 'UNCERTAINTY',

    /* Source for each line of data */
    'Cloud-V2.sqlite; Table: ZRTADDRESSMO(Z_PK:' || ZRTADDRESSMO.Z_PK || ')' AS 'DATA_SOURCE'


FROM ZRTADDRESSMO
    LEFT JOIN ZRTMAPITEMMO ON ZRTADDRESSMO.ZMAPITEM = ZRTMAPITEMMO.ZADDRESS


ORDER BY
    ZRTADDRESSMO.ZCREATIONDATE DESC