SELECT

    Z_PK,
    Z_ENT,
    Z_OPT,
    ZPREDOMINANTMOTIONACTIVITYTYPE,
    ZLOCATIONOFINTEREST,
    strftime('%m-%d-%Y %H:%M:%fZ', datetime(ZCREATIONDATE + 978307200, 'UNIXEPOCH')) AS 'Creation Date/Time (UTC)',
    strftime('%m-%d-%Y %H:%M:%fZ', datetime(ZSTARTDATE + 978307200, 'UNIXEPOCH')) AS 'Start Date/Time (UTC)',
    strftime('%m-%d-%Y %H:%M:%fZ', datetime(ZSTOPDATE + 978307200, 'UNIXEPOCH')) AS 'Stop Date/Time (UTC)',
    strftime('%m-%d-%Y %H:%M:%fZ', datetime(ZEXPIRATIONDATE + 978307200, 'UNIXEPOCH')) AS 'Expiration Date/Time (UTC)',
    hex(ZIDENTIFIER) AS 'ZIDENTIFIER(hex)',
    hex(ZVISITIDENTIFIERDESTINATION) AS 'ZVISITIDENTIFIERDESTINATION(hex)',
    hex(ZVISITIDENTIFIERORIGIN) AS 'ZVISITIDENTIFIERORIGIN(hex)'


FROM ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO


--WHERE Z_PK = '159459'


ORDER BY ZVISITIDENTIFIERDESTINATION ASC