SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    ZRTLEARNEDLOCATIONOFINTERESTVISITMO.Z_PK AS 'ZRTLEARNEDLOCATIONOFINTERESTVISITMO.Z_PK',
    ZRTLEARNEDLOCATIONOFINTERESTVISITMO.ZLOCATIONOFINTEREST AS 'ZLOCATIONOFINTEREST',

    datetime(ZRTLEARNEDLOCATIONOFINTERESTVISITMO.ZENTRYDATE + 978307200, 'UNIXEPOCH') AS 'Entry Date/Time (UTC)',
    datetime(ZRTLEARNEDLOCATIONOFINTERESTVISITMO.ZEXITDATE + 978307200, 'UNIXEPOCH') AS 'Exit Date/Time (UTC)',

    (ZRTLEARNEDLOCATIONOFINTERESTVISITMO.ZEXITDATE-ZRTLEARNEDLOCATIONOFINTERESTVISITMO.ZENTRYDATE) / 60.00 AS 'Exit Time (Minutes)',

    ZRTLEARNEDLOCATIONOFINTERESTMO.ZLOCATIONLATITUDE || ', ' || ZRTLEARNEDLOCATIONOFINTERESTMO.ZLOCATIONLONGITUDE AS 'Coordinates',
    ZRTLEARNEDLOCATIONOFINTERESTMO.ZLOCATIONLATITUDE AS 'Latitude',
    ZRTLEARNEDLOCATIONOFINTERESTMO.ZLOCATIONLONGITUDE AS 'Longitude',
    ZRTLEARNEDLOCATIONOFINTERESTVISITMO.ZCONFIDENCE AS 'Confidence',
    ZRTLEARNEDLOCATIONOFINTERESTVISITMO.ZLOCATIONOFINTERESTCONFIDENCE AS 'LOI Confidencde',
    ZRTLEARNEDLOCATIONOFINTERESTVISITMO.ZLOCATIONHORIZONTALUNCERTAINTY AS 'Horizonal Location Uncertainty',
    ZRTLEARNEDLOCATIONOFINTERESTVISITMO.ZLOCATIONVERTICALUNCERTAINTY AS 'Vertical Location Uncertainty',
    ZRTLEARNEDLOCATIONOFINTERESTVISITMO.ZDATAPOINTCOUNT AS 'Data Point Count',

    datetime(ZRTLEARNEDLOCATIONOFINTERESTVISITMO.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'Place Creation Date/Time (UTC)',
    datetime(ZRTLEARNEDLOCATIONOFINTERESTVISITMO.ZEXPIRATIONDATE + 978307200, 'UNIXEPOCH') AS 'Expiration Date/Time (UTC)',

    ZRTLEARNEDLOCATIONOFINTERESTVISITMO.ZLOCATIONLATITUDE AS 'Visit Latitude',
    ZRTLEARNEDLOCATIONOFINTERESTVISITMO.ZLOCATIONLONGITUDE AS 'Visit Longitude',

    /* Source for each line of data */
    'Local.sqlite; Table: ZRTLEARNEDLOCATIONOFINTERESTVISITMO(Z_PK:' || ZRTLEARNEDLOCATIONOFINTERESTVISITMO.Z_PK || ')' AS 'DATA_SOURCE'


FROM ZRTLEARNEDLOCATIONOFINTERESTVISITMO
	LEFT JOIN ZRTLEARNEDLOCATIONOFINTERESTMO ON ZRTLEARNEDLOCATIONOFINTERESTMO.Z_PK = ZRTLEARNEDLOCATIONOFINTERESTVISITMO.ZLOCATIONOFINTEREST