SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    ZRTVEHICLEEVENTHISTORYMO.Z_PK AS 'ZRTLEARNEDVISITMO.Z_PK',

    datetime(ZRTVEHICLEEVENTHISTORYMO.ZDATE + 978307200, 'UNIXEPOCH') AS 'Date/Time (UTC)',
    datetime(ZRTVEHICLEEVENTHISTORYMO.ZLOCDATE + 978307200, 'UNIXEPOCH') AS 'Location Date/Time (UTC)',

    ZLOCLATITUDE || ', ' || ZLOCLONGITUDE AS 'COORDINATES',
    ZLOCUNCERTAINTY AS 'LOCATION UNCERTAINTY',
    ZIDENTIFIER AS 'IDENTIFIER',
    ZLOCLATITUDE AS 'LATITUDE',
    ZLOCLONGITUDE AS 'LONGITUDE'


FROM ZRTVEHICLEEVENTHISTORYMO