SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    ZRTVEHICLEEVENTMO.Z_PK AS 'ZRTVEHICLEEVENTMO.Z_PK',

    datetime(ZRTVEHICLEEVENTMO.ZDATE + 978307200, 'UNIXEPOCH') AS 'Date/Time (UTC)',
    datetime(ZRTVEHICLEEVENTMO.ZLOCDATE + 978307200, 'UNIXEPOCH') AS 'Location Date/Time (UTC)',

    ZLOCLATITUDE || ', ' || ZLOCLONGITUDE AS 'COORDINATES',
    ZLOCLATITUDE AS 'LATITUDE',
    ZLOCLONGITUDE AS 'LONGITUDE',
    ZVEHICLEIDENTIFIER AS 'VEHICLE IDENTIFIER',
    ZLOCUNCERTAINTY AS 'LOCATION UNCERTAINTY',
    ZIDENTIFIER AS 'IDENTIFIER',
    ZLOCATIONQUALITY AS 'LOCATION QUALITY',
    ZUSERSETLOCATION AS 'USER SET LOCATION',
    ZUSUALLOCATION AS 'USUAL LOCATION',
    ZNOTES AS 'NOTES',
    ZPHOTODATA AS 'PHOTO DATA'


FROM ZRTVEHICLEEVENTMO