SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    ZRTVEHICLEEVENTHISTORYMO.Z_PK AS 'ZRTLEARNEDVISITMO.Z_PK',

    datetime(ZRTVEHICLEEVENTHISTORYMO.ZDATE + 978307200, 'UNIXEPOCH') AS 'Date/Time (UTC)',
    datetime(ZRTVEHICLEEVENTHISTORYMO.ZLOCDATE + 978307200, 'UNIXEPOCH') AS 'Location Date/Time (UTC)',

    ZLOCLATITUDE AS 'LATITUDE',
    ZLOCLONGITUDE AS 'LONGITUDE',
    RTRIM(LTRIM(CONCAT(ROUND(ZLOCLATITUDE, 6), ',', ROUND(ZLOCLONGITUDE, 6)))) AS 'GPS(Merged)',

    ZLOCUNCERTAINTY AS 'LOCATION UNCERTAINTY',
    ZIDENTIFIER AS 'IDENTIFIER',


FROM ZRTVEHICLEEVENTHISTORYMO