SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    ZRTVEHICLEEVENTHISTORYMO.Z_PK AS 'ZRTLEARNEDVISITMO.Z_PK',

    datetime(ZRTVEHICLEEVENTHISTORYMO.ZDATE + 978307200, 'UNIXEPOCH') AS 'Date/Time (UTC)',
    datetime(ZRTVEHICLEEVENTHISTORYMO.ZLOCDATE + 978307200, 'UNIXEPOCH') AS 'Location Date/Time (UTC)',

    ZRTVEHICLEEVENTHISTORYMO.ZLOCLATITUDE AS 'LATITUDE',
    ZRTVEHICLEEVENTHISTORYMO.ZLOCLONGITUDE AS 'LONGITUDE',
    RTRIM(LTRIM(CONCAT(ROUND(ZRTVEHICLEEVENTHISTORYMO.ZLOCLATITUDE, 6), ',', ROUND(ZRTVEHICLEEVENTHISTORYMO.ZLOCLONGITUDE, 6)))) AS 'GPS(Merged)',

    ZRTVEHICLEEVENTHISTORYMO.ZLOCUNCERTAINTY AS 'LOCATION UNCERTAINTY',
    ZRTVEHICLEEVENTHISTORYMO.ZIDENTIFIER AS 'IDENTIFIER',


FROM ZRTVEHICLEEVENTHISTORYMO


ORDER BY ZRTVEHICLEEVENTHISTORYMO.ZDATE ASC