SELECT

    ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.Z_PK,
    ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.Z_ENT,
    ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.Z_OPT,
    ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZPREDOMINANTMOTIONACTIVITYTYPE,
    ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZLOCATIONOFINTEREST,

    strftime('%m-%d-%Y %H:%M:%fZ', datetime(ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZCREATIONDATE + 978307200, 'UNIXEPOCH')) AS 'Creation DateTime (UTC)',
    strftime('%m-%d-%Y %H:%M:%fZ', datetime(ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZSTARTDATE + 978307200, 'UNIXEPOCH')) AS 'Start DateTime (UTC)',
    strftime('%m-%d-%Y %H:%M:%fZ', datetime(ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZSTOPDATE + 978307200, 'UNIXEPOCH')) AS 'Stop DateTime (UTC)',
    strftime('%m-%d-%Y %H:%M:%fZ', datetime(ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZEXPIRATIONDATE + 978307200, 'UNIXEPOCH')) AS 'Expiration DateTime (UTC)',

    hex(ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZIDENTIFIER) AS 'ZIDENTIFIER(hex)',
    hex(ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZVISITIDENTIFIERORIGIN) AS 'ZVISITIDENTIFIERORIGIN(hex)',
    hex(ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZVISITIDENTIFIERDESTINATION) AS 'ZVISITIDENTIFIERDESTINATION(hex)'


FROM ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO


--WHERE Z_PK = '159459'


ORDER BY ZVISITIDENTIFIERDESTINATION ASC