/* Modified from the original script located at: https://github.com/mac4n6/APOLLO/blob/master/modules/routined_local_learned_location_of_interest_transition_stop.txt */

SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.Z_PK AS 'ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.Z_PK',
    ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZLOCATIONOFINTEREST AS 'ZLOCATIONOFINTEREST',

    datetime(ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'Start Date/Time (UTC)',
    datetime(ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZSTOPDATE + 978307200, 'UNIXEPOCH') AS 'Stop Date/Time (UTC)',

    ZRTLEARNEDLOCATIONOFINTERESTMO.ZLOCATIONLATITUDE || ', ' || ZRTLEARNEDLOCATIONOFINTERESTMO.ZLOCATIONLONGITUDE AS 'Coordinates',

    datetime(ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'Creation Date/Time (UTC)',
    datetime(ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZEXPIRATIONDATE + 978307200, 'UNIXEPOCH') AS 'Expiration Date/Time (UTC)',

    ZRTLEARNEDLOCATIONOFINTERESTMO.ZLOCATIONLATITUDE AS 'Latitude',
    ZRTLEARNEDLOCATIONOFINTERESTMO.ZLOCATIONLONGITUDE AS 'Longitude',

    HEX(ZRTLEARNEDLOCATIONOFINTERESTMO.ZIDENTIFIER) AS 'ZIDENTIFIER (HEX)',
    HEX(ZRTLEARNEDLOCATIONOFINTERESTMO.ZPLACEIDENTIFIER) AS 'ZPLACEIDENTIFIER (HEX)',
    HEX(ZRTLEARNEDLOCATIONOFINTERESTMO.ZPLACEMAPITEMIDENTIFIER) AS 'ZPLACEMAPITEMIDENTIFIER (HEX)',

    /* Source for each line of data */
    'Local.sqlite; Table: ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO(Z_PK:' || ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.Z_PK || ')' AS 'DATA_SOURCE'


FROM ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO
    LEFT JOIN ZRTLEARNEDLOCATIONOFINTERESTMO ON ZRTLEARNEDLOCATIONOFINTERESTMO.Z_PK = ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZLOCATIONOFINTEREST


ORDER BY ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZSTARTDATE ASC