SELECT

    ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.Z_PK AS 'LearnedLocOfInterestTransition.Z_PK',

    vo.ZLOCATIONLATITUDE || ', ' || vo.ZLOCATIONLONGITUDE AS 'Origin_Location',
    vd.ZLOCATIONLATITUDE || ', ' || vd.ZLOCATIONLONGITUDE AS 'Destination_Location',

    datetime(ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'Start Date/Time (UTC)',
    datetime(ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZSTOPDATE + 978307200, 'UNIXEPOCH') AS 'Stop Date/Time (UTC)',
    datetime(ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'Creation Date/Time (UTC)',

    vo.Z_PK AS 'OriginRecord.Z_PK',
    vd.Z_PK AS 'DestinationRecord.Z_PK',

    vo.ZLOCATIONOFINTEREST AS 'OriginLocationOfInterestID',
    vd.ZLOCATIONOFINTEREST AS 'DestinationLocationOfInterestID',

    vo.ZDATAPOINTCOUNT AS 'OriginDataPointCount',
    vd.ZDATAPOINTCOUNT AS 'DestinationDataPointCount',

    HEX(ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZVISITIDENTIFIERORIGIN) AS 'OriginIdentifier',
    HEX(ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZVISITIDENTIFIERDESTINATION) AS 'DestinationIdentifier',

    /* Source for each line of data */
    'Local.sqlite; Table: ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO(Z_PK:' || ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.Z_PK || '), ZRTLEARNEDLOCATIONOFINTERESTVISITMO(P_PK:' || vo.Z_PK || '), ZRTLEARNEDLOCATIONOFINTERESTVISITMO(P_PK:' || vd.Z_PK || ')' AS 'DATA_SOURCE'


FROM ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO
    LEFT JOIN ZRTLEARNEDLOCATIONOFINTERESTVISITMO vo ON vo.ZIDENTIFIER = ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZVISITIDENTIFIERORIGIN
    LEFT JOIN ZRTLEARNEDLOCATIONOFINTERESTVISITMO vd ON vd.ZIDENTIFIER = ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZVISITIDENTIFIERDESTINATION


-- WHERE
--     ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.Z_PK IS '159459' OR
--     ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.Z_PK IS '159035' OR
--     ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.Z_PK IS '159341'


ORDER BY ZRTLEARNEDLOCATIONOFINTERESTTRANSITIONMO.ZSTARTDATE ASC