SELECT

    ROW_NUMBER() OVER() AS 'RECORD-NUMBER',
    ZRTVEHICLEEVENTMO.Z_PK AS 'ZRTVEHICLEEVENTMO.Z_PK',

    datetime(ZRTVEHICLEEVENTMO.ZDATE + 978307200, 'UNIXEPOCH') AS 'DATETIME (UTC)',
    datetime(ZRTVEHICLEEVENTMO.ZLOCDATE + 978307200, 'UNIXEPOCH') AS 'LOCATION-DATETIME (UTC)',

    ZRTVEHICLEEVENTMO.ZLOCLATITUDE AS 'LATITUDE',
    ZRTVEHICLEEVENTMO.ZLOCLONGITUDE AS 'LONGITUDE',
    RTRIM(LTRIM(CONCAT(ROUND(ZRTVEHICLEEVENTMO.ZLOCLATITUDE, 6), ',', ROUND(ZRTVEHICLEEVENTMO.ZLOCLONGITUDE, 6)))) AS 'GPS(Merged)',

    ZRTVEHICLEEVENTMO.ZVEHICLEIDENTIFIER AS 'VEHICLE-IDENTIFIER',
    ZRTVEHICLEEVENTMO.ZLOCUNCERTAINTY AS 'LOCATION-UNCERTAINTY',
    ZRTVEHICLEEVENTMO.ZIDENTIFIER AS 'IDENTIFIER',
    ZRTVEHICLEEVENTMO.ZLOCATIONQUALITY AS 'LOCATION-QUALITY',
    ZRTVEHICLEEVENTMO.ZUSERSETLOCATION AS 'USER-SET-LOCATION',
    ZRTVEHICLEEVENTMO.ZUSUALLOCATION AS 'USUAL-LOCATION',
    ZRTVEHICLEEVENTMO.ZNOTES AS 'NOTES',
    ZRTVEHICLEEVENTMO.ZPHOTODATA AS 'PHOTO-DATA'


FROM ZRTVEHICLEEVENTMO


ORDER BY ZRTVEHICLEEVENTMO.ZDATE ASC