/*
    [DLU]
        2024-10-17
    [VERSION]
        Tested on iOS 18
    [DATABASE PATH]
        /private/var/mobile/Library/CoreDuet/People/interactionC.db
*/


SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    ZINTERACTIONS.Z_PK AS 'ZINTERACTIONS.Z_PK',

    CASE ZINTERACTIONS.ZDIRECTION
        WHEN 0 THEN 'Incoming'
        WHEN 1 THEN 'Outgoing'
        ELSE ZINTERACTIONS.ZDIRECTION
    END AS 'ZINTERACTIONS.ZDIRECTION',

    ZINTERACTIONS.ZBUNDLEID AS 'ZINTERACTIONS.ZBUNDLEID',
    ZINTERACTIONS.ZDOMAINIDENTIFIER AS 'ZINTERACTIONS.ZDOMAINIDENTIFIER',
    ZINTERACTIONS.ZGROUPNAME AS 'ZINTERACTIONS.ZGROUPNAME',
    ZINTERACTIONS.ZSENDER AS 'ZINTERACTIONS.ZSENDER',
    Z_2INTERACTIONRECIPIENT.Z_2RECIPIENTS AS 'Z_2INTERACTIONRECIPIENT.Z_2RECIPIENTS',
    ZCONTACTS.ZDISPLAYNAME AS 'ZCONTACTS.ZDISPLAYNAME',
    ZCONTACTS.ZIDENTIFIER AS 'ZCONTACTS.ZIDENTIFIER',
    ZINTERACTIONS.ZCONTENTURL AS 'ZINTERACTIONS.ZCONTENTURL',

    datetime(ZINTERACTIONS.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'ZINTERACTIONS.ZSTARTDATE(UTC)',
    datetime(ZINTERACTIONS.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'ZINTERACTIONS.ZENDDATE(UTC)',
    datetime(ZINTERACTIONS.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'ZINTERACTIONS.ZCREATIONDATE(UTC)',
    datetime(ZINTERACTIONS.ZUPDATEDATE + 978307200, 'UNIXEPOCH') AS 'ZINTERACTIONS.ZUPDATEDATE(UTC)',

    ZCONTACTS.ZINCOMINGRECIPIENTCOUNT AS 'ZCONTACTS.ZINCOMINGRECIPIENTCOUNT',

    datetime(ZCONTACTS.ZFIRSTINCOMINGRECIPIENTDATE + 978307200, 'UNIXEPOCH') AS 'ZCONTACTS.ZFIRSTINCOMINGRECIPIENTDATE(UTC)',

    ZCONTACTS.ZINCOMINGSENDERCOUNT AS 'ZCONTACTS.ZINCOMINGSENDERCOUNT',

    datetime(ZCONTACTS.ZFIRSTINCOMINGSENDERDATE + 978307200, 'UNIXEPOCH') AS 'ZCONTACTS.ZFIRSTINCOMINGSENDERDATE(UTC)',

    ZCONTACTS.ZOUTGOINGRECIPIENTCOUNT AS 'ZCONTACTS.ZOUTGOINGRECIPIENTCOUNT',

    datetime(ZCONTACTS.ZFIRSTOUTGOINGRECIPIENTDATE + 978307200, 'UNIXEPOCH') AS 'ZCONTACTS.ZFIRSTOUTGOINGRECIPIENTDATE(UTC)',

    CASE
        WHEN ZCONTACTS.ZLASTINCOMINGRECIPIENTDATE IS 0 THEN NULL
        ELSE datetime(ZCONTACTS.ZLASTINCOMINGRECIPIENTDATE + 978307200, 'UNIXEPOCH')
    END AS 'ZCONTACTS.ZLASTINCOMINGRECIPIENTDATE(UTC)',

    datetime(ZCONTACTS.ZLASTINCOMINGSENDERDATE + 978307200, 'UNIXEPOCH') AS 'ZCONTACTS.ZLASTINCOMINGSENDERDATE(UTC)',
    datetime(ZCONTACTS.ZLASTOUTGOINGRECIPIENTDATE + 978307200, 'UNIXEPOCH') AS 'ZCONTACTS.ZLASTOUTGOINGRECIPIENTDATE(UTC)',

    /* Source for each line of data */
    '/private/var/mobile/Library/CoreDuet/People/interactionC.db; Table: ZINTERACTIONS(Z_PK: ' || ZINTERACTIONS.Z_PK || ')' AS 'DATA_SOURCE'


FROM ZINTERACTIONS

    LEFT JOIN Z_2INTERACTIONRECIPIENT ON ZINTERACTIONS.Z_PK = Z_2INTERACTIONRECIPIENT.Z_3INTERACTIONRECIPIENT
    LEFT JOIN ZCONTACTS ON ZINTERACTIONS.ZSENDER = ZCONTACTS.Z_PK


WHERE
    --To filter between date/time points
    ZINTERACTIONS.ZSTARTDATE BETWEEN 750312000 AND 750449160


ORDER BY
    ZINTERACTIONS.ZSTARTDATE ASC
