/*
[DLU]
    2024-10-17
[VERSION]
    Tested on iOS 18
[DATABASE PATH]
    /private/var/mobile/Library/CoreDuet/People/interactionC.db
*/


SELECT

    ROW_NUMBER() OVER() AS 'RECORD-NUMBER',
    ZINTERACTIONS.Z_PK AS 'Z_PK',

    CASE ZINTERACTIONS.ZDIRECTION
        WHEN 0 THEN '0 [Incoming]'
        WHEN 1 THEN '1 [Outgoing]'
        ELSE ZINTERACTIONS.ZDIRECTION
    END AS 'MESSAGE-DIRECTION',

    ZINTERACTIONS.ZBUNDLEID AS 'ZINTERACTIONS.ZBUNDLEID' AS 'BUNDLE-ID',
    ZINTERACTIONS.ZDOMAINIDENTIFIER AS 'ZINTERACTIONS.ZDOMAINIDENTIFIER' AS 'DOMAIN-IDENTIFIER',
    ZINTERACTIONS.ZGROUPNAME AS 'ZINTERACTIONS.ZGROUPNAME' AS 'GROUP-NAME',
    ZINTERACTIONS.ZSENDER AS 'ZINTERACTIONS.ZSENDER' AS 'SENDER',
    Z_2INTERACTIONRECIPIENT.Z_2RECIPIENTS AS 'Z_2INTERACTIONRECIPIENT.Z_2RECIPIENTS' AS 'RECIPIENTS',
    ZCONTACTS.ZDISPLAYNAME AS 'ZCONTACTS.ZDISPLAYNAME' AS 'DISPLAY-NAME',
    ZCONTACTS.ZIDENTIFIER AS 'ZCONTACTS.ZIDENTIFIER' AS 'IDENTIFIER',
    ZINTERACTIONS.ZCONTENTURL AS 'ZINTERACTIONS.ZCONTENTURL' AS 'CONTENT-URL',

    datetime(ZINTERACTIONS.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'START-DATE(UTC)',
    datetime(ZINTERACTIONS.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'END-DATE(UTC)',
    datetime(ZINTERACTIONS.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'CREATION-DATE(UTC)',
    datetime(ZINTERACTIONS.ZUPDATEDATE + 978307200, 'UNIXEPOCH') AS 'UPDATE-DATE(UTC)',

    ZCONTACTS.ZINCOMINGRECIPIENTCOUNT AS 'INCOMING-RECIPIENT-COUNT',

    datetime(ZCONTACTS.ZFIRSTINCOMINGRECIPIENTDATE + 978307200, 'UNIXEPOCH') AS 'FIRST-INCOMING-RECIPIENT-DATE(UTC)',

    ZCONTACTS.ZINCOMINGSENDERCOUNT AS 'ZCONTACTS.ZINCOMINGSENDERCOUNT',

    datetime(ZCONTACTS.ZFIRSTINCOMINGSENDERDATE + 978307200, 'UNIXEPOCH') AS 'FIRST-INCOMING-SENDER-DATE(UTC)',

    ZCONTACTS.ZOUTGOINGRECIPIENTCOUNT AS 'ZCONTACTS.ZOUTGOINGRECIPIENTCOUNT',

    datetime(ZCONTACTS.ZFIRSTOUTGOINGRECIPIENTDATE + 978307200, 'UNIXEPOCH') AS 'FIRST-OUTGOING-RECIPIENT-DATE(UTC)',

    CASE
        WHEN ZCONTACTS.ZLASTINCOMINGRECIPIENTDATE IS 0 THEN NULL
        ELSE datetime(ZCONTACTS.ZLASTINCOMINGRECIPIENTDATE + 978307200, 'UNIXEPOCH')
    END AS 'LAST-INCOMING-RECIPIENT-DATE(UTC)',

    datetime(ZCONTACTS.ZLASTINCOMINGSENDERDATE + 978307200, 'UNIXEPOCH') AS 'LAST-INCOMING-SENDER-DATE(UTC)',
    datetime(ZCONTACTS.ZLASTOUTGOINGRECIPIENTDATE + 978307200, 'UNIXEPOCH') AS 'LAST-OUT-GOING-RECIPIENT-DATE(UTC)',

    /* Source for each line of data */
    'interactionC.db; Table: ZINTERACTIONS(Z_PK: ' || ZINTERACTIONS.Z_PK || ')' AS 'DATA-SOURCE'


FROM ZINTERACTIONS
    LEFT JOIN Z_2INTERACTIONRECIPIENT ON ZINTERACTIONS.Z_PK = Z_2INTERACTIONRECIPIENT.Z_3INTERACTIONRECIPIENT
    LEFT JOIN ZCONTACTS ON ZINTERACTIONS.ZSENDER = ZCONTACTS.Z_PK


WHERE
    --To filter between date/time points
    ZINTERACTIONS.ZSTARTDATE BETWEEN 750312000 AND 750449160


ORDER BY
    ZINTERACTIONS.ZSTARTDATE ASC
