/*
[DLU]
    23-Jul-2025
[DATABASE FILE]
    /private/var/wireless/Library/Databases/DataUsage.sqlite
*/

SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',

    CASE
        WHEN ZLIVEUSAGE.ZTIMESTAMP IS NULL THEN '[N/A]'
        ELSE datetime(ZLIVEUSAGE.ZTIMESTAMP + 978307200, 'UNIXEPOCH')
    END AS 'ZLIVEUSAGE.ZTIMESTAMP(UTC)',

    datetime(ZPROCESS.ZFIRSTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZPROCESS.ZFIRSTTIMESTAMP(UTC)',
    datetime(ZPROCESS.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZPROCESS.ZTIMESTAMP(UTC)',

    ZPROCESS.ZPROCNAME AS 'ZPROCESS.ZPROCNAME',
    ZPROCESS.ZBUNDLENAME AS 'ZPROCESS.ZBUNDLENAME',
    printf("%,d", ZLIVEUSAGE.ZWIFIIN) AS 'ZLIVEUSAGE.ZWIFIIN(BYTES)',
    printf("%,d", ZLIVEUSAGE.ZWIFIOUT) AS 'ZLIVEUSAGE.ZWIFIOUT(BYTES)',
    printf("%,d", ZLIVEUSAGE.ZWWANIN) AS 'ZLIVEUSAGE.ZWWANIN(BYTES)',
    printf("%,d", ZLIVEUSAGE.ZWWANOUT) AS 'ZLIVEUSAGE.ZWWANOUT(BYTES)',

    /* Source for each line of data */
    'DataUsage.sqlite; Table: ZLIVEUSAGE(Z_PK:' || ZLIVEUSAGE.Z_PK || '), ' || 'Table: ZPROCESS(Z_PK:' || ZPROCESS.Z_PK || ')' AS 'DATA_SOURCE'


FROM ZLIVEUSAGE
    LEFT JOIN ZPROCESS ON ZLIVEUSAGE.ZHASPROCESS = ZPROCESS.Z_PK


WHERE
    ZPROCESS.ZPROCNAME LIKE '%compress%' OR
    ZPROCESS.ZBUNDLENAME LIKE '%compress%'


ORDER BY
    ZLIVEUSAGE.ZTIMESTAMP ASC


-- =========================================

/*
    [DLU]
        04-Sep-2025
    [DATABASE FILE]
        \private\var\networkd\db\netusage.sqlite
*/

SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    ZLIVEROUTEPERF.Z_PK AS 'ZLIVEROUTEPERF.Z_PK',
    ZNETWORKATTACHMENT.Z_PK AS 'ZNETWORKATTACHMENT.Z_PK',

    datetime(ZLIVEROUTEPERF.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZLIVEROUTEPERF.ZTIMESTAMP(UTC)',
    datetime(ZNETWORKATTACHMENT.ZFIRSTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZNETWORKATTACHMENT.ZFIRSTTIMESTAMP(UTC)',
    datetime(ZNETWORKATTACHMENT.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZNETWORKATTACHMENT.ZTIMESTAMP(UTC)',

    CASE ZLIVEROUTEPERF.ZKIND
        WHEN 1 THEN '1 [WI-FI]'
        WHEN 2 THEN '2 [CELLULAR]'
        ELSE ZLIVEROUTEPERF.ZKIND
    END 'ZLIVEROUTEPERF.ZKIND',

    printf("%,d", ZLIVEROUTEPERF.ZBYTESIN) AS 'ZLIVEROUTEPERF.ZBYTESIN',
    printf("%,d", ZLIVEROUTEPERF.ZBYTESOUT) AS 'ZLIVEROUTEPERF.ZBYTESOUT',
    ZLIVEROUTEPERF.ZPACKETSIN AS 'ZLIVEROUTEPERF.ZPACKETSIN',
    ZLIVEROUTEPERF.ZPACKETSOUT AS 'ZLIVEROUTEPERF.ZPACKETSOUT',
    ZLIVEROUTEPERF.ZCONNATTEMPTS AS 'ZLIVEROUTEPERF.ZCONNATTEMPTS',
    ZLIVEROUTEPERF.ZCONNSUCCESSES AS ' ZLIVEROUTEPERF.ZCONNSUCCESSES',
    ZNETWORKATTACHMENT.ZIDENTIFIER AS 'ZNETWORKATTACHMENT.ZIDENTIFIER',
    ZNETWORKATTACHMENT.ZISKNOWNGOOD AS 'ZNETWORKATTACHMENT.ZISKNOWNGOOD',

    hex(ZNETWORKATTACHMENT.ZNETSIGNATURE) AS 'ZNETWORKATTACHMENT.ZNETSIGNATURE(HEX)',

    ZNETWORKATTACHMENT.ZOVERALLSTAYMEAN AS 'ZNETWORKATTACHMENT.ZOVERALLSTAYMEAN',
    ZNETWORKATTACHMENT.ZOVERALLSTAYVAR AS 'ZNETWORKATTACHMENT.ZOVERALLSTAYVAR',
    ZLIVEROUTEPERF.ZOVERALLSTAY AS ' ZLIVEROUTEPERF.ZOVERALLSTAY',
    ZLIVEROUTEPERF.ZOVERALLSTAYM2 AS 'ZLIVEROUTEPERF.ZOVERALLSTAYM2',

    /* Source for each line of data */
    'netusage.sqlite; Table: ZZLIVEROUTEPERF(Z_PK:' || ZLIVEROUTEPERF.Z_PK || ')' AS 'DATA_SOURCE'


FROM ZLIVEROUTEPERF
    LEFT JOIN ZNETWORKATTACHMENT ON ZLIVEROUTEPERF.ZHASNETWORKATTACHMENT = ZNETWORKATTACHMENT.Z_PK


ORDER BY
    ZLIVEROUTEPERF.ZTIMESTAMP ASC


-- =========================================


SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    ZPROCESS.Z_PK AS 'ZPROCESS.Z_PK',

    datetime(ZPROCESS.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZPROCESS.ZTIMESTAMP(UTC)',
    datetime(ZPROCESS.ZFIRSTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZPROCESS.ZFIRSTTIMESTAMP(UTC)',
    datetime(ZLIVEUSAGE.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZLIVEUSAGE.ZTIMESTAMP(UTC)',

    ZPROCESS.ZBUNDLENAME AS 'ZPROCESS.ZBUNDLENAME',
    ZPROCESS.ZPROCNAME AS 'ZPROCESS.ZPROCNAME',
    printf("%,d", ZLIVEUSAGE.ZWIFIIN) AS 'ZLIVEUSAGE.ZWIFIIN(BYTES)',
    printf("%,d", ZLIVEUSAGE.ZWIFIOUT) AS 'ZLIVEUSAGE.ZWIFIOUT(BYTES)',
    printf("%,d", ZLIVEUSAGE.ZWWANIN) AS 'ZLIVEUSAGE.ZWWANIN(BYTES)',
    printf("%,d", ZLIVEUSAGE.ZWWANOUT) AS 'ZLIVEUSAGE.ZWWANOUT(BYTES)',
    ZLIVEUSAGE.ZWIREDIN AS 'ZLIVEUSAGE.ZWIREDIN',
    ZLIVEUSAGE.ZWIREDOUT AS 'ZLIVEUSAGE.ZWIREDOUT',
    ZLIVEUSAGE.ZXIN AS 'ZLIVEUSAGE.ZXIN',
    ZLIVEUSAGE.ZXOUT AS 'ZLIVEUSAGE.ZXOUT',

    /* Source for each line of data */
    'netusage.sqlite; Table: ZLIVEUSAGE(Z_PK: ' || ZLIVEUSAGE.Z_PK || ')' AS 'DATA_SOURCE'


FROM ZLIVEUSAGE
    LEFT JOIN ZPROCESS ON ZPROCESS.Z_PK = ZLIVEUSAGE.ZHASPROCESS


WHERE
    ZPROCESS.ZBUNDLENAME LIKE '%compress%'


ORDER BY
    ZLIVEUSAGE.Z_PK ASC


-- =========================================


SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    ZPROCESS.Z_PK AS 'ZPROCESS.Z_PK',

    datetime(ZPROCESS.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZPROCESS.ZTIMESTAMP(UTC)',
    datetime(ZPROCESS.ZFIRSTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZPROCESS.ZFIRSTTIMESTAMP(UTC)',

    ZPROCESS.ZPROCNAME AS 'ZPROCESS.ZPROCNAME',
    ZPROCESS.ZBUNDLENAME AS 'ZPROCESS.ZBUNDLENAME',

    /* Source for each line of data */
    'netusage.sqlite; Table: ZPROCESS(Z_PK: ' || ZPROCESS.Z_PK || ')' AS 'DATA_SOURCE'


FROM ZPROCESS


-- WHERE
--     ZPROCESS.ZBUNDLENAME LIKE '%whisper%'


ORDER BY
    ZPROCESS.ZTIMESTAMP ASC