/*
[DLU]
    09-Mar-2026
[DATABASE FILE]
    /private/var/wireless/Library/Databases/DataUsage.sqlite
*/

SELECT

    ROW_NUMBER() OVER() AS 'RECORD-NUMBER',

    CASE
        WHEN ZLIVEUSAGE.ZTIMESTAMP IS NULL THEN '[N/A]'
        ELSE datetime(ZLIVEUSAGE.ZTIMESTAMP + 978307200, 'UNIXEPOCH')
    END AS 'LIVEUSAGE-TIMESTAMP(UTC)',

    datetime(ZPROCESS.ZFIRSTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'FIRST-TIMESTAMP(UTC)',
    datetime(ZPROCESS.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'PROCESS-TIMESTAMP(UTC)',

    ZPROCESS.ZPROCNAME AS 'PROCESS-NAME',
    ZPROCESS.ZBUNDLENAME AS 'BUNDLE-NAME',
    printf("%,d", ZLIVEUSAGE.ZWIFIIN) AS 'WIFI-BYTES-IN',
    printf("%,d", ZLIVEUSAGE.ZWIFIOUT) AS 'WIFI-BYTES-OUT',
    printf("%,d", ZLIVEUSAGE.ZWWANIN) AS 'WWAN-BYTES-IN',
    printf("%,d", ZLIVEUSAGE.ZWWANOUT) AS 'WWAN-BYTES-OUT',

    /* Source for each line of data */
    'DataUsage.sqlite; Table: ZLIVEUSAGE(Z_PK:' || ZLIVEUSAGE.Z_PK || '), ' || 'Table: ZPROCESS(Z_PK:' || ZPROCESS.Z_PK || ')' AS 'DATA-SOURCE'


FROM ZLIVEUSAGE
    LEFT JOIN ZPROCESS ON ZLIVEUSAGE.ZHASPROCESS = ZPROCESS.Z_PK


WHERE
    ZPROCESS.ZPROCNAME LIKE '%compress%' OR
    ZPROCESS.ZBUNDLENAME LIKE '%compress%'


ORDER BY
    ZLIVEUSAGE.ZTIMESTAMP ASC


-- =========================================

/*
    [DLU]
        09-Mar-2026
    [DATABASE FILE]
        \private\var\networkd\db\netusage.sqlite
*/

SELECT

    ROW_NUMBER() OVER() AS 'RECORD-NUMBER',
    ZLIVEROUTEPERF.Z_PK AS 'LIVE-ROUTE-PERF-Z_PK',
    ZNETWORKATTACHMENT.Z_PK AS 'NETWORK-ATTACHMENT-Z_PK',

    datetime(ZLIVEROUTEPERF.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'TIMESTAMP(UTC)',
    datetime(ZNETWORKATTACHMENT.ZFIRSTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'FIRST-TIMESTAMP(UTC)',
    datetime(ZNETWORKATTACHMENT.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'TIMESTAMP(UTC)',

    CASE ZLIVEROUTEPERF.ZKIND
        WHEN 1 THEN '1 [WI-FI]'
        WHEN 2 THEN '2 [CELLULAR]'
        ELSE ZLIVEROUTEPERF.ZKIND
    END 'LIVE-ROUTE-PERF-KIND',

    printf("%,d", ZLIVEROUTEPERF.ZBYTESIN) AS 'BYTES-IN',
    printf("%,d", ZLIVEROUTEPERF.ZBYTESOUT) AS 'BYTES-OUT',
    ZLIVEROUTEPERF.ZPACKETSIN AS 'PACKETS-IN',
    ZLIVEROUTEPERF.ZPACKETSOUT AS 'PACKETS-OUT',
    ZLIVEROUTEPERF.ZCONNATTEMPTS AS 'CONN-ATTEMPTS',
    ZLIVEROUTEPERF.ZCONNSUCCESSES AS 'CONN-SUCCESSES',
    ZNETWORKATTACHMENT.ZIDENTIFIER AS 'IDENTIFIER',
    ZNETWORKATTACHMENT.ZISKNOWNGOOD AS 'IS-KNOWN-GOOD',

    hex(ZNETWORKATTACHMENT.ZNETSIGNATURE) AS 'NET-SIGNATURE(HEX)',

    ZNETWORKATTACHMENT.ZOVERALLSTAYMEAN AS 'OVERALL-STAY-MEAN',
    ZNETWORKATTACHMENT.ZOVERALLSTAYVAR AS 'OVERALL-STAY-VAR',
    ZLIVEROUTEPERF.ZOVERALLSTAY AS 'OVERALL-STAY',
    ZLIVEROUTEPERF.ZOVERALLSTAYM2 AS 'OVERALL-STAY-M2',

    /* Source for each line of data */
    'netusage.sqlite; Table: ZZLIVEROUTEPERF(Z_PK:' || ZLIVEROUTEPERF.Z_PK || ')' AS 'DATA-SOURCE'


FROM ZLIVEROUTEPERF
    LEFT JOIN ZNETWORKATTACHMENT ON ZLIVEROUTEPERF.ZHASNETWORKATTACHMENT = ZNETWORKATTACHMENT.Z_PK


ORDER BY
    ZLIVEROUTEPERF.ZTIMESTAMP ASC


-- =========================================


SELECT

    ROW_NUMBER() OVER() AS 'RECORD-NUMBER',
    ZPROCESS.Z_PK AS 'ZPROCESS-Z_PK',

    datetime(ZPROCESS.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'PROCESS-TIMESTAMP(UTC)',
    datetime(ZPROCESS.ZFIRSTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'PROCESS-FIRST-TIMESTAMP(UTC)',
    datetime(ZLIVEUSAGE.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'LIVEUSAGE-TIMESTAMP(UTC)',

    ZPROCESS.ZBUNDLENAME AS 'BUNDLE-NAME',
    ZPROCESS.ZPROCNAME AS 'PROC-NAME',
    printf("%,d", ZLIVEUSAGE.ZWIFIIN) AS 'WIFI-BYTES-IN',
    printf("%,d", ZLIVEUSAGE.ZWIFIOUT) AS 'WIFI-BYTES-OUT',
    printf("%,d", ZLIVEUSAGE.ZWWANIN) AS 'WWAN-BYTES-IN',
    printf("%,d", ZLIVEUSAGE.ZWWANOUT) AS 'WWAN-BYTES-OUT',
    ZLIVEUSAGE.ZWIREDIN AS 'WIRED-BYTES-IN',
    ZLIVEUSAGE.ZWIREDOUT AS 'WIRED-BYTES-OUT',
    ZLIVEUSAGE.ZXIN AS 'X-IN',
    ZLIVEUSAGE.ZXOUT AS 'X-OUT',

    /* Source for each line of data */
    'netusage.sqlite; Table: ZLIVEUSAGE(Z_PK: ' || ZLIVEUSAGE.Z_PK || ')' AS 'DATA-SOURCE'


FROM ZLIVEUSAGE
    LEFT JOIN ZPROCESS ON ZPROCESS.Z_PK = ZLIVEUSAGE.ZHASPROCESS


WHERE
    ZPROCESS.ZBUNDLENAME LIKE '%compress%'


ORDER BY
    ZLIVEUSAGE.Z_PK ASC


-- =========================================


SELECT

    ROW_NUMBER() OVER() AS 'RECORD-NUMBER',
    ZPROCESS.Z_PK AS 'ZPROCESS-Z_PK',

    datetime(ZPROCESS.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'TIMESTAMP(UTC)',
    datetime(ZPROCESS.ZFIRSTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'FIRST-TIMESTAMP(UTC)',

    ZPROCESS.ZPROCNAME AS 'PROC-NAME',
    ZPROCESS.ZBUNDLENAME AS 'BUNDLE-NAME',

    /* Source for each line of data */
    'netusage.sqlite; Table: ZPROCESS(Z_PK: ' || ZPROCESS.Z_PK || ')' AS 'DATA-SOURCE'


FROM ZPROCESS


-- WHERE
--     ZPROCESS.ZBUNDLENAME LIKE '%whisper%'


ORDER BY
    ZPROCESS.ZTIMESTAMP ASC