SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    ZPROCESS.Z_PK AS 'ZPROCESS_Z_PK',

    datetime(ZPROCESS.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'PROCESS_TIMESTAMP_utc',
    datetime(ZPROCESS.ZFIRSTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'PROCESS_FIRST_TIMESTAMP_utc',
    datetime(ZLIVEUSAGE.ZTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'LIVEUSAGE_TIMESTAMP_utc',

    ZPROCESS.ZBUNDLENAME AS 'BUNDLE_NAME',
    ZPROCESS.ZPROCNAME AS 'PROC_NAME',
    printf("%,d", ZLIVEUSAGE.ZWIFIIN) AS 'WIFI_BYTES_IN',
    printf("%,d", ZLIVEUSAGE.ZWIFIOUT) AS 'WIFI_BYTES_OUT',
    printf("%,d", ZLIVEUSAGE.ZWWANIN) AS 'WWAN_BYTES_IN',
    printf("%,d", ZLIVEUSAGE.ZWWANOUT) AS 'WWAN_BYTES_OUT',
    ZLIVEUSAGE.ZWIREDIN AS 'WIRED_BYTES_IN',
    ZLIVEUSAGE.ZWIREDOUT AS 'WIRED_BYTES_OUT',
    ZLIVEUSAGE.ZXIN AS 'X_IN',
    ZLIVEUSAGE.ZXOUT AS 'X_OUT',

    /* Source for each line of data */
    'netusage.sqlite; Table:ZLIVEUSAGE(Z_PK: ' || ZLIVEUSAGE.Z_PK || ')' AS 'DATA_SOURCE'


FROM ZLIVEUSAGE
    LEFT JOIN ZPROCESS ON ZPROCESS.Z_PK = ZLIVEUSAGE.ZHASPROCESS


WHERE
    ZPROCESS.ZBUNDLENAME LIKE '%compress%'


ORDER BY
    ZLIVEUSAGE.Z_PK ASC