
SELECT

    ROW_NUMBER() OVER() AS 'record_number',

    ZWAADDRESSBOOKCONTACT.Z_PK AS 'ZWAADDRESSBOOKCONTACT.z_pk',
    ZWAADDRESSBOOKCONTACT.ZGIVENNAME AS 'ZWAADDRESSBOOKCONTACT.zgivenname',
    ZWAADDRESSBOOKCONTACT.ZHIGHLIGHTEDNAME AS 'ZWAADDRESSBOOKCONTACT.zhighlightedname',
    ZWAADDRESSBOOKCONTACT.ZFULLNAME AS 'ZWAADDRESSBOOKCONTACT.zfullname',
    ZWAADDRESSBOOKCONTACT.ZABOUTTEXT AS 'ZWAADDRESSBOOKCONTACT.zabouttext',

    datetime(ZWAADDRESSBOOKCONTACT.ZABOUTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZWAADDRESSBOOKCONTACT.zabouttimestamp(utc)',

    ZWAADDRESSBOOKCONTACT.ZPHONENUMBER AS 'ZWAADDRESSBOOKCONTACT.zphonenumber',

    CASE ZWAADDRESSBOOKCONTACT.ZPHONENUMBERLABEL
        WHEN '_$!<Work>!$_' THEN 'Work'
        WHEN '_$!<Mobile>!$_' THEN 'Mobile'
        WHEN '_$!<Home>!$_' THEN 'Home'
        WHEN '_$!<Other>!$_' THEN 'Other'
        ELSE ZWAADDRESSBOOKCONTACT.ZPHONENUMBERLABEL
    END AS 'ZWAADDRESSBOOKCONTACT.zphonenumberlabel',

    ZWAADDRESSBOOKCONTACT.ZWHATSAPPID AS 'ZWAADDRESSBOOKCONTACT.zwhatsappid'


FROM ZWAADDRESSBOOKCONTACT


ORDER BY
    ZWAADDRESSBOOKCONTACT.Z_PK ASC
