
SELECT

    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    ZWAADDRESSBOOKCONTACT.Z_PK AS 'ZWAADDRESSBOOKCONTACT.Z_PK',
    ZWAADDRESSBOOKCONTACT.ZGIVENNAME AS 'ZWAADDRESSBOOKCONTACT.ZGIVENNAME',
    ZWAADDRESSBOOKCONTACT.ZHIGHLIGHTEDNAME AS 'ZWAADDRESSBOOKCONTACT.ZHIGHLIGHTEDNAME',
    ZWAADDRESSBOOKCONTACT.ZFULLNAME AS 'ZWAADDRESSBOOKCONTACT.ZFULLNAME',
    ZWAADDRESSBOOKCONTACT.ZABOUTTEXT AS 'ZWAADDRESSBOOKCONTACT.ZABOUTTEXT',

    datetime(ZWAADDRESSBOOKCONTACT.ZABOUTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZWAADDRESSBOOKCONTACT.ZABOUTTIMESTAMP(UTC)',

    ZWAADDRESSBOOKCONTACT.ZPHONENUMBER AS 'ZWAADDRESSBOOKCONTACT.ZPHONENUMBER',

    CASE ZWAADDRESSBOOKCONTACT.ZPHONENUMBERLABEL
        WHEN '_$!<Work>!$_' THEN 'Work'
        WHEN '_$!<Mobile>!$_' THEN 'Mobile'
        WHEN '_$!<Home>!$_' THEN 'Home'
        WHEN '_$!<Other>!$_' THEN 'Other'
        ELSE ZWAADDRESSBOOKCONTACT.ZPHONENUMBERLABEL
    END AS 'ZWAADDRESSBOOKCONTACT.ZPHONENUMBERLABEL',

    ZWAADDRESSBOOKCONTACT.ZWHATSAPPID AS 'ZWAADDRESSBOOKCONTACT.ZWHATSAPPID'


FROM ZWAADDRESSBOOKCONTACT


ORDER BY
    ZWAADDRESSBOOKCONTACT.Z_PK ASC
