/*
  DLU = 01-Aug-2025
*/

SELECT

    ROW_NUMBER() OVER () AS 'RECORD_NUMBER',
    ZASSET.Z_PK AS 'ZASSET.Z_PK',
    ZGENERICALBUM.ZTITLE AS 'ZGENERICALBUM.ZTITLE',
    ZASSET.ZDIRECTORY AS 'ZASSET.ZDIRECTORY',
    ZASSET.ZFILENAME AS 'ZASSET.ZFILENAME',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALFILENAME AS 'ZADDITIONALASSETATTRIBUTES.ZORIGINALFILENAME',
    ZASSET.ZUNIFORMTYPEIDENTIFIER AS 'ZASSET.ZUNIFORMTYPEIDENTIFIER',
    ZADDITIONALASSETATTRIBUTES.ZIMPORTEDBYBUNDLEIDENTIFIER AS 'ZADDITIONALASSETATTRIBUTES.ZIMPORTEDBYBUNDLEIDENTIFIER',

    CASE ZASSET.ZFAVORITE
        WHEN 0 THEN '0 [No]'
        WHEN 1 THEN '1 [Yes]'
        ELSE ZASSET.ZFAVORITE
    END AS 'ZASSET.ZFAVORITE',

    CASE ZASSET.ZHIDDEN
        WHEN 0 THEN '0 [Not Hidden]'
        WHEN 1 THEN '1 [Hidden]'
        ELSE ZASSET.ZHIDDEN
    END AS 'ZASSET.ZHIDDEN',

    datetime(ZASSET.ZDATECREATED + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZDATECREATED(UTC)',
    datetime(ZASSET.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZMODIFICATIONDATE(UTC)',
    datetime(ZASSET.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZADDEDDATE(UTC)',

    CASE ZASSET.ZTRASHEDSTATE
        WHEN 0 THEN '0 [Not In Trash]'
        WHEN 1 THEN '1 [In Trash]'
        ELSE ZASSET.ZTRASHEDSTATE
    END AS 'ZASSET.ZTRASHEDSTATE',

    CASE
        WHEN ZASSET.ZTRASHEDDATE IS NULL THEN '[N/A]'
        ELSE datetime(ZASSET.ZTRASHEDDATE + 978307200, 'UNIXEPOCH')
    END AS 'ZASSET.ZTRASHEDDATE(UTC)',


    CASE ZASSET.ZLATITUDE
        WHEN -180.0 THEN '[N/A]'
        ELSE ZASSET.ZLATITUDE
    END 'ZASSET.ZLATITUDE',

    CASE ZASSET.ZLONGITUDE
        WHEN -180.0 THEN '[N/A]'
        ELSE ZASSET.ZLONGITUDE
    END 'ZASSET.ZLONGITUDE'


FROM ZASSET
    JOIN ZADDITIONALASSETATTRIBUTES ON ZASSET.ZADDITIONALATTRIBUTES = ZADDITIONALASSETATTRIBUTES.Z_PK
    LEFT JOIN Z_29ASSETS ON ZASSET.Z_PK = Z_29ASSETS.Z_3ASSETS
    LEFT JOIN ZGENERICALBUM ON ZGENERICALBUM.Z_PK = Z_29ASSETS.Z_29ALBUMS


WHERE
    ZASSET.ZHIDDEN IS "1"


ORDER BY ZGENERICALBUM.Z_PK