/*
[DLU]
    05-Sep-2025

[NOTES]
    Parts of query copied from:  https://github.com/ScottKjr3347/iOS_SWY_PL_Photos.sqlite_Queries/blob/main/iOS17/iOS17_SWY-PL_Phsql_LargeReference.txt

    Blog Link:  https://theforensicscooter.com/2022/09/16/shared-with-you-syndication-photo-library-message-attachments-linked-assets/#_Toc114172924

    This query is for the Shared With You (SWY) Syndication Photo Library (PL) Photos.sqlite database.

Database location:
    /private/var/mobile/Library/Photos/Libraries/Syndication.photoslibrary/database/Photos.sqlite
*/

SELECT

    /* Add a row number at the beggining of each row */
    ROW_NUMBER() OVER() AS 'ROW_NUMBER',
    ZASSET.Z_PK AS 'ZASSET.Z_PK',
    --ZASSET.ZADDITIONALATTRIBUTES AS 'AddAttributesKey',
    --ZDETECTEDFACE.ZASSETFORFACE AS 'DetectedFaceAsset',

    CASE ZASSET.ZKIND
        WHEN 0 THEN '0 [Photo]'
        WHEN 1 THEN '1 [Video]'
        ELSE 'Unknown Value: ' || ZASSET.ZKIND
    END AS 'ZASSET.ZKIND',

    ZASSET.ZUNIFORMTYPEIDENTIFIER AS 'ZASSET.ZUNIFORMTYPEIDENTIFIER',

    datetime(ZASSET.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZADDEDDATE(UTC)',

    ZASSET.ZFILENAME AS 'ZASSET.ZFILENAME',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALFILENAME AS 'ZADDITIONALASSETATTRIBUTES.ZORIGINALFILENAME',

    datetime(ZASSET.ZDATECREATED + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZDATECREATED(UTC)',
    datetime(ZASSET.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZMODIFICATIONDATE(UTC)',

    -- The EXIF data is stored in the device local time at the time of capture/creation
    ZADDITIONALASSETATTRIBUTES.ZEXIFTIMESTAMPSTRING AS 'ZADDITIONALASSETATTRIBUTES.ZEXIFTIMESTAMPSTRING',

    CASE ZASSET.ZSYNDICATIONSTATE
        WHEN 0 THEN '0 [Received SWY_Synd_Asset]'
        WHEN 1 THEN '1 [Sent SWY_Synd_Asset]'
        WHEN 2 THEN '2 [Manually Saved_SWY_Synd_Asset]'
        WHEN 3 THEN '3 [STILLTESTING_Sent-SWY]'
        WHEN 8 THEN '8 [SWY_Linked_Asset_was_Visible_On-Device_User_Deleted_Link]'
        WHEN 9 THEN '9 [STILLTESTING_Sent_SWY]'
        WHEN 10 THEN '10 [Manually-Saved_SWY_Synd_Asset_User_Deleted_From_LPL]'
        ELSE 'Unknown Value: ' || zAsset.ZSYNDICATIONSTATE
    END AS 'ZASSET.ZSYNDICATIONSTATE',

    datetime(ZADDITIONALASSETATTRIBUTES.ZSCENEANALYSISTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZADDITIONALASSETATTRIBUTES.ZSCENEANALYSISTIMESTAMP(UTC)',

    datetime(ZASSET.ZANALYSISSTATEMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZANALYSISSTATEMODIFICATIONDATE(UTC)',

    CASE ZASSET.ZHASADJUSTMENTS
        WHEN 0 THEN '0 [No]'
        WHEN 1 THEN '1 [Yes]'
        ELSE 'Unknown Value: ' || ZASSET.ZHASADJUSTMENTS
    END AS 'ZASSET.ZHASADJUSTMENTS',

    datetime(ZASSET.ZADJUSTMENTTIMESTAMP + 978307200, 'UNIXEPOCH')  AS 'ZASSET.ZADJUSTMENTTIMESTAMP(UTC)',

    CASE
        WHEN ZGENERICALBUM.ZTITLE IS NULL THEN '[N/A]'
        ELSE ZGENERICALBUM.ZTITLE
    END AS 'ZGENERICALBUM.ZTITLE',

    ZADDITIONALASSETATTRIBUTES.ZCREATORBUNDLEID AS 'ZADDITIONALASSETATTRIBUTES.ZCREATORBUNDLEID',
    ZADDITIONALASSETATTRIBUTES.ZIMPORTEDBYBUNDLEIDENTIFIER AS 'ZADDITIONALASSETATTRIBUTES.ZIMPORTEDBYBUNDLEIDENTIFIER',

    /*
    This column can correlate to the `guid` column in the `message` table of the
    sms.db file.  This can tell what message a given image was associated with.

    The ZSYNDICATIONIDENTIFIER will have the following format:
        at_0_B2F67B26-592F-4551-8D0C-9CFBC15653F4
        -- `at` indicates the item\asset is from within Apple Messages application
            or was an attachment to a message.

    The first number between the underscores indicates how many images were sent
    as part of that message -- counting begins at "0" -- so, in the example above,
    one (1) image was sent with this message (if the number were "1", that would
    indicate that two files were attached to the message).  The ID formatted as:
    8-4-4-4-12 is the message GUID from the sms.db file.
    */
    ZADDITIONALASSETATTRIBUTES.ZSYNDICATIONIDENTIFIER AS 'ZADDITIONALASSETATTRIBUTES.ZSYNDICATIONIDENTIFIER',

    CASE
        WHEN ZADDITIONALASSETATTRIBUTES.ZEDITORBUNDLEID IS NULL THEN '[N/A]'
        ELSE ZADDITIONALASSETATTRIBUTES.ZEDITORBUNDLEID
    END AS 'ZADDITIONALASSETATTRIBUTES.ZEDITORBUNDLEID',

    ZASSET.ZDIRECTORY AS 'ZASSET.ZDIRECTORY',

    CASE ZASSET.ZSAVEDASSETTYPE
        WHEN 0 THEN '0 [Saved via other source]'
        WHEN 1 THEN '1 [Still Testing]'
        WHEN 2 THEN '2 [Still Testing]'
        WHEN 3 THEN '3 [SWY Syndicaion PL Asset NoAuto Display In LPL]'
        WHEN 4 THEN '4 [Photo Cloud Sharing Data Asset]'
        WHEN 5 THEN '5 [Still Testing]'
        WHEN 6 THEN '6 [Cloud Photo Library Asset]'
        WHEN 7 THEN '7 [Still Testing]'
        WHEN 8 THEN '8 [iCloudLink CloudMasterMomentAsset]'
        WHEN 12 THEN '12 [SWY Syndicaion PL Asset Auto Display In LPL]'
        ELSE 'Unknown Value: ' || zAsset.ZSAVEDASSETTYPE
    END AS 'SavedAssetType',

    CASE
        WHEN ZASSET.ZFACEAREAPOINTS > 0 THEN 'Yes'
        ELSE 'N/A (' || ZASSET.ZFACEAREAPOINTS || ')'
    END AS 'ZASSET.ZFACEAREAPOINTS',

    ZPERSON.ZDISPLAYNAME AS 'ZPERSON.ZDISPLAYNAME',
    ZPERSON.ZFULLNAME AS 'ZPERSON.ZFULLNAME',
    ZPERSON.ZFACECOUNT AS 'ZPERSON.ZFACECOUNT',
    ZDETECTEDFACE.ZPERSONFORFACE AS 'ZDETECTEDFACE.ZPERSONFORFACE',
    ZPERSON.ZCONTACTMATCHINGDICTIONARY AS 'ZPERSON.ZCONTACTMATCHINGDICTIONARY',
    ZPERSON.ZPERSONUUID AS 'ZPERSON.ZPERSONUUID',
    ZDETECTEDFACE.ZQUALITYMEASURE AS 'ZDETECTEDFACE.ZQUALITYMEASURE',

    CASE ZDETECTEDFACE.ZAGETYPE
        WHEN 1 THEN '1 [Baby/Toddler]'
        WHEN 2 THEN '2 [Baby/Toddler]'
        WHEN 3 THEN '3 [Child/YoungAdult]'
        WHEN 4 THEN '4 [YoungAdult/Adult]'
        WHEN 5 THEN '5 [Adult]'
        ELSE 'Unknown Value: ' || ZDETECTEDFACE.ZAGETYPE
    END AS 'ZDETECTEDFACE.ZAGETYPE',

    CASE ZDETECTEDFACE.ZGENDERTYPE
        WHEN 1 THEN '1 [Male]'
        WHEN 2 THEN '2 [Female]'
        ELSE 'Unknown Value: ' || ZDETECTEDFACE.ZGENDERTYPE
    END AS 'ZDETECTEDFACE.ZGENDERTYPE',

    CASE ZDETECTEDFACE.ZGLASSESTYPE
        WHEN 1 THEN '1 [Eye]'
        WHEN 2 THEN '2 [Sun]'
        WHEN 3 THEN '3 [None]'
        ELSE 'Unknown Value: ' || ZDETECTEDFACE.ZGLASSESTYPE
    END AS 'ZDETECTEDFACE.ZGLASSESTYPE',

    CASE ZDETECTEDFACE.ZFACIALHAIRTYPE
        WHEN 1 THEN '1 [None]'
        WHEN 2 THEN '2 [Beard/Mustache]'
        WHEN 3 THEN '3 [Goatee]'
        WHEN 5 THEN '5 [Stubble]'
        ELSE 'Unknown Value: ' || ZDETECTEDFACE.ZFACIALHAIRTYPE
    END AS 'ZDETECTEDFACE.ZFACIALHAIRTYPE',

    CASE ZDETECTEDFACE.ZHAIRTYPE
        WHEN 2 THEN '2 [Bald]'
        WHEN 3 THEN '3 [NotBald]'
        ELSE 'Unknown Value: ' || ZDETECTEDFACE.ZHAIRTYPE
    END AS 'ZDETECTEDFACE.ZHAIRTYPE',

    ZASSET.ZORIGINALCOLORSPACE AS 'ZASSET.ZORIGINALCOLORSPACE',
    ZASSET.ZDURATION AS 'ZASSET.ZDURATION(sec)',
    ZASSET.ZVIDEOCPDURATIONVALUE AS 'ZASSET.ZVIDEOCPDURATIONVALUE',

    CASE ZASSET.ZCOMPLETE
        WHEN 1 THEN '1 [Yes]'
        ELSE 'Unknown Value: ' || ZASSET.ZCOMPLETE
    END AS 'ZASSET.ZCOMPLETE',

    CASE ZASSET.ZVISIBILITYSTATE
        WHEN 0 THEN '0 [Visible]'
        WHEN 1 THEN '1 [PhotoStreamsData]'
        WHEN 2 THEN '2 [Burst]'
        ELSE 'Unknown Value: ' || ZASSET.ZVISIBILITYSTATE
    END AS 'ZASSET.ZVISIBILITYSTATE',

    CASE ZASSET.ZFAVORITE
        WHEN 0 THEN '0 [No]'
        WHEN 1 THEN '1 [Yes]'
        ELSE 'Unknown Value: ' || ZASSET.ZFAVORITE
    END AS 'ZASSET.ZFAVORITE',

    CASE ZASSET.ZHIDDEN
        WHEN 0 THEN '0 [Not Hidden]'
        WHEN 1 THEN '1 [Hidden]'
        ELSE 'Unknown Value: ' || ZASSET.ZHIDDEN
    END AS 'ZASSET.ZHIDDEN',

    CASE ZASSET.ZTRASHEDSTATE
        WHEN 0 THEN '0 [Not In Trash]'
        WHEN 1 THEN '1 [In Trash]'
        ELSE 'Unknown Value: ' || ZASSET.ZTRASHEDSTATE
    END AS 'ZASSET.ZTRASHEDSTATE',

    CASE
        WHEN ZASSET.ZTRASHEDDATE IS NULL THEN '[N/A]'
        ELSE datetime(ZASSET.ZTRASHEDDATE + 978307200, 'UNIXEPOCH')
    END AS 'ZASSET.ZTRASHEDDATE(UTC)',

    ZADDITIONALASSETATTRIBUTES.ZVIEWCOUNT AS 'ZADDITIONALASSETATTRIBUTES.ZVIEWCOUNT',
    ZADDITIONALASSETATTRIBUTES.ZPLAYCOUNT AS 'ZADDITIONALASSETATTRIBUTES.ZPLAYCOUNT',
    ZADDITIONALASSETATTRIBUTES.ZSHARECOUNT AS 'ZADDITIONALASSETATTRIBUTES.ZSHARECOUNT',

    datetime(ZASSET.ZLASTSHAREDDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZLASTSHAREDDATE(UTC)',

    printf("%,d", ZADDITIONALASSETATTRIBUTES.ZORIGINALFILESIZE) AS 'ZADDITIONALASSETATTRIBUTES.ZORIGINALFILESIZE(bytes)',
    ZASSET.ZHEIGHT AS 'ZASSET.ZHEIGHT(px)',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALHEIGHT AS 'ZADDITIONALASSETATTRIBUTES.ZORIGINALHEIGHT',
    ZASSET.ZWIDTH AS 'ZASSET.ZWIDTH(px)',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALWIDTH AS 'ZADDITIONALASSETATTRIBUTES.ZORIGINALWIDTH',
    ZADDITIONALASSETATTRIBUTES.ZCAMERACAPTUREDEVICE AS 'ZADDITIONALASSETATTRIBUTES.ZCAMERACAPTUREDEVICE',

    CASE ZASSET.ZORIENTATION
        WHEN 1 THEN '1 [Horizontal (Left)]'
        WHEN 3 THEN '3 [Horizontal (Right)]'
        WHEN 6 THEN '6 [Vertical (Up)]'
        WHEN 8 THEN '8 [Vertical (Down)]'
        ELSE 'Unknown Value: ' || ZASSET.ZORIENTATION
    END AS 'ZASSET.ZORIENTATION',

    CASE ZADDITIONALASSETATTRIBUTES.ZORIGINALORIENTATION
        WHEN 1 THEN '1 [Horizontal (Left)]'
        WHEN 3 THEN '3 [Horizontal (Right)]'
        WHEN 6 THEN '6 [Vertical (Up)]'
        WHEN 8 THEN '8 [Vertical (Down)]'
        ELSE 'Unknown Value: ' || ZASSET.ZORIENTATION
    END AS 'ZADDITIONALASSETATTRIBUTES.ZORIGINALORIENTATION',

    ZADDITIONALASSETATTRIBUTES.ZTIMEZONENAME AS 'ZADDITIONALASSETATTRIBUTES.ZTIMEZONENAME',
    ZADDITIONALASSETATTRIBUTES.ZTIMEZONEOFFSET AS 'ZADDITIONALASSETATTRIBUTES.ZTIMEZONEOFFSET',
    ZADDITIONALASSETATTRIBUTES.ZINFERREDTIMEZONEOFFSET AS 'ZADDITIONALASSETATTRIBUTES.ZINFERREDTIMEZONEOFFSET',
    ZASSET.ZLOCATIONDATA AS 'ZASSET.ZLOCATIONDATA',

    CASE ZASSET.ZLATITUDE
        WHEN -180.0 THEN '[-180.0]'
        ELSE ZASSET.ZLATITUDE
    END 'ZASSET.ZLATITUDE',

    CASE ZASSET.ZLONGITUDE
        WHEN -180.0 THEN '[-180.0]'
        ELSE ZASSET.ZLONGITUDE
    END 'ZASSET.ZLONGITUDE',

    CASE ZADDITIONALASSETATTRIBUTES.ZSHIFTEDLOCATIONISVALID
        WHEN 0 THEN '0 [No]'
        WHEN 1 THEN '1 [Yes]'
        ELSE 'Unknown Value: ' || ZADDITIONALASSETATTRIBUTES.ZSHIFTEDLOCATIONISVALID
    END AS 'ZADDITIONALASSETATTRIBUTES.ZSHIFTEDLOCATIONISVALID',

    CASE ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATAISVALID
        WHEN 0 THEN '0 [No]'
        WHEN 1 THEN '1 [Yes]'
        ELSE 'Unknown Value: ' || ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATAISVALID
    END AS 'ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATAISVALID',

    ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATA AS 'ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATA',
    ZASSET.ZTHUMBNAILINDEX AS 'ZASSET.ZTHUMBNAILINDEX',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILWIDTH AS 'ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILWIDTH',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILHEIGHT AS 'ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILHEIGHT',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILOFFSET AS 'ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILOFFSET',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILLENGTH AS 'ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILLENGTH',
    ZASSET.ZMOMENT AS 'ZASSET.ZMOMENT',
    ZMOMENT.ZTITLE AS 'ZMOMENT.ZTITLE',

    datetime(ZMOMENT.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'ZMOMENT.ZSTARTDATE(UTC)',
    datetime(ZMOMENT.ZREPRESENTATIVEDATE + 978307200, 'UNIXEPOCH') AS 'ZMOMENT.ZREPRESENTATIVEDATE(UTC)',
    datetime(ZMOMENT.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'ZMOMENT.ZMODIFICATIONDATE(UTC)',
    datetime(ZMOMENT.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'ZMOMENT.ZENDDATE(UTC)',

    CASE ZMOMENT.ZAPPROXIMATELATITUDE
        WHEN -180.0 THEN '[-180.0]'
        ELSE ZMOMENT.ZAPPROXIMATELATITUDE
    END AS 'ZMOMENT.ZAPPROXIMATELATITUDE',

    CASE ZMOMENT.ZAPPROXIMATELONGITUDE
        WHEN -180.0 THEN '[-180.0]'
        ELSE ZMOMENT.ZAPPROXIMATELONGITUDE
    END AS 'ZMOMENT.ZAPPROXIMATELONGITUDE',

    ZASSET.ZUUID AS 'ZASSET.ZUUID',
    ZASSET.ZMEDIAGROUPUUID AS 'ZASSET.ZMEDIAGROUPUUID',
    ZASSET.ZCLOUDASSETGUID AS 'ZASSET.ZCLOUDASSETGUID',
    ZADDITIONALASSETATTRIBUTES.ZPUBLICGLOBALUUID AS 'ZADDITIONALASSETATTRIBUTES.ZPUBLICGLOBALUUID',
    -- ZADDITIONALASSETATTRIBUTES.ZMASTERFINGERPRINT AS 'MasterFingerprint',
    -- ZADDITIONALASSETATTRIBUTES.ZADJUSTEDFINGERPRINT AS 'AdjustedFingerprint',

    /* Source for each line of data */
    -- /SWY PHOTO LIBRARY/
    '/private/var/mobile/Library/Photos/Libraries/Syndication.photoslibrary/database/Photos.sqlite; ZASSET(Z_PK:' || ZASSET.Z_PK || ')' AS 'DATA_SOURCE'


FROM ZASSET
    LEFT JOIN ZMOMENT ON ZASSET.ZMOMENT = ZMOMENT.Z_PK
    JOIN ZADDITIONALASSETATTRIBUTES ON ZASSET.ZADDITIONALATTRIBUTES = ZADDITIONALASSETATTRIBUTES.Z_PK
    LEFT JOIN ZDETECTEDFACE ON ZADDITIONALASSETATTRIBUTES.ZASSET = ZDETECTEDFACE.ZASSETFORFACE
    LEFT JOIN ZPERSON ON ZPERSON.Z_PK = ZDETECTEDFACE.ZPERSONFORFACE
    LEFT JOIN Z_30ASSETS ON ZASSET.Z_PK = Z_30ASSETS.Z_3ASSETS
    LEFT JOIN ZGENERICALBUM ON ZGENERICALBUM.Z_PK = Z_30ASSETS.Z_30ALBUMS


--WHERE ZADDITIONALASSETATTRIBUTES.ZIMPORTEDBYBUNDLEIDENTIFIER IS 'com.apple.FileProvider.LocalStorage'


ORDER BY ZASSET.Z_PK ASC