/*
    [DLU]
        01-Aug-2025
    [DATABASE PATH]
        /private/var/mobile/Media/PhotoData/Photos.sqlite
*/

SELECT

    ROW_NUMBER() OVER () AS 'RecordNumber',
    ZASSET.Z_PK AS 'Z_PK',
    ZGENERICALBUM.ZTITLE AS 'AlbumTitle',
    ZASSET.ZDIRECTORY AS 'Directory',
    ZASSET.ZFILENAME AS 'FileName',
    CONCAT(ZASSET.ZDIRECTORY, '/', ZASSET.ZFILENAME) AS 'FilePath',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALFILENAME AS 'OriginalFileName',
    ZASSET.ZUNIFORMTYPEIDENTIFIER AS 'UniformTypeIdentifier',
    ZADDITIONALASSETATTRIBUTES.ZIMPORTEDBYBUNDLEIDENTIFIER AS 'ImportedByBundleIdentifier',

    CASE ZASSET.ZFAVORITE
        WHEN 0 THEN '0 [No]'
        WHEN 1 THEN '1 [Yes]'
        ELSE 'Unknown Value: ' || ZASSET.ZFAVORITE
    END AS 'IsFavorite',

    CASE ZASSET.ZHIDDEN
        WHEN 0 THEN '0 [Not Hidden]'
        WHEN 1 THEN '1 [Hidden]'
        ELSE 'Unknown Value: ' || ZASSET.ZHIDDEN
    END AS 'IsHidden',

    datetime(ZASSET.ZDATECREATED + 978307200, 'UNIXEPOCH') AS 'DateCreated(UTC)',
    datetime(ZASSET.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'ModificationDate(UTC)',
    datetime(ZASSET.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'DateAdded(UTC)',

    CASE ZASSET.ZTRASHEDSTATE
        WHEN 0 THEN '0 [Not In Trash]'
        WHEN 1 THEN '1 [In Trash]'
        ELSE 'Unknown Value: ' || ZASSET.ZTRASHEDSTATE
    END AS 'TrashedState',

    CASE
        WHEN ZASSET.ZTRASHEDDATE IS NULL THEN '[N/A]'
        ELSE datetime(ZASSET.ZTRASHEDDATE + 978307200, 'UNIXEPOCH')
    END AS 'TrashedDate(UTC)',

    CASE ZASSET.ZLATITUDE
        WHEN -180.0 THEN '[-180.0]'
        ELSE ZASSET.ZLATITUDE
    END 'Latitude',

    CASE ZASSET.ZLONGITUDE
        WHEN -180.0 THEN '[-180.0]'
        ELSE ZASSET.ZLONGITUDE
    END 'Longitude',

    /* Source for each line of data */
    'Photos.sqlite; ZASSET(Z_PK:' || ZASSET.Z_PK || ')' AS 'DataSource'


FROM ZASSET
    JOIN ZADDITIONALASSETATTRIBUTES ON ZASSET.ZADDITIONALATTRIBUTES = ZADDITIONALASSETATTRIBUTES.Z_PK
    LEFT JOIN Z_30ASSETS ON ZASSET.Z_PK = Z_30ASSETS.Z_3ASSETS
    LEFT JOIN ZGENERICALBUM ON ZGENERICALBUM.Z_PK = Z_30ASSETS.Z_30ALBUMS


-- WHERE
--     ZASSET.ZHIDDEN IS "1"


ORDER BY ZGENERICALBUM.Z_PK ASC