/*
DLU = 16-Jul-2025
*/

SELECT

    ROW_NUMBER() OVER () AS 'RowNo.',
    ZASSET.Z_PK AS 'ZASSET.Z_PK',
    ZASSET.ZEXTENDEDATTRIBUTES AS 'ZASSET.ZEXTENDEDATTRIBUTES',
    ZASSET.ZCONVERSATION AS 'ZASSET.ZCONVERSATION',
    ZASSET.ZMOMENT AS 'ZASSET.ZMOMENT',
    ZASSET.ZDIRECTORY AS 'ZASSET.ZDIRECTORY',
    ZASSET.ZFILENAME AS 'ZASSET.ZFILENAME',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALFILENAME AS 'ZADDITIONALASSETATTRIBUTES.ZORIGINALFILENAME',
    ZASSET.ZUNIFORMTYPEIDENTIFIER AS 'ZASSET.ZUNIFORMTYPEIDENTIFIER',
    ZASSET.ZUUID AS 'ZASSET.ZUUID',

    CASE ZASSET.ZKIND
        WHEN 0 THEN '0 [Photo]'
        WHEN 1 THEN '1 [Video]'
    END AS 'ZASSET.ZKIND',

    CASE ZASSET.ZKINDSUBTYPE
        WHEN 0 THEN '0 [Still Photo]'
        WHEN 1 THEN '1 [Still Testing]'
        WHEN 2 THEN '2 [Live Photo]'
        WHEN 3 THEN '3 [Screenshot]'
        WHEN 10 THEN '10 [SpringBoard Screenshot]'
        WHEN 100 THEN '100 [Video]'
        WHEN 101 THEN '101 [Slow Mo Video]'
        WHEN 102 THEN '102 [Time lapse Video]'
        WHEN 103 THEN '103 [Replay Screen Recording]'
        ELSE 'Unknown New Value: ' || ZASSET.ZKINDSUBTYPE || ''
    END AS 'ZASSET.ZKINDSUBTYPE',

    CASE ZASSET.ZPLAYBACKSTYLE
        WHEN 1 THEN '1 [Image]'
        WHEN 2 THEN '2 [Image Animated]'
        WHEN 3 THEN '3 [Live Photo]'
        WHEN 4 THEN '4 [Video]'
        WHEN 5 THEN '5 [Video Looping]'
        ELSE 'Unknown New Value: ' || ZASSET.ZPLAYBACKSTYLE || ''
    END AS 'ZASSET.ZPLAYBACKSTYLE',

    ZEXTENDEDATTRIBUTES.ZCAMERAMAKE AS 'ZCAMERAMAKE',
    ZEXTENDEDATTRIBUTES.ZCAMERAMODEL AS 'ZCAMERAMODEL',
    ZEXTENDEDATTRIBUTES.ZCODEC AS 'ZCODEC',
    ZEXTENDEDATTRIBUTES.ZLENSMODEL AS 'ZLENSMODEL',

    ZGENERICALBUM.ZTITLE AS 'ZGENERICALBUM.ZTITLE',

    CASE ZASSET.ZDURATION
        WHEN 0 THEN '0 [N/A]'
        ELSE ZASSET.ZDURATION
    END AS 'ZASSET.ZDURATION',

    ZADDITIONALASSETATTRIBUTES.ZIMPORTEDBYBUNDLEIDENTIFIER AS 'ZIMPORTEDBYBUNDLEIDENTIFIER',
    ZADDITIONALASSETATTRIBUTES.ZIMPORTEDBYDISPLAYNAME AS 'ZIMPORTEDBYDISPLAYNAME',
    printf("%,d", ZADDITIONALASSETATTRIBUTES.ZORIGINALFILESIZE) AS 'ZORIGINALFILESIZE(Bytes)',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALHEIGHT AS 'ZORIGINALHEIGHT',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALWIDTH AS 'ZORIGINALWIDTH',

    datetime(ZASSET.ZDATECREATED + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZDATECREATED(UTC)',
    datetime(ZASSET.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZMODIFICATIONDATE(UTC)',
    datetime(ZASSET.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZADDEDDATE(UTC)',

    /*
    This column can correlate to the `guid` column in the `message` table of the
    sms.db file.  This can tell what message a given image was associated with.

    The ZSYNDICATIONIDENTIFIER will have the following format:
        at_0_B2F67B26-592F-4551-8D0C-9CFBC15653F4
        --"at" indicates the item\asset is from within Apple Messages application
        or was an attachment to a message.

    The first number between the underscores indicates how many images were sent
    as part of that message -- counting begins at "0" -- so, in the example above,
    one (1) image was sent with this message (if the number were "1", that would
    indicate that two files were attached to the message).  The ID formatted as:
    8-4-4-4-12 is the message GUID from the sms.db file.
    */
    ZADDITIONALASSETATTRIBUTES.ZSYNDICATIONIDENTIFIER AS 'ZSYNDICATIONIDENTIFIER',

    CASE ZASSET.ZFAVORITE
        WHEN 0 THEN '0 [No]'
        WHEN 1 THEN '1 [Yes]'
        ELSE ZASSET.ZFAVORITE
    END AS 'ZFAVORITE',

    CASE ZASSET.ZHIDDEN
        WHEN 0 THEN '0 [Not Hidden]'
        WHEN 1 THEN '1 [Hidden]'
        ELSE ZASSET.ZHIDDEN
    END AS 'ZHIDDEN',

    ZADDITIONALASSETATTRIBUTES.ZPENDINGVIEWCOUNT AS 'ZPENDINGVIEWCOUNT',
    ZADDITIONALASSETATTRIBUTES.ZVIEWCOUNT AS 'ZVIEWCOUNT',
    ZADDITIONALASSETATTRIBUTES.ZPENDINGSHARECOUNT AS 'ZPENDINGSHARECOUNT',
    ZADDITIONALASSETATTRIBUTES.ZSHARECOUNT AS 'ZSHARECOUNT',
    ZASSET.ZLASTSHAREDDATE AS 'ZASSET.ZLASTSHAREDDATE',
    ZADDITIONALASSETATTRIBUTES.ZPENDINGPLAYCOUNT AS 'ZPENDINGPLAYCOUNT',
    ZADDITIONALASSETATTRIBUTES.ZPLAYCOUNT AS 'ZPLAYCOUNT',
    ZADDITIONALASSETATTRIBUTES.ZUPLOADATTEMPTS AS 'ZUPLOADATTEMPTS',

    CASE ZASSET.ZTRASHEDSTATE
        WHEN 1 THEN '1 [In Trash]'
        WHEN 0 THEN '0 [Not In Trash]'
        ELSE ZASSET.ZTRASHEDSTATE
    END AS 'ZASSET.ZTRASHEDSTATE',

    CASE
        WHEN ZASSET.ZTRASHEDDATE IS NULL THEN 'n/a'
        ELSE datetime(ZASSET.ZTRASHEDDATE + 978307200, 'UNIXEPOCH')
    END AS 'ZASSET.ZTRASHEDDATE(UTC)',

    CASE ZASSET.ZLATITUDE
        WHEN -180.0 THEN '[N/A]'
        ELSE ZASSET.ZLATITUDE
    END 'ZASSET.LATITUDE',

    CASE ZASSET.ZLONGITUDE
        WHEN -180.0 THEN '[N/A]'
        ELSE ZASSET.ZLONGITUDE
    END 'ZASSET.LONGITUDE',

    datetime(ZMOMENT.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'ZMOMENT.ZSTARTDATE(UTC)',
    datetime(ZMOMENT.ZREPRESENTATIVEDATE + 978307200, 'UNIXEPOCH') AS 'ZMOMENT.ZREPRESENTATIVEDATE(UTC)',
    datetime(ZMOMENT.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'ZMOMENT.ZMODIFICATIONDATE(UTC)',
    datetime(ZMOMENT.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'ZMOMENT.ZENDDATE(UTC)',

    ZMOMENT.ZTITLE AS 'ZMOMENT.ZTITLE',
    ZMOMENT.ZUUID AS 'ZMOMENT.UUID',

    CASE ZMOMENT.ZAPPROXIMATELATITUDE
        WHEN -180.0 THEN 'n/a'
        ELSE ZMOMENT.ZAPPROXIMATELATITUDE
    END AS 'ZMOMENT.ZAPPROXIMATELATITUDE',

    CASE ZMOMENT.ZAPPROXIMATELONGITUDE
        WHEN -180.0 THEN 'n/a'
        ELSE ZMOMENT.ZAPPROXIMATELONGITUDE
    END AS 'ZMOMENT.ZAPPROXIMATELONGITUDE',

    CASE ZINTERNALRESOURCE.ZLOCALAVAILABILITY
        WHEN -1 THEN '(-1) [IR Asset Not Available Local Device]'
        WHEN 1 THEN '1 [IR Asset Available Local Device]'
        WHEN -32768 THEN '(-32768) [IR Asset SWY Linked Asset]'
        ELSE 'Unknown New Value: ' || ZINTERNALRESOURCE.ZLOCALAVAILABILITY || ''
    END AS 'ZINTERNALRESOURCE.ZLOCALAVAILABILITY',

    datetime(ZASSET.ZCLOUDSERVERPUBLISHDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZCLOUDSERVERPUBLISHDATE(UTC)',

    ZASSET.ZCLOUDASSETGUID AS 'ZASSET.ZCLOUDASSETGUID',
    ZASSET.ZCLOUDBATCHID AS 'ZASSET.ZCLOUDBATCHID',

    CASE ZASSET.ZCLOUDPLACEHOLDERKIND
        WHEN 0 THEN '0 [Local&CloudMaster Asset]'
        WHEN 1 THEN '1 [Still Testing]'
        WHEN 2 THEN '2 [Still Testing]'
        WHEN 3 THEN '3 [JPG Asset Only PhotoData/Thumb/V2]'
        WHEN 4 THEN '4 [LPL JPG Asset CPL Asset HEIC JPG JPEG MOV PNG]'
        WHEN 5 THEN '5 [Asset synced via iCloud Photos 2 Device]'
        WHEN 6 THEN '6 [Still Testing]'
        WHEN 7 THEN '7 [LPL poster JPG Asset CPL Asset MP4]'
        WHEN 8 THEN '8 [LPL JPG Asset CPL Asset LivePhoto MOV]'
        WHEN 9 THEN '9 [CPL MP4 Asset Saved 2 LPL]'
        ELSE 'Unknown New Value: ' || ZASSET.ZCLOUDPLACEHOLDERKIND || ''
    END AS 'ZASSET.ZCLOUDPLACEHOLDERKIND',

    ZASSET.ZCLOUDDOWNLOADREQUESTS AS 'ZCLOUDDOWNLOADREQUESTS'


FROM ZASSET
    JOIN ZADDITIONALASSETATTRIBUTES ON ZASSET.ZADDITIONALATTRIBUTES = ZADDITIONALASSETATTRIBUTES.Z_PK
    LEFT JOIN ZMOMENT ON ZASSET.ZMOMENT = ZMOMENT.Z_PK
    LEFT JOIN ZEXTENDEDATTRIBUTES ON ZEXTENDEDATTRIBUTES.Z_PK = ZASSET.ZEXTENDEDATTRIBUTES
    LEFT JOIN ZINTERNALRESOURCE ON ZINTERNALRESOURCE.ZASSET = ZASSET.Z_PK
    LEFT JOIN Z_28ASSETS ON ZASSET.Z_PK = Z_28ASSETS.Z_3ASSETS
    LEFT JOIN ZGENERICALBUM ON ZGENERICALBUM.Z_PK = Z_28ASSETS.Z_28ALBUMS
    LEFT JOIN Z_27ALBUMLISTS ON Z_27ALBUMLISTS.Z_27ALBUMS = ZGENERICALBUM.Z_PK
    LEFT JOIN ZALBUMLIST ON ZALBUMLIST.Z_PK = Z_27ALBUMLISTS.Z_2ALBUMLISTS


-- WHERE
--     /*Find only files that are hidden*/
--     ZASSET.ZHIDDEN IS "1"
--     /*Find only files that have GPS coordinates*/
--     ZASSET.ZLATITUDE != -180.0


ORDER BY ZASSET.Z_PK


-- LIMIT 20