SELECT
    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    ZGENERICALBUM.Z_PK AS 'ZGENERICALBUM.Z_PK',
    ZGENERICALBUM.ZTITLE AS 'ZGENERICALBUM.ZTITLE',
    ZASSET.ZDIRECTORY AS 'ZASSET.ZDIRECTORY',
    ZASSET.ZFILENAME AS 'ZASSET.ZFILENAME',
    ZASSET.ZUNIFORMTYPEIDENTIFIER AS 'ZASSET.ZUNIFORMTYPEIDENTIFIER',

    CASE ZASSET.ZFAVORITE
        WHEN '0' THEN '0  [No]'
        WHEN '1' THEN '1  [Yes]'
        ELSE ZASSET.ZFAVORITE
    END 'ZASSET.ZFAVORITE',

    ZASSET.ZDURATION AS 'ZASSET.ZDURATION(SECONDS)',

    datetime(ZASSET.ZDATECREATED + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZDATECREATED(UTC)',
    datetime(ZASSET.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZADDEDDATE(UTC)',
    datetime(ZASSET.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZMODIFICATIONDATE(UTC)',
    datetime(ZASSET.ZTRASHEDDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZTRASHEDDATE(UTC)',

    ZASSET.ZTHUMBNAILINDEX AS 'ThumbnailIndex',

    CASE ZASSET.ZLATITUDE
        WHEN '-180.0' THEN 'N/A'
        ELSE ZASSET.ZLATITUDE
    END 'Latitude',

    CASE ZASSET.ZLONGITUDE
        WHEN '-180.0' THEN 'N/A'
        ELSE ZASSET.ZLONGITUDE
    END 'Longitude'


FROM ZASSET
    INNER JOIN (ZGENERICALBUM INNER JOIN Z_28ASSETS ON ZGENERICALBUM.Z_PK = Z_28ASSETS.Z_28ALBUMS) ON ZASSET.Z_PK = Z_28ASSETS.Z_3ASSETS


ORDER BY ZGENERICALBUM.Z_PK
