SELECT
    /* Add a row number at the beggining of each row */
    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    ZASSET.Z_PK AS 'ZASSET.Z_PK',
    ZASSET.ZADDITIONALATTRIBUTES AS 'ZASSET.ZADDITIONALATTRIBUTES',
    zdf.ZASSET AS 'zdf.ZASSET',

    CASE ZASSET.ZKIND
        WHEN 0 THEN '0  [Photo]'
        WHEN 1 THEN '1  [Video]'
        ELSE ZASSET.ZKIND
    END AS 'ZASSET.ZKIND',

    ZASSET.ZUNIFORMTYPEIDENTIFIER AS 'ZASSET.ZUNIFORMTYPEIDENTIFIER',

    datetime(ZASSET.ZDATECREATED + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZDATECREATED(UTC)',

    zaaa.ZEXIFTIMESTAMPSTRING AS 'zaaa.ZEXIFTIMESTAMPSTRING(UTC)',

    datetime(ZASSET.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZADDEDDATE(UTC)',
    datetime(zaaa.ZSCENEANALYSISTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'zaaa.ZSCENEANALYSISTIMESTAMP(UTC)',
    datetime(ZASSET.ZANALYSISSTATEMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZANALYSISSTATEMODIFICATIONDATE(UTC)',

    ZASSET.ZDIRECTORY AS 'ZASSET.ZDIRECTORY',
    ZASSET.ZFILENAME AS 'ZASSET.ZFILENAME',
    zaaa.ZORIGINALFILENAME AS 'zaaa.ZORIGINALFILENAME',
    zga.ZTITLE AS 'zga.ZTITLE',
    -- zaaa.ZCREATORBUNDLEID AS 'zaaa.ZCREATORBUNDLEID',
    zaaa.ZEDITORBUNDLEID AS 'zaaa.ZEDITORBUNDLEID',

    CASE ZASSET.ZSAVEDASSETTYPE
        WHEN 0 THEN '0  [Saved via other source]'
        WHEN 2 THEN '1  [Still Testing]'
        WHEN 1 THEN '2  [Still Testing]'
        WHEN 3 THEN '3  [Local Photo Library Asset]'
        WHEN 4 THEN '4  [Photo Cloud Sharing Data Asset]'
        WHEN 5 THEN '5  [PhotoBooth Photo Library Asset]'
        WHEN 6 THEN '6  [Cloud Photo Library Asset]'
        WHEN 7 THEN '7  [Still Testing]'
        WHEN 8 THEN '8  [iCloudLink Cloud Master Moment Asset]'
        WHEN 12 THEN '12  [SWY Syndication PL Asset/Auto Displayed in LPL]'
        ELSE 'Unknown Value: ' || ZASSET.ZSAVEDASSETTYPE || ''
    END AS 'ZASSET.ZSAVEDASSETTYPE(LPL)',

    CASE
        WHEN ZASSET.ZFACEAREAPOINTS > 0 THEN 'Yes'
        ELSE '[N/A]'
    END AS 'ZASSET.ZFACEAREAPOINTS',

    ZPERSON.ZDISPLAYNAME AS 'ZPERSON.ZDISPLAYNAME',
    ZPERSON.ZFULLNAME AS 'ZPERSON.ZFULLNAME',
    ZPERSON.ZFACECOUNT AS 'ZPERSON.ZFACECOUNT',
    zdf.ZPERSON AS 'zdf.ZPERSON',
    hex(ZPERSON.ZCONTACTMATCHINGDICTIONARY) AS 'ZPERSON.ZCONTACTMATCHINGDICTIONARY',
    ZPERSON.ZPERSONUUID as 'ZPERSON.ZPERSONUUID',
    zdf.ZQUALITYMEASURE AS 'zdf.ZQUALITYMEASURE',

    CASE zdf.ZAGETYPE
        WHEN 1 THEN '1  [Baby/Toddler]'
        WHEN 2 THEN '2  [Baby/Toddler]'
        WHEN 3 THEN '3  [Child/Young Adult]'
        WHEN 4 THEN '4  [Young Adult/Adult]'
        WHEN 5 THEN '5  [Adult]'
        ELSE zdf.ZAGETYPE
    END AS 'zdf.ZAGETYPE',

    CASE zdf.ZGENDERTYPE
        WHEN 1 THEN '1  [Male]'
        WHEN 2 THEN '2  [Female]'
        ELSE zdf.ZGENDERTYPE
    END AS 'zdf.ZGENDERTYPE',

    CASE zdf.ZGLASSESTYPE
        WHEN 1 THEN '1  [Eye]'
        WHEN 2 THEN '2  [Sun]'
        WHEN 3 THEN '3  [None]'
        ELSE zdf.ZGLASSESTYPE
    END AS 'zdf.ZGLASSESTYPE',

    CASE zdf.ZFACIALHAIRTYPE
        WHEN 1 THEN '1  [None]'
        WHEN 2 THEN '2  [Beard/Mustache]'
        WHEN 3 THEN '3  [Goatee]'
        WHEN 5 THEN '5  [Stubble]'
        ELSE zdf.ZFACIALHAIRTYPE
    END AS 'zdf.ZFACIALHAIRTYPE',

    CASE zdf.ZHAIRTYPE
        WHEN 2 THEN '2  [Bald]'
        WHEN 3 THEN '3  [Not Bald]'
        ELSE zdf.ZHAIRTYPE
    END AS 'zdf.ZHAIRTYPE',

    ZASSET.ZORIGINALCOLORSPACE AS 'ZASSET.ZORIGINALCOLORSPACE',
    ZASSET.ZDURATION AS 'ZASSET.ZDURATION',
    ZASSET.ZVIDEOCPDURATIONVALUE AS 'ZASSET.ZVIDEOCPDURATIONVALUE',

    CASE ZASSET.ZCOMPLETE
        WHEN 1 THEN '1  [Yes]'
        ELSE ZASSET.ZCOMPLETE
    END AS 'ZASSET.ZCOMPLETE',

    CASE ZASSET.ZVISIBILITYSTATE
        WHEN 0 THEN '0  [Visible]'
        WHEN 1 THEN '1  [Photo Streams Data]'
        WHEN 2 THEN '2  [Burst]'
        ELSE ZASSET.ZVISIBILITYSTATE
    END AS 'ZASSET.ZVISIBILITYSTATE',

    CASE ZASSET.ZFAVORITE
        WHEN 0 THEN '0  [No]'
        WHEN 1 THEN '1  [Yes]'
        ELSE ZASSET.ZFAVORITE
    END AS 'ZASSET.ZFAVORITE',

    CASE ZASSET.ZHIDDEN
        WHEN 0 THEN '0  [Not Hidden]'
        WHEN 1 THEN '1  [File Hidden]'
        ELSE ZASSET.ZHIDDEN
    END AS 'ZASSET.ZHIDDEN',

    CASE ZASSET.ZTRASHEDSTATE
        WHEN 0 THEN '0  [Not In Trash]'
        WHEN 1 THEN '1  [In Trash]'
        ELSE ZASSET.ZTRASHEDSTATE
    END AS 'ZASSET.ZTRASHEDSTATE',

    CASE
        WHEN ZASSET.ZTRASHEDDATE IS NULL THEN 'N/A'
        ELSE datetime(ZASSET.ZTRASHEDDATE + 978307200, 'UNIXEPOCH')
    END AS 'ZASSET.ZTRASHEDDATE(UTC)',

    zaaa.ZVIEWCOUNT AS 'zaaa.ZVIEWCOUNT',
    zaaa.ZPLAYCOUNT AS 'zaaa.ZPLAYCOUNT',
    zaaa.ZSHARECOUNT AS 'zaaa.ZSHARECOUNT',

    datetime(ZASSET.ZLASTSHAREDDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZLASTSHAREDDATE(UTC)',
    datetime(ZASSET.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZMODIFICATIONDATE(UTC)',

    CASE ZASSET.ZHASADJUSTMENTS
        WHEN 0 THEN '0  [No]'
        WHEN 1 THEN '1  [Yes]'
        ELSE ZASSET.ZHASADJUSTMENTS
    END AS 'ZASSET.ZHASADJUSTMENTS',

    datetime(ZASSET.ZADJUSTMENTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZADJUSTMENTTIMESTAMP(UTC)',

    zaaa.ZORIGINALFILESIZE AS 'zaaa.ZORIGINALFILESIZE',
    ZASSET.ZHEIGHT AS 'ZASSET.ZHEIGHT',
    zaaa.ZORIGINALHEIGHT AS 'zaaa.ZORIGINALHEIGHT',
    ZASSET.ZWIDTH AS 'ZASSET.ZWIDTH',
    zaaa.ZORIGINALWIDTH AS 'zaaa.ZORIGINALWIDTH',
    zaaa.ZCAMERACAPTUREDEVICE AS 'zaaa.ZCAMERACAPTUREDEVICE',

    CASE ZASSET.ZORIENTATION
        WHEN 1 THEN '1  [Horizontal (Left)]'
        WHEN 3 THEN '3  [Horizontal (Right)]'
        WHEN 6 THEN '6  [Vertical (Up)]'
        WHEN 8 THEN '8  [Vertical (Down)]'
        ELSE ZASSET.ZORIENTATION
    END AS 'ZASSET.ZORIENTATION',

    CASE zaaa.ZORIGINALORIENTATION
        WHEN 1 THEN '1  [Horizontal (Left)]'
        WHEN 3 THEN '3  [Horizontal (Right)]'
        WHEN 6 THEN '6  [Vertical (Up)]'
        WHEN 8 THEN '8  [Vertical (Down)]'
        ELSE zaaa.ZORIGINALORIENTATION
    END AS 'zaaa.ZORIGINALORIENTATION',

    zaaa.ZTIMEZONENAME AS 'zaaa.ZTIMEZONENAME',
    zaaa.ZTIMEZONEOFFSET AS 'zaaa.ZTIMEZONEOFFSET',
    zaaa.ZINFERREDTIMEZONEOFFSET AS 'zaaa.ZINFERREDTIMEZONEOFFSET',
    ZASSET.ZLOCATIONDATA AS 'ZASSET.ZLOCATIONDATA',

    CASE ZASSET.ZLATITUDE
        WHEN -180.0 THEN 'N/A'
        ELSE ZASSET.ZLATITUDE
    END 'ZASSET.ZLATITUDE',

    CASE ZASSET.ZLONGITUDE
        WHEN -180.0 THEN 'N/A'
        ELSE ZASSET.ZLONGITUDE
    END 'ZASSET.ZLONGITUDE',

    CASE zaaa.ZSHIFTEDLOCATIONISVALID
        WHEN 0 THEN '0  [No]'
        WHEN 1 THEN '1  [Yes]'
        ELSE zaaa.ZSHIFTEDLOCATIONISVALID
    END AS 'zaaa.ZSHIFTEDLOCATIONISVALID',

    CASE zaaa.ZREVERSELOCATIONDATAISVALID
        WHEN 0 THEN '0  [No - Check Scene Analysis]'
        WHEN 1 THEN '1  [Yes - Check Scene Analysis]'
        ELSE zaaa.ZREVERSELOCATIONDATAISVALID
    END AS 'zaaa.ZREVERSELOCATIONDATAISVALID',

    zaaa.ZREVERSELOCATIONDATA AS 'zaaa.ZREVERSELOCATIONDATA',
    ZASSET.ZTHUMBNAILINDEX AS 'ZASSET.ZTHUMBNAILINDEX ',
    zaaa.ZEMBEDDEDTHUMBNAILWIDTH AS 'zaaa.ZEMBEDDEDTHUMBNAILWIDTH',
    zaaa.ZEMBEDDEDTHUMBNAILHEIGHT AS 'zaaa.ZEMBEDDEDTHUMBNAILHEIGHT',
    zaaa.ZEMBEDDEDTHUMBNAILOFFSET AS 'zaaa.ZEMBEDDEDTHUMBNAILOFFSET',
    zaaa.ZEMBEDDEDTHUMBNAILLENGTH AS 'zaaa.ZEMBEDDEDTHUMBNAILLENGTH',
    ZASSET.ZMOMENT AS 'ZASSET.ZMOMENT',
    zm.ZTITLE AS 'zm.ZTITLE',

    datetime(zm.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'zm.ZSTARTDATE(UTC)',
    datetime(zm.ZREPRESENTATIVEDATE + 978307200, 'UNIXEPOCH') AS 'zm.ZREPRESENTATIVEDATE(UTC)',
    datetime(zm.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'zm.ZMODIFICATIONDATE(UTC)',
    datetime(zm.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'zm.ZENDDATE(UTC)',

    CASE zm.ZTRASHEDSTATE
        WHEN 0 THEN '0  [Not In Trash]'
        WHEN 1 THEN '1  [In Trash]'
        ELSE zm.ZTRASHEDSTATE
    END AS 'zm.ZTRASHEDSTATE',

    CASE zm.ZAPPROXIMATELATITUDE
        WHEN -180.0 THEN 'N/A'
        ELSE zm.ZAPPROXIMATELATITUDE
    END AS 'zm.ZAPPROXIMATELATITUDE',

    CASE zm.ZAPPROXIMATELONGITUDE
        WHEN -180.0 THEN 'N/A'
        ELSE zm.ZAPPROXIMATELONGITUDE
    END AS 'zm.ZAPPROXIMATELONGITUDE',

    ZASSET.ZUUID AS 'ZASSET.ZUUID',
    ZASSET.ZMEDIAGROUPUUID AS 'ZASSET.ZMEDIAGROUPUUID',
    ZASSET.ZCLOUDASSETGUID AS 'ZASSET.ZCLOUDASSETGUID',
    zaaa.ZPUBLICGLOBALUUID AS 'zaaa.ZPUBLICGLOBALUUID',
    zaaa.ZMASTERFINGERPRINT AS 'zaaa.ZMASTERFINGERPRINT',
    zaaa.ZADJUSTEDFINGERPRINT AS 'zaaa.ZADJUSTEDFINGERPRINT'


FROM ZASSET
    LEFT JOIN ZMOMENT zm ON zm.Z_PK = ZASSET.ZMOMENT
    JOIN ZADDITIONALASSETATTRIBUTES zaaa ON ZASSET.ZADDITIONALATTRIBUTES = zaaa.Z_PK
    LEFT JOIN ZDETECTEDFACE zdf ON zdf.ZASSET = ZASSET.Z_PK
    LEFT JOIN ZPERSON ON ZPERSON.Z_PK = zdf.ZPERSON
    LEFT JOIN Z_28ASSETS ON ZASSET.Z_PK = Z_28ASSETS.Z_3ASSETS
    LEFT JOIN ZGENERICALBUM zga ON zga.Z_PK = Z_28ASSETS.Z_28ALBUMS


WHERE ZASSET.ZFACEAREAPOINTS > 0


ORDER BY ZASSET.Z_PK ASC
