/*
[DLU]
    05-Sep-2025
*/


SELECT
    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    ZGENERICALBUM.Z_PK AS 'ZGENERICALBUM.Z_PK',
    ZASSET.ZDIRECTORY AS 'ZASSET.ZDIRECTORY',
    ZASSET.ZFILENAME AS 'ZASSET.ZFILENAME',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALFILENAME AS 'ZADDITIONALASSETATTRIBUTES.ZORIGINALFILENAME',

    CASE ZASSET.ZKINDZUNIFORMTYPEIDENTIFIER
        WHEN '0' THEN '0 [Photo]'
        WHEN '1' THEN '1 [Video]'
        ELSE 'Unknown Value: ' || ZASSET.ZKINDZUNIFORMTYPEIDENTIFIER
    END AS 'ZASSET.ZKINDZUNIFORMTYPEIDENTIFIER',

    ZASSET.ZUNIFORMTYPEIDENTIFIER AS 'ZASSET.ZUNIFORMTYPEIDENTIFIER',

    CASE ZASSET.ZFAVORITE
        WHEN '0' THEN '0 [No]'
        WHEN '1' THEN '1 [Yes]'
        ELSE 'Unknown Value: ' || ZASSET.ZFAVORITE
    END 'ZASSET.ZFAVORITE',

    datetime(ZASSET.ZDATECREATED + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZDATECREATED(UTC)',
    datetime(ZASSET.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZADDEDDATE(UTC)',
    datetime(ZASSET.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZMODIFICATIONDATE(UTC)',
    datetime(ZASSET.ZTRASHEDDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZTRASHEDDATE(UTC)',

    CASE
        WHEN ZADDITIONALASSETATTRIBUTES.ZEXIFTIMESTAMPSTRING IS NULL THEN '[N/A]'
        ELSE ZADDITIONALASSETATTRIBUTES.ZEXIFTIMESTAMPSTRING
    END AS 'ZADDITIONALASSETATTRIBUTES.ZEXIFTIMESTAMPSTRING(UTC)',

    ZADDITIONALASSETATTRIBUTES.ZVIEWCOUNT AS 'ZADDITIONALASSETATTRIBUTES.ZVIEWCOUNT',
    ZADDITIONALASSETATTRIBUTES.ZSHARECOUNT AS 'ZADDITIONALASSETATTRIBUTES.ZSHARECOUNT',

    CASE
        WHEN ZASSET.ZLASTSHAREDDATE IS NULL THEN '[N/A]'
        ELSE datetime(ZASSET.ZLASTSHAREDDATE + 978307200, 'UNIXEPOCH')
    END AS 'ZASSET.ZLASTSHAREDDATE(UTC)',

    ZADDITIONALASSETATTRIBUTES.ZPLAYCOUNT AS 'ZADDITIONALASSETATTRIBUTES.ZPLAYCOUNT',

    CASE ZASSET.ZHIDDEN
        WHEN 0 THEN '0 [Not Hidden]'
        WHEN 1 THEN '1 [Hidden]'
        ELSE 'Unknown Value: ' || ZASSET.ZHIDDEN
    END AS 'ZASSET.ZHIDDEN',

    ZASSET.ZDURATION AS 'Duration(seconds)',
    ZADDITIONALASSETATTRIBUTES.ZIMPORTEDBY AS 'ZADDITIONALASSETATTRIBUTES.ZIMPORTEDBY',
    ZADDITIONALASSETATTRIBUTES.ZCAMERACAPTUREDEVICE AS 'ZADDITIONALASSETATTRIBUTES.ZCAMERACAPTUREDEVICE',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALFILESIZE AS 'ZADDITIONALASSETATTRIBUTES.ZORIGINALFILESIZE',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALHEIGHT AS 'ZADDITIONALASSETATTRIBUTES.ZORIGINALHEIGHT',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALWIDTH AS 'ZADDITIONALASSETATTRIBUTES.ZORIGINALWIDTH',
    ZASSET.ZTHUMBNAILINDEX AS 'ZASSET.ZTHUMBNAILINDEX',

    CASE
        WHEN ZADDITIONALASSETATTRIBUTES.ZCREATORBUNDLEID IS NULL THEN '[N/A]'
        ELSE ZADDITIONALASSETATTRIBUTES.ZCREATORBUNDLEID
    END AS 'ZADDITIONALASSETATTRIBUTES.ZCREATORBUNDLEID',

    CASE
        WHEN ZADDITIONALASSETATTRIBUTES.ZEDITORBUNDLEID IS NULL THEN '[N/A]'
        ELSE ZADDITIONALASSETATTRIBUTES.ZEDITORBUNDLEID
    END AS 'ZADDITIONALASSETATTRIBUTES.ZEDITORBUNDLEID',

    ZADDITIONALASSETATTRIBUTES.ZLOCATIONHASH AS 'ZADDITIONALASSETATTRIBUTES.ZLOCATIONHASH',
    ZADDITIONALASSETATTRIBUTES.ZMASTERFINGERPRINT AS 'ZADDITIONALASSETATTRIBUTES.ZMASTERFINGERPRINT',

    CASE ZASSET.ZLATITUDE
        WHEN '-180.0' THEN '[-180.0]'
        ELSE ZASSET.ZLATITUDE
    END 'ZASSET.ZLATITUDE',

    CASE ZASSET.ZLONGITUDE
        WHEN '-180.0' THEN '[-180.0]'
        ELSE ZASSET.ZLONGITUDE
    END 'ZASSET.ZLONGITUDE'


FROM ZASSET
    JOIN ZADDITIONALASSETATTRIBUTES ON ZASSET.Z_PK = ZADDITIONALASSETATTRIBUTES.ZASSET


ORDER BY ZASSET.ZADDEDDATE ASC

/*

To get info for specific media files, enter the file name below

DO NOT put "OR" after the last file name

*/

-- WHERE (
--     ZFILENAME LIKE 'IMG 9007.JPG' OR
--     ZFILENAME LIKE 'IMG 9014.GIF' OR
--     ZFILENAME LIKE 'IMG 9037.JPG' OR
--     ZFILENAME LIKE 'IMG 9049.PNG' OR
--     ZFILENAME LIKE 'IMG 9058.JPG' OR
--     ZFILENAME LIKE 'IMG 9064.JPG' OR
--     ZFILENAME LIKE 'IMG 9092.JPG' OR
--     ZFILENAME LIKE 'IMG 9095.JPG' OR
--     ZFILENAME LIKE 'IMG 9123.PNG' OR
--     ZFILENAME LIKE 'IMG 9253.JPG'
--    )

/*
Use 'DESC' for decending order (most recent date on top)
Use 'ASC' for acending order (most recent date on bottom)
*/

