/*
[DLU]
    05-Sep-2025
[FILE PATH]
    /private/var/mobile/Media/PhotoData/Photos.sqlite
    /private/var/mobile/Library/Photos/Libraries/Syndication.photoslibrary/database/Photos.sqlite
*/

SELECT

    /* Add a row number at the beggining of each row */
    ROW_NUMBER() OVER() AS 'RECORD_NUMBER',
    ZASSET.Z_PK AS 'ZASSET.Z_PK',
    ZASSET.ZADDITIONALATTRIBUTES AS 'ZASSET.ZADDITIONALATTRIBUTES',
    ZDETECTEDFACE.ZASSET AS 'ZDETECTEDFACE.ZASSET',

    CASE ZASSET.ZKIND
        WHEN 0 THEN '0 [Photo]'
        WHEN 1 THEN '1 [Video]'
        ELSE 'Unknown Value: ' || ZASSET.ZKIND
    END AS 'ZASSET.ZKIND',

    ZASSET.ZUNIFORMTYPEIDENTIFIER AS 'ZASSET.ZUNIFORMTYPEIDENTIFIER',

    CASE
        WHEN LENGTH(ZASSET.ZDATECREATED) = 18 THEN datetime((ZASSET.ZDATECREATED / 1000000000) + 978307200, 'UNIXEPOCH')
        WHEN LENGTH(ZASSET.ZDATECREATED) = 9 THEN datetime(ZASSET.ZDATECREATED + 978307200, 'UNIXEPOCH')
        ELSE datetime(ZASSET.ZDATECREATED + 978307200, 'UNIXEPOCH')
    END AS 'ZASSET.ZDATECREATED(UTC)',

    ZADDITIONALASSETATTRIBUTES.ZEXIFTIMESTAMPSTRING AS 'ZADDITIONALASSETATTRIBUTES.ZEXIFTIMESTAMPSTRING(UTC)',

    datetime(ZASSET.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZADDEDDATE(UTC)',
    datetime(ZADDITIONALASSETATTRIBUTES.ZSCENEANALYSISTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZADDITIONALASSETATTRIBUTES.ZSCENEANALYSISTIMESTAMP(UTC)',
    datetime(ZASSET.ZANALYSISSTATEMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZANALYSISSTATEMODIFICATIONDATE(UTC)',

    ZASSET.ZDIRECTORY AS 'ZASSET.ZDIRECTORY',
    ZASSET.ZFILENAME AS 'ZASSET.ZFILENAME',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALFILENAME AS 'ZADDITIONALASSETATTRIBUTES.ZORIGINALFILENAME',
    ZGENERICALBUM.ZTITLE AS 'ZGENERICALBUM.ZTITLE',
    -- ZADDITIONALASSETATTRIBUTES.ZCREATORBUNDLEID AS 'ZADDITIONALASSETATTRIBUTES.ZCREATORBUNDLEID',
    ZADDITIONALASSETATTRIBUTES.ZEDITORBUNDLEID AS 'ZADDITIONALASSETATTRIBUTES.ZEDITORBUNDLEID',

    CASE ZASSET.ZSAVEDASSETTYPE
        WHEN 0 THEN '0 [Saved via other source]'
        WHEN 1 THEN '1 [Still Testing]'
        WHEN 2 THEN '2 [Photo Streams Data]'
        WHEN 3 THEN '3 [Local Photo Library Asset]'
        WHEN 4 THEN '4 [Photo Cloud Sharing Data Asset]'
        WHEN 5 THEN '5 [PhotoBooth Photo Library Asset]'
        WHEN 6 THEN '6 [Cloud Photo Library Asset]'
        WHEN 7 THEN '7 [Still Testing]'
        WHEN 8 THEN '8 [iCloudLink Cloud Master Moment Asset]'
        WHEN 12 THEN '12 [SWY Syndication PL Asset/Auto Displayed in LPL]'
        ELSE 'Unknown Value: ' || ZASSET.ZSAVEDASSETTYPE
    END AS 'ZASSET.ZSAVEDASSETTYPE(LPL)',

    CASE
        WHEN ZASSET.ZFACEAREAPOINTS > 0 THEN 'Yes'
        ELSE '[N/A]'
    END AS 'ZASSET.ZFACEAREAPOINTS',

    ZPERSON.ZDISPLAYNAME AS 'ZPERSON.ZDISPLAYNAME',
    ZPERSON.ZFULLNAME AS 'ZPERSON.ZFULLNAME',
    ZPERSON.ZFACECOUNT AS 'ZPERSON.ZFACECOUNT',
    ZDETECTEDFACE.ZPERSON AS 'ZDETECTEDFACE.ZPERSON',
    hex(ZPERSON.ZCONTACTMATCHINGDICTIONARY) AS 'ZPERSON.ZCONTACTMATCHINGDICTIONARY',
    ZPERSON.ZPERSONUUID as 'ZPERSON.ZPERSONUUID',
    ZDETECTEDFACE.ZQUALITYMEASURE AS 'ZDETECTEDFACE.ZQUALITYMEASURE',

    CASE ZDETECTEDFACE.ZAGETYPE
        WHEN 1 THEN '1 [Baby/Toddler]'
        WHEN 2 THEN '2 [Baby/Toddler]'
        WHEN 3 THEN '3 [Child/Young Adult]'
        WHEN 4 THEN '4 [Young Adult/Adult]'
        WHEN 5 THEN '5 [Adult]'
        ELSE 'Unknown Value: ' || ZDETECTEDFACE.ZAGETYPE
    END AS 'ZDETECTEDFACE.ZAGETYPE',

    CASE ZDETECTEDFACE.ZGENDERTYPE
        WHEN 1 THEN '1 [Male]'
        WHEN 2 THEN '2 [Female]'
        ELSE 'Unknown Value: ' || ZDETECTEDFACE.ZGENDERTYPE
    END AS 'ZDETECTEDFACE.ZGENDERTYPE',

    CASE ZDETECTEDFACE.ZGLASSESTYPE
        WHEN 1 THEN '1 [Eye]'
        WHEN 2 THEN '2 [Sun]'
        WHEN 3 THEN '3 [None]'
        ELSE 'Unknown Value: ' || ZDETECTEDFACE.ZGLASSESTYPE
    END AS 'ZDETECTEDFACE.ZGLASSESTYPE',

    CASE ZDETECTEDFACE.ZFACIALHAIRTYPE
        WHEN 1 THEN '1 [None]'
        WHEN 2 THEN '2 [Beard/Mustache]'
        WHEN 3 THEN '3 [Goatee]'
        WHEN 5 THEN '5 [Stubble]'
        ELSE 'Unknown Value: ' || ZDETECTEDFACE.ZFACIALHAIRTYPE
    END AS 'ZDETECTEDFACE.ZFACIALHAIRTYPE',

    CASE ZDETECTEDFACE.ZHAIRTYPE
        WHEN 2 THEN '2 [Bald]'
        WHEN 3 THEN '3 [Not Bald]'
        ELSE 'Unknown Value: ' || ZDETECTEDFACE.ZHAIRTYPE
    END AS 'ZDETECTEDFACE.ZHAIRTYPE',

    ZASSET.ZORIGINALCOLORSPACE AS 'ZASSET.ZORIGINALCOLORSPACE',
    ZASSET.ZDURATION AS 'ZASSET.ZDURATION',
    ZASSET.ZVIDEOCPDURATIONVALUE AS 'ZASSET.ZVIDEOCPDURATIONVALUE',

    CASE ZASSET.ZCOMPLETE
        WHEN 1 THEN '1 [Yes]'
        ELSE ZASSET.ZCOMPLETE
    END AS 'ZASSET.ZCOMPLETE',

    CASE ZASSET.ZVISIBILITYSTATE
        WHEN 0 THEN '0 [Visible]'
        WHEN 1 THEN '1 [Photo Streams Data]'
        WHEN 2 THEN '2 [Burst]'
        ELSE 'Unknown Value: ' || ZASSET.ZVISIBILITYSTATE
    END AS 'ZASSET.ZVISIBILITYSTATE',

    CASE ZASSET.ZFAVORITE
        WHEN 0 THEN '0 [No]'
        WHEN 1 THEN '1 [Yes]'
        ELSE 'Unknown Value: ' || ZASSET.ZFAVORITE
    END AS 'ZASSET.ZFAVORITE',

    CASE ZASSET.ZHIDDEN
        WHEN 0 THEN '0 [Not Hidden]'
        WHEN 1 THEN '1 [File Hidden]'
        ELSE 'Unknown Value: ' || ZASSET.ZHIDDEN
    END AS 'ZASSET.ZHIDDEN',

    CASE ZASSET.ZTRASHEDSTATE
        WHEN 0 THEN '0 [Not In Trash]'
        WHEN 1 THEN '1 [In Trash]'
        ELSE 'Unknown Value: ' || ZASSET.ZTRASHEDSTATE
    END AS 'ZASSET.ZTRASHEDSTATE',

    CASE
        WHEN ZASSET.ZTRASHEDDATE IS NULL THEN '[N/A]'
        ELSE datetime(ZASSET.ZTRASHEDDATE + 978307200, 'UNIXEPOCH')
    END AS 'ZASSET.ZTRASHEDDATE(UTC)',

    ZADDITIONALASSETATTRIBUTES.ZVIEWCOUNT AS 'ZADDITIONALASSETATTRIBUTES.ZVIEWCOUNT',
    ZADDITIONALASSETATTRIBUTES.ZPLAYCOUNT AS 'ZADDITIONALASSETATTRIBUTES.ZPLAYCOUNT',
    ZADDITIONALASSETATTRIBUTES.ZSHARECOUNT AS 'ZADDITIONALASSETATTRIBUTES.ZSHARECOUNT',

    datetime(ZASSET.ZLASTSHAREDDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZLASTSHAREDDATE(UTC)',
    datetime(ZASSET.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZMODIFICATIONDATE(UTC)',

    CASE ZASSET.ZHASADJUSTMENTS
        WHEN 0 THEN '0 [No]'
        WHEN 1 THEN '1 [Yes]'
        ELSE 'Unknown Value: ' || ZASSET.ZHASADJUSTMENTS
    END AS 'ZASSET.ZHASADJUSTMENTS',

    datetime(ZASSET.ZADJUSTMENTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZADJUSTMENTTIMESTAMP(UTC)',

    ZADDITIONALASSETATTRIBUTES.ZORIGINALFILESIZE AS 'ZADDITIONALASSETATTRIBUTES.ZORIGINALFILESIZE',
    ZASSET.ZHEIGHT AS 'ZASSET.ZHEIGHT',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALHEIGHT AS 'ZADDITIONALASSETATTRIBUTES.ZORIGINALHEIGHT',
    ZASSET.ZWIDTH AS 'ZASSET.ZWIDTH',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALWIDTH AS 'ZADDITIONALASSETATTRIBUTES.ZORIGINALWIDTH',
    ZADDITIONALASSETATTRIBUTES.ZCAMERACAPTUREDEVICE AS 'ZADDITIONALASSETATTRIBUTES.ZCAMERACAPTUREDEVICE',

    CASE ZASSET.ZORIENTATION
        WHEN 1 THEN '1 [Horizontal (Left)]'
        WHEN 3 THEN '3 [Horizontal (Right)]'
        WHEN 6 THEN '6 [Vertical (Up)]'
        WHEN 8 THEN '8 [Vertical (Down)]'
        ELSE 'Unknown Value: ' || ZASSET.ZORIENTATION
    END AS 'ZASSET.ZORIENTATION',

    CASE ZADDITIONALASSETATTRIBUTES.ZORIGINALORIENTATION
        WHEN 1 THEN '1 [Horizontal (Left)]'
        WHEN 3 THEN '3 [Horizontal (Right)]'
        WHEN 6 THEN '6 [Vertical (Up)]'
        WHEN 8 THEN '8 [Vertical (Down)]'
        ELSE 'Unknown Value: ' || ZADDITIONALASSETATTRIBUTES.ZORIGINALORIENTATION
    END AS 'ZADDITIONALASSETATTRIBUTES.ZORIGINALORIENTATION',

    ZADDITIONALASSETATTRIBUTES.ZTIMEZONENAME AS 'ZADDITIONALASSETATTRIBUTES.ZTIMEZONENAME',
    ZADDITIONALASSETATTRIBUTES.ZTIMEZONEOFFSET AS 'ZADDITIONALASSETATTRIBUTES.ZTIMEZONEOFFSET',
    ZADDITIONALASSETATTRIBUTES.ZINFERREDTIMEZONEOFFSET AS 'ZADDITIONALASSETATTRIBUTES.ZINFERREDTIMEZONEOFFSET',
    ZASSET.ZLOCATIONDATA AS 'ZASSET.ZLOCATIONDATA',

    CASE ZASSET.ZLATITUDE
        WHEN -180.0 THEN '[-180.0]'
        ELSE ZASSET.ZLATITUDE
    END 'ZASSET.ZLATITUDE',

    CASE ZASSET.ZLONGITUDE
        WHEN -180.0 THEN '[-180.0]'
        ELSE ZASSET.ZLONGITUDE
    END 'ZASSET.ZLONGITUDE',

    CASE ZADDITIONALASSETATTRIBUTES.ZSHIFTEDLOCATIONISVALID
        WHEN 0 THEN '0 [No]'
        WHEN 1 THEN '1 [Yes]'
        ELSE 'Unknown Value: ' || ZADDITIONALASSETATTRIBUTES.ZSHIFTEDLOCATIONISVALID
    END AS 'ZADDITIONALASSETATTRIBUTES.ZSHIFTEDLOCATIONISVALID',

    CASE ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATAISVALID
        WHEN 0 THEN '0 [No - Check Scene Analysis]'
        WHEN 1 THEN '1 [Yes - Check Scene Analysis]'
        ELSE ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATAISVALID
    END AS 'ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATAISVALID',

    ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATA AS 'ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATA',
    ZASSET.ZTHUMBNAILINDEX AS 'ZASSET.ZTHUMBNAILINDEX ',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILWIDTH AS 'ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILWIDTH',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILHEIGHT AS 'ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILHEIGHT',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILOFFSET AS 'ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILOFFSET',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILLENGTH AS 'ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILLENGTH',
    ZASSET.ZMOMENT AS 'ZASSET.ZMOMENT',
    ZMOMENT.ZTITLE AS 'ZMOMENT.ZTITLE',

    datetime(ZMOMENT.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'ZMOMENT.ZSTARTDATE(UTC)',
    datetime(ZMOMENT.ZREPRESENTATIVEDATE + 978307200, 'UNIXEPOCH') AS 'ZMOMENT.ZREPRESENTATIVEDATE(UTC)',
    datetime(ZMOMENT.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'ZMOMENT.ZMODIFICATIONDATE(UTC)',
    datetime(ZMOMENT.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'ZMOMENT.ZENDDATE(UTC)',

    CASE ZMOMENT.ZTRASHEDSTATE
        WHEN 0 THEN '0 [Not In Trash]'
        WHEN 1 THEN '1 [In Trash]'
        ELSE 'Unknown Value: ' || ZMOMENT.ZTRASHEDSTATE
    END AS 'ZMOMENT.ZTRASHEDSTATE',

    CASE ZMOMENT.ZAPPROXIMATELATITUDE
        WHEN -180.0 THEN '[-180.0]'
        ELSE ZMOMENT.ZAPPROXIMATELATITUDE
    END AS 'ZMOMENT.ZAPPROXIMATELATITUDE',

    CASE ZMOMENT.ZAPPROXIMATELONGITUDE
        WHEN -180.0 THEN '[-180.0]'
        ELSE ZMOMENT.ZAPPROXIMATELONGITUDE
    END AS 'ZMOMENT.ZAPPROXIMATELONGITUDE',

    ZASSET.ZUUID AS 'ZASSET.ZUUID',
    ZASSET.ZMEDIAGROUPUUID AS 'ZASSET.ZMEDIAGROUPUUID',
    ZASSET.ZCLOUDASSETGUID AS 'ZASSET.ZCLOUDASSETGUID',
    ZADDITIONALASSETATTRIBUTES.ZPUBLICGLOBALUUID AS 'ZADDITIONALASSETATTRIBUTES.ZPUBLICGLOBALUUID',
    ZADDITIONALASSETATTRIBUTES.ZMASTERFINGERPRINT AS 'ZADDITIONALASSETATTRIBUTES.ZMASTERFINGERPRINT',
    ZADDITIONALASSETATTRIBUTES.ZADJUSTEDFINGERPRINT AS 'ZADDITIONALASSETATTRIBUTES.ZADJUSTEDFINGERPRINT',

    /* Source for each line of data */
    'Photos.sqlite; Table: ZASSETS(Z_PK:' || ZASSETS.Z_PK || ')' AS 'DATA_SOURCE'


FROM ZASSET
    LEFT JOIN ZMOMENT ON ZMOMENT.Z_PK = ZASSET.ZMOMENT
    JOIN ZADDITIONALASSETATTRIBUTES ON ZASSET.ZADDITIONALATTRIBUTES = ZADDITIONALASSETATTRIBUTES.Z_PK
    LEFT JOIN ZDETECTEDFACE ON ZDETECTEDFACE.ZASSET = ZASSET.Z_PK
    LEFT JOIN ZPERSON ON ZPERSON.Z_PK = ZDETECTEDFACE.ZPERSON
    LEFT JOIN Z_28ASSETS ON ZASSET.Z_PK = Z_28ASSETS.Z_3ASSETS
    LEFT JOIN ZGENERICALBUM ON ZGENERICALBUM.Z_PK = Z_28ASSETS.Z_28ALBUMS


WHERE ZASSET.ZFACEAREAPOINTS > 0


ORDER BY ZASSET.Z_PK ASC
