/*
File located at: /private/var/mobile/Media/PhotoData/Photos.sqlite
                 /private/var/mobile/Library/Photos/Libraries/Syndication.photoslibrary/database/Photos.sqlite
*/

SELECT
    /* Add a row number at the beggining of each row */
    ROW_NUMBER() OVER() AS 'RecordNo.',
    ZASSET.Z_PK AS 'ZASSET.Z_PK',
    ZASSET.ZDIRECTORY AS 'Directory',
    ZASSET.ZFILENAME AS 'FileName',
    ZASSET.ZADDITIONALATTRIBUTES AS 'AddAttributesKey',
    CASE ZASSET.ZKIND
        WHEN 0 THEN 'Photo'
        WHEN 1 THEN 'Video'
        ELSE ZASSET.ZKIND
    END AS 'FileType',
    ZASSET.ZUNIFORMTYPEIDENTIFIER AS 'MIMEType',
    CASE
        WHEN LENGTH(ZASSET.ZDATECREATED) = 18 THEN datetime((ZASSET.ZDATECREATED / 1000000000) + 978307200, 'UNIXEPOCH')
        WHEN LENGTH(ZASSET.ZDATECREATED) = 9 THEN datetime(ZASSET.ZDATECREATED + 978307200, 'UNIXEPOCH')
        ELSE datetime(ZASSET.ZDATECREATED + 978307200, 'UNIXEPOCH')
    END AS 'DateCreated(UTC)',
    ZADDITIONALASSETATTRIBUTES.ZEXIFTIMESTAMPSTRING AS 'EXIFTimeStamp',
    datetime(ZADDITIONALASSETATTRIBUTES.ZSCENEANALYSISTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'SceneAnalysisTimeStamp(UTC)',
    datetime(ZASSET.ZANALYSISSTATEMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'AnalysisStateModificationDate(UTC)',
    datetime(ZASSET.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'AddedDate(UTC)',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALFILENAME AS 'OriginalFilename',
    ZGENERICALBUM.ZTITLE AS 'AlbumTitle',
    -- ZADDITIONALASSETATTRIBUTES.ZCREATORBUNDLEID AS 'Creator Bundle ID',
    -- ZADDITIONALASSETATTRIBUTES.ZEDITORBUNDLEID AS 'Editor Bundle ID',
    CASE ZASSET.ZSAVEDASSETTYPE
        WHEN 0 THEN 'SavedFromOtherSource'
        WHEN 2 THEN 'PhotoStreamsData'
        WHEN 3 THEN 'Made/SavedWithThisDevice'
        WHEN 4 THEN 'DefaultRow'
        WHEN 7 THEN 'Deleted'
        ELSE ZASSET.ZSAVEDASSETTYPE
    END AS 'SavedAssetType',
    CASE
        WHEN ZASSET.ZFACEAREAPOINTS > 0 THEN 'Yes'
        ELSE ZASSET.ZFACEAREAPOINTS
    END AS 'FaceDetectedInPhoto',
    ZPERSON.ZDISPLAYNAME AS 'DisplayName',
    ZPERSON.ZFULLNAME AS 'FullName',
    ZPERSON.ZFACECOUNT AS 'FaceCount',
    ZDETECTEDFACE.ZPERSON AS 'Person',
    ZPERSON.ZCONTACTMATCHINGDICTIONARY AS 'ContactBlob',
    ZPERSON.ZPERSONUUID as 'PersonUUID',
    ZDETECTEDFACE.ZASSET AS 'DetectedFaceAsset',
    ZDETECTEDFACE.ZQUALITYMEASURE AS 'DetectedFaceQuality',
    CASE ZDETECTEDFACE.ZAGETYPE
        WHEN 1 THEN 'Baby/Toddler'
        WHEN 2 THEN 'Baby/Toddler'
        WHEN 3 THEN 'Child/YoungAdult'
        WHEN 4 THEN 'YoungAdult/Adult'
        WHEN 5 THEN 'Adult'
        ELSE ZDETECTEDFACE.ZAGETYPE
    END AS 'AgeTypeEstimate',
    CASE ZDETECTEDFACE.ZGENDERTYPE
        WHEN 1 THEN 'Male'
        WHEN 2 THEN 'Female'
        ELSE ZDETECTEDFACE.ZGENDERTYPE
    END AS 'Gender',
    CASE ZDETECTEDFACE.ZGLASSESTYPE
        WHEN 1 THEN 'Eye'
        WHEN 2 THEN 'Sun'
        WHEN 3 THEN 'None'
        ELSE ZDETECTEDFACE.ZGLASSESTYPE
    END AS 'GlassesType',
    CASE ZDETECTEDFACE.ZFACIALHAIRTYPE
        WHEN 1 THEN 'None'
        WHEN 2 THEN 'Beard/Mustache'
        WHEN 3 THEN 'Goatee'
        WHEN 5 THEN 'Stubble'
        ELSE ZDETECTEDFACE.ZFACIALHAIRTYPE
    END AS 'Facial Hair Type',
    CASE ZDETECTEDFACE.ZHAIRTYPE
        WHEN 2 THEN 'Bald'
        WHEN 3 THEN 'NotBald'
        ELSE ZDETECTEDFACE.ZHAIRTYPE
    END AS 'Baldness',
    ZASSET.ZORIGINALCOLORSPACE AS 'ColorSpace',
    ZASSET.ZDURATION AS 'Duration(Seconds)',
    ZASSET.ZVIDEOCPDURATIONVALUE AS 'VideoDuration',
    CASE ZASSET.ZCOMPLETE
        WHEN 1 THEN 'Yes'
        ELSE ZASSET.ZCOMPLETE
    END AS 'Complete',
    CASE ZASSET.ZVISIBILITYSTATE
        WHEN 0 THEN 'Visible'
        WHEN 1 THEN 'PhotoStreamsData'
        WHEN 2 THEN 'Burst'
        ELSE ZASSET.ZVISIBILITYSTATE
    END AS 'VisibilityState',
    CASE ZASSET.ZFAVORITE
        WHEN 0 THEN 'No'
        WHEN 1 THEN 'Yes'
        ELSE ZASSET.ZFAVORITE
    END AS 'IsFavorite',
    CASE ZASSET.ZHIDDEN
        WHEN 0 THEN 'NotHidden'
        WHEN 1 THEN 'FileHidden'
        ELSE ZASSET.ZHIDDEN
    END AS 'HiddenFile',
    CASE ZASSET.ZTRASHEDSTATE
        WHEN 1 THEN 'InTrash'
        WHEN 0 THEN 'NotInTrash'
        ELSE ZASSET.ZTRASHEDSTATE
    END AS 'TrashState',
    CASE
        WHEN ZASSET.ZTRASHEDDATE IS NULL THEN 'N/A'
        ELSE datetime(ZASSET.ZTRASHEDDATE + 978307200, 'UNIXEPOCH')
    END AS 'FileTrashDate(UTC)',
    ZADDITIONALASSETATTRIBUTES.ZVIEWCOUNT AS 'ViewCount',
    ZADDITIONALASSETATTRIBUTES.ZPLAYCOUNT AS 'PlayCount',
    ZADDITIONALASSETATTRIBUTES.ZSHARECOUNT AS 'ShareCount',
    datetime(ZASSET.ZLASTSHAREDDATE + 978307200, 'UNIXEPOCH') AS 'LastSharedDate(UTC)',
    datetime(ZASSET.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'FileModificationDate(UTC)',
    CASE ZASSET.ZHASADJUSTMENTS
        WHEN 0 THEN 'No'
        WHEN 1 THEN 'Yes'
        ELSE ZASSET.ZHASADJUSTMENTS
    END AS 'HasAdjustments',
    datetime(ZASSET.ZADJUSTMENTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'AdjustmentsTimeStamp(UTC)',
    printf("%,d", ZADDITIONALASSETATTRIBUTES.ZORIGINALFILESIZE) AS 'OriginalFileSize(bytes)',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALHEIGHT AS 'OriginalFileHeight',
    ZADDITIONALASSETATTRIBUTES.ZORIGINALWIDTH AS 'OriginalFileWidth',
    ZASSET.ZHEIGHT AS 'FileHeight',
    ZASSET.ZWIDTH AS 'Fil Width',
    CASE ZADDITIONALASSETATTRIBUTES.ZORIGINALORIENTATION
        WHEN 1 THEN 'Horizontal(Left)'
        WHEN 3 THEN 'Horizontal(Right)'
        WHEN 6 THEN 'Vertical(Up)'
        WHEN 8 THEN 'Vertical(Down)'
        ELSE ZASSET.ZORIENTATION
    END AS 'OriginalOrientation',
    CASE ZASSET.ZORIENTATION
        WHEN 1 THEN 'Horizontal(Left)'
        WHEN 3 THEN 'Horizontal(Right)'
        WHEN 6 THEN 'Vertical(Up)'
        WHEN 8 THEN 'Vertical(Down)'
        ELSE ZASSET.ZORIENTATION
    END AS 'Orientation',
    ZADDITIONALASSETATTRIBUTES.ZCAMERACAPTUREDEVICE AS 'CameraCaptureDevice',
    ZADDITIONALASSETATTRIBUTES.ZTIMEZONENAME AS 'TimeZoneName',
    ZADDITIONALASSETATTRIBUTES.ZTIMEZONEOFFSET AS 'TimeZoneOffset',
    ZADDITIONALASSETATTRIBUTES.ZINFERREDTIMEZONEOFFSET AS 'InferredTimeZoneOffset',
    ZASSET.ZLOCATIONDATA AS 'FileLocationData',
    CASE ZASSET.ZLATITUDE
        WHEN -180.0 THEN 'N/A'
        ELSE ZASSET.ZLATITUDE
    END 'Latitude',
    CASE ZASSET.ZLONGITUDE
        WHEN -180.0 THEN 'N/A'
        ELSE ZASSET.ZLONGITUDE
    END 'Longitude',
    CASE ZADDITIONALASSETATTRIBUTES.ZSHIFTEDLOCATIONISVALID
        WHEN 0 THEN 'No'
        WHEN 1 THEN 'Yes'
        ELSE ZADDITIONALASSETATTRIBUTES.ZSHIFTEDLOCATIONISVALID
    END AS 'ShiftedLocationValid',
    CASE ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATAISVALID
        WHEN 0 THEN 'No'
        WHEN 1 THEN 'Yes'
        ELSE ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATAISVALID
    END AS 'ReverseLocationDataIsValid',
    ZADDITIONALASSETATTRIBUTES.ZREVERSELOCATIONDATA AS 'OrgFileReverseLocationData',
    ZASSET.ZTHUMBNAILINDEX AS 'ThumbnailIndex',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILWIDTH AS 'EmbeddedThumbnailWidth',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILHEIGHT AS 'EmbeddedThumbnailHeight',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILOFFSET AS 'EmbeddedThumbnailOffset',
    ZADDITIONALASSETATTRIBUTES.ZEMBEDDEDTHUMBNAILLENGTH AS 'EmbeddedThumbnailLength',
    ZASSET.ZMOMENT AS 'MomentPK',
    ZMOMENT.ZTITLE AS 'MomentTitle',
    datetime(ZMOMENT.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'MomentStartDate(UTC)',
    datetime(ZMOMENT.ZREPRESENTATIVEDATE + 978307200, 'UNIXEPOCH') AS 'MomentRepresentativeDate(UTC)',
    datetime(ZMOMENT.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'MomentModificationDate(UTC)',
    datetime(ZMOMENT.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'MomentEndDate(UTC)',
    CASE ZMOMENT.ZAPPROXIMATELATITUDE
        WHEN -180.0 THEN 'N/A'
        ELSE ZMOMENT.ZAPPROXIMATELATITUDE
    END AS 'Moment Approx. Latitude',
    CASE ZMOMENT.ZAPPROXIMATELONGITUDE
        WHEN -180.0 THEN 'N/A'
        ELSE ZMOMENT.ZAPPROXIMATELONGITUDE
    END AS 'MomentApproxLongitude',
    ZASSET.ZUUID AS 'UUID',
    ZASSET.ZMEDIAGROUPUUID AS 'MediaGroupUUID',
    ZASSET.ZCLOUDASSETGUID AS 'CloudAssetGUID',
    ZADDITIONALASSETATTRIBUTES.ZPUBLICGLOBALUUID AS 'PublicGlobalUUID',
    ZADDITIONALASSETATTRIBUTES.ZMASTERFINGERPRINT AS 'MasterFingerprint',
    ZADDITIONALASSETATTRIBUTES.ZADJUSTEDFINGERPRINT AS 'AdjustedFingerprint',
    /* Source for each line of data */
    'File: /private/var/mobile/Media/PhotoData/Photos.sqlite' AS 'DatabaseFile',
    'Table: ZASSET(Z_PK:' || ZASSET.Z_PK || ')' AS 'DataSource'

FROM ZASSET
    LEFT JOIN ZMOMENT ON ZASSET.ZMOMENT = ZMOMENT.Z_PK
    JOIN ZADDITIONALASSETATTRIBUTES ON ZASSET.ZADDITIONALATTRIBUTES = ZADDITIONALASSETATTRIBUTES.Z_PK
    LEFT JOIN ZDETECTEDFACE ON ZADDITIONALASSETATTRIBUTES.ZASSET = ZDETECTEDFACE.ZASSET
    LEFT JOIN ZPERSON ON ZPERSON.Z_PK = ZDETECTEDFACE.ZPERSON
    LEFT JOIN Z_28ASSETS ON ZASSET.Z_PK = Z_28ASSETS.Z_3ASSETS
    LEFT JOIN ZGENERICALBUM ON ZGENERICALBUM.Z_PK = Z_28ASSETS.Z_28ALBUMS

ORDER BY ZASSET.Z_PK ASC
