/*
DLU: 15-Jul-2025

Query copied from https://github.com/ScottKjr3347/iOS_SWY_PL_Photos.sqlite_Queries/blob/main/iOS16/iOS16_SWY-PL_Phsql_Basic.txt
*/

SELECT
    ROW_NUMBER() OVER() AS 'Record #',
    ZASSET.Z_PK AS 'ZASSET.Z_PK ',
    ZASSET.ZSORTTOKEN AS 'ZASSET.ZSORTTOKEN',
    ZASSET.ZPROMOTIONSCORE AS 'ZASSET.ZPROMOTIONSCORE',

    CASE ZASSET.ZCOMPLETE
        WHEN 1 THEN '1 [Yes]'
    END AS 'ZASSET.ZCOMPLETE',

    ZADDASSETATTR.Z_PK AS 'ZADDASSETATTR.Z_PK',
    --[ZCLOUDMASTER.Z_PK = ZASSET.ZMaster]
    ZCLOUDMASTER.Z_PK AS 'ZCLOUDMASTER.Z_PK',
    --[ZASSET.ZMASTER = ZCLOUDMASTER.Z_PK]
    ZASSET.ZMASTER AS 'ZASSET.ZMASTER',
    --[ZASSET.ZEXTENDEDATTRIBUTES = ZEXTATTR.Z_PK]
    ZASSET.ZEXTENDEDATTRIBUTES AS 'ZASSET.ZEXTENDEDATTRIBUTES',
    --[ZEXTATTR.Z_PK = ZASSET.zExtendedAttributes]
    ZEXTATTR.Z_PK AS 'ZEXTATTR.Z_PK',
    --[CMzCldMastMedData-CldMast = ZCLOUDMASTER.Z_PK]
    CMzCldMastMedData.ZCLOUDMASTER AS 'CMzCldMastMedData.ZCLOUDMASTER',
    --[ZCLOUDMASTER.ZMEDIAMETADATA = zCldMastMedData.Z_PK]
    ZCLOUDMASTER.ZMEDIAMETADATA AS 'ZCLOUDMASTER.ZMEDIAMETADATA',
    --[CMzCldMastMedData.Z_PK=ZADDASSETATTR&ZCLOUDMASTER.ZMEDIAMETADATA]
    CMzCldMastMedData.Z_PK AS 'CMzCldMastMedData.Z_PK',
    CMzCldMastMedData.Z_ENT AS 'CMzCldMastMedData.Z_ENT',
    --[ZASSET.UUID = store.cloudphotodb]
    ZASSET.ZUUID AS 'ZASSET.ZUUID',
    --[ZASSET.Cloud_Asset_GUID = store.cloudphotodb]
    ZASSET.ZCLOUDASSETGUID AS 'ZASSET.ZCLOUDASSETGUID',
    ZASSET.ZCLOUDCOLLECTIONGUID AS 'ZASSET.ZCLOUDCOLLECTIONGUID',
    --[ZCLOUDMASTER.ZCLOUDMASTERGUID = store.cloudphotodb]
    ZCLOUDMASTER.ZCLOUDMASTERGUID AS 'ZCLOUDMASTER.ZCLOUDMASTERGUID',
    --[zGenAlbum.ZCLOUDGUID = store.cloudphotodb]
    zGenAlbum.ZCLOUDGUID AS 'ZGENERICALBUM.ZCLOUDGUID',
    --[zShare-Scope ID = store.cloudphotodb]
    ZSHARE.ZSCOPEIDENTIFIER AS 'ZSHARE.ZSCOPEIDENTIFIER',
    ZADDASSETATTR.ZORIGINALASSETSUUID AS 'ZADDASSETATTR.ZORIGINALASSETSUUID',
    ZADDASSETATTR.ZPUBLICGLOBALUUID AS 'ZADDASSETATTR.ZPUBLICGLOBALUUID',
    ZADDASSETATTR.ZMASTERFINGERPRINT AS 'ZADDASSETATTR.ZMASTERFINGERPRINT',
    ZADDASSETATTR.ZORIGINATINGASSETIDENTIFIER AS 'ZADDASSETATTR.ZORIGINATINGASSETIDENTIFIER',
    ZCLOUDMASTER.ZORIGINATINGASSETIDENTIFIER AS 'ZCLOUDMASTER.ZORIGINATINGASSETIDENTIFIER',
    ZINTERNALRESOURCE.ZFINGERPRINT AS 'ZINTERNALRESOURCE.ZFINGERPRINT',
    ZADDASSETATTR.ZADJUSTEDFINGERPRINT AS 'ZADDASSETATTR.ZADJUSTEDFINGERPRINT',
    ZUNMANAGEDADJUSTMENT.ZOTHERADJUSTMENTSFINGERPRINT AS 'ZUNMANAGEDADJUSTMENT.ZOTHERADJUSTMENTSFINGERPRINT',
    ZUNMANAGEDADJUSTMENT.ZSIMILARTOORIGINALADJUSTMENTSFINGERPRINT AS 'ZUNMANAGEDADJUSTMENT.ZSIMILARTOORIGINALADJUSTMENTSFINGERPRINT',

    ZASSET.ZDIRECTORY AS 'ZASSET.ZDIRECTORY',
    ZASSET.ZFILENAME AS 'ZASSET.ZFILENAME',
    ZADDASSETATTR.ZORIGINALFILENAME AS 'ZADDASSETATTR.ZORIGINALFILENAME',
    ZCLOUDMASTER.ZORIGINALFILENAME AS 'ZCLOUDMASTER.ZORIGINALFILENAME ',
    ZADDASSETATTR.ZSYNDICATIONIDENTIFIER AS 'ZADDASSETATTR.ZSYNDICATIONIDENTIFIER',

    datetime(ZASSET.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZADDEDDATE(UTC)',
	datetime(ZASSET.ZDATECREATED + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZDATECREATED(UTC)',
    datetime(ZCLOUDMASTER.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'ZCLOUDMASTER.ZCREATIONDATE(UTC)',
    datetime(ZINTERNALRESOURCE.ZCLOUDMASTERDATECREATED + 978307200, 'UNIXEPOCH') AS 'ZINTERNALRESOURCE.ZCLOUDMASTERDATECREATED(UTC)',
	datetime(ZASSET.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZMODIFICATIONDATE(UTC)',

    CASE ParentzGenAlbum.ZCLOUDLOCALSTATE
        WHEN 0 THEN '0 [iCloudPhotos ON=Asset In Shared/Other Album / iCloudPhotos OFF=Generic Album]'
        WHEN 1 THEN '1 [iCloudPhotos ON=Asset In Generic Album]'
        ELSE 'Unknown New Value: ' || ParentzGenAlbum.ZCLOUDLOCALSTATE || ''
    END AS 'ParentzGenAlbum.ZCLOUDLOCALSTATE',

    ParentzGenAlbum.ZTITLE AS 'ParentzGenAlbum.ZTITLE',

    datetime(ParentzGenAlbum.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'ParentzGenAlbum.ZCREATIONDATE(UTC)',
    datetime(zGenAlbum.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'zGenAlbum.ZCREATIONDATE(UTC)',

    CASE zGenAlbum.ZCLOUDLOCALSTATE
        WHEN 0 THEN '0 [iCloudPhotos ON=Asset In Shared/Other Album / iCloudPhotos OFF=Generic Album]'
        WHEN 1 THEN '1 [iCloudPhotos ON=Asset In Generic Album]'
        ELSE 'Unknown New Value: ' || zGenAlbum.ZCLOUDLOCALSTATE || ''
    END AS 'zGenAlbum.ZCLOUDLOCALSTATE',

    zGenAlbum.ZTITLE AS 'zGenAlbum.ZTITLE',

	CASE ZADDASSETATTR.ZIMPORTEDBY
        WHEN 0 THEN '0 [Cloud Other]'
        WHEN 1 THEN '1 [Native Back Camera]'
        WHEN 2 THEN '2 [Native Front Camera]'
        WHEN 3 THEN '3 [Third Party App]'
        WHEN 4 THEN '4 [Still Testing]'
        WHEN 5 THEN '5 [PhotoBooth PL Asset]'
        WHEN 6 THEN '6 [Third Party App]'
        WHEN 7 THEN '7 [iCloud Share Link CMMAsset]'
        WHEN 8 THEN '8 [System Package App]'
        WHEN 9 THEN '9 [Native App]'
        WHEN 10 THEN '10 [Still Testing]'
        WHEN 11 THEN '11 [Still Testing]'
        WHEN 12 THEN '12 [SWY Syndication PL]'
        ELSE 'Unknown New Value: ' || ZADDASSETATTR.ZIMPORTEDBY || ''
    END AS 'ZADDASSETATTR.ZIMPORTEDBY',

    datetime(ZCLOUDMASTER.ZIMPORTDATE + 978307200, 'UNIXEPOCH') AS 'ZCLOUDMASTER.ZIMPORTDATE(UTC)',

	CASE ZCLOUDMASTER.ZIMPORTEDBY
        WHEN 0 THEN '0 [Cloud Other]'
        WHEN 1 THEN '1 [Native Back Camera]'
        WHEN 2 THEN '2 [Native Front Camera]'
        WHEN 3 THEN '3 [Third Party App]'
        WHEN 4 THEN '4 [Still Testing]'
        WHEN 5 THEN '5 [PhotoBooth PL Asset]'
        WHEN 6 THEN '6 [Third Party App]'
        WHEN 7 THEN '7 [iCloud Share Link CMMAsset]'
        WHEN 8 THEN '8 [System Package App]'
        WHEN 9 THEN '9 [Native App]'
        WHEN 10 THEN '10 [Still Testing]'
        WHEN 11 THEN '11 [Still Testing]'
        WHEN 12 THEN '12 [SWY Syndication PL]'
        ELSE 'Unknown New Value: ' || ZCLOUDMASTER.ZIMPORTEDBY || ''
    END AS 'ZCLOUDMASTER.ZIMPORTEDBY',

    ZADDASSETATTR.ZIMPORTEDBYBUNDLEIDENTIFIER AS 'ZADDASSETATTR.ZIMPORTEDBYBUNDLEIDENTIFIER',
    ZADDASSETATTR.ZIMPORTEDBYDISPLAYNAME AS 'ZADDASSETATTR.ZIMPORTEDBYDISPLAYNAME',
    ZCLOUDMASTER.ZIMPORTEDBYBUNDLEIDENTIFIER AS 'ZCLOUDMASTER.ZIMPORTEDBYBUNDLEIDENTIFIER',
    ZCLOUDMASTER.ZIMPORTEDBYDISPLAYNAME AS 'ZCLOUDMASTER.ZIMPORTEDBYDISPLAYNAME',
    --hex(ZASSET.ZIMAGEREQUESTHINTS) AS 'ZASSET.ZIMAGEREQUESTHINTS(HEX)',

    CASE ZASSET.ZBUNDLESCOPE
        WHEN 0 THEN '0 [iCloudPhotos ON=Not In Shared Album iCloudPhotos OFF=On Local Device]'
        WHEN 1 THEN '1 [SWY Syndication CMMAsset]'
        WHEN 2 THEN '2 [iCloudPhotos ON=Asset In Cloud Shared Album]'
        WHEN 3 THEN '3 [iCloudPhotos ON=SWY Syndication Asset]'
        ELSE 'Unknown New Value: ' || ZASSET.ZBUNDLESCOPE || ''
    END AS 'ZASSET.ZBUNDLESCOPE',

    CASE ZASSET.ZCLOUDISMYASSET
        WHEN 0 THEN '0 [Not My Asset in Shared Album]'
        WHEN 1 THEN '1 [My Asset in Shared Album]'
        ELSE 'Unknown New Value: ' || ZASSET.ZCLOUDISMYASSET || ''
    END AS 'ZASSET.ZCLOUDISMYASSET',

    CASE ZASSET.ZCLOUDISDELETABLE
        WHEN 0 THEN '0 [No]'
        WHEN 1 THEN '1 [Yes]'
        ELSE 'Unknown New Value: ' || ZASSET.ZCLOUDISDELETABLE || ''
    END AS 'ZASSET.ZCLOUDISDELETABLE',

    CASE ZASSET.ZCLOUDLOCALSTATE
        WHEN 0 THEN '0 [iCloudPhotos ON=Asset In Shared Other Album/iCloudPhotos OFF=Not Synced]'
        WHEN 1 THEN '1 [iCloudPhotos ON=Asset Synced with iCloud]'
        ELSE 'Unknown New Value: ' || ZASSET.ZCLOUDLOCALSTATE || ''
    END AS 'ZASSET.ZCLOUDLOCALSTATE',

    CASE ZASSET.ZVISIBILITYSTATE
        WHEN 0 THEN '0 [Visible Photo Library]'
        WHEN 2 THEN '2 [Not Visible Photo Library]'
        ELSE 'Unknown New Value: ' || ZASSET.ZVISIBILITYSTATE || ''
    END AS 'ZASSET.ZVISIBILITYSTATE',

    ZEXTATTR.ZCAMERAMAKE AS 'ZEXTATTR.ZCAMERAMAKE',
    ZEXTATTR.ZCAMERAMODEL AS 'ZEXTATTR.ZCAMERAMODEL',
    ZEXTATTR.ZLENSMODEL AS 'ZEXTATTR.ZLENSMODEL',

    CASE ZEXTATTR.ZFLASHFIRED
        WHEN 0 THEN '0 [No Flash]'
        WHEN 1 THEN '1 [Flash Fired]'
        ELSE 'Unknown New Value: ' || ZEXTATTR.ZFLASHFIRED || ''
    END AS 'ZEXTATTR.ZFLASHFIRED',

    ZEXTATTR.ZFOCALLENGTH AS 'ZEXTATTR.ZFOCALLENGTH',
    ZEXTATTR.ZFOCALLENGTHIN35MM AS 'ZEXTATTR.ZFOCALLENGTHIN35MM',
    ZEXTATTR.ZDIGITALZOOMRATIO AS 'ZEXTATTR.ZDIGITALZOOMRATIO',

    CASE ZASSET.ZDERIVEDCAMERACAPTUREDEVICE
        WHEN 0 THEN '0 [Back Camera/Other]'
        WHEN 1 THEN '1 [Front Camera]'
        ELSE 'Unknown New Value: ' || ZASSET.ZDERIVEDCAMERACAPTUREDEVICE || ''
    END AS 'ZASSET.ZDERIVEDCAMERACAPTUREDEVICE',

    CASE ZADDASSETATTR.ZCAMERACAPTUREDEVICE
        WHEN 0 THEN '0 [Back Camera/Other]'
        WHEN 1 THEN '1 [Front Camera]'
        ELSE 'Unknown New Value: ' || ZADDASSETATTR.ZCAMERACAPTUREDEVICE || ''
    END AS 'ZADDASSETATTR.ZCAMERACAPTUREDEVICE',

    CASE ZASSET.ZSAVEDASSETTYPE
        WHEN 0 THEN '0 [Saved via other source]'
        WHEN 1 THEN '1 [Still Testing]'
        WHEN 2 THEN '2 [Still Testing]'
        WHEN 3 THEN '3 [SWY Syndicaion PL Asset Not In Local PL]'
        WHEN 4 THEN '4 [Photo Cloud Sharing Data Asset]'
        WHEN 5 THEN '5 [Still Testing]'
        WHEN 6 THEN '6 [Cloud Photo Library Asset]'
        WHEN 7 THEN '7 [Still Testing]'
        WHEN 8 THEN '8 [iCloud Link CloudMaster Moment Asset]'
        WHEN 12 THEN '12 [SWY Syndicaion PL Asset In Local PL]'
        ELSE 'Unknown New Value: ' || ZASSET.ZSAVEDASSETTYPE || ''
    END AS 'ZASSET.ZSAVEDASSETTYPE',

    CASE ZASSET.ZSAVEDASSETTYPE
        WHEN 0 THEN '0 [Saved via other source]'
        WHEN 1 THEN '1 [Still Testing]'
        WHEN 2 THEN '2 [Still Testing]'
        WHEN 3 THEN '3 [Local Photo Library Asset]'
        WHEN 4 THEN '4 [Photo Cloud Sharing Data Asset]'
        WHEN 5 THEN '5 [PhotoBooth Photo Library Asset]'
        WHEN 6 THEN '6 [Cloud Photo Library Asset]'
        WHEN 7 THEN '7 [Still Testing]'
        WHEN 8 THEN '8 [iCloud Link CloudMaster Moment Asset]'
        WHEN 12 THEN '12 [SWY Syndication PL Asset/Auto Displayed in LPL]'
        ELSE 'Unknown New Value: ' || ZASSET.ZSAVEDASSETTYPE || ''
    END AS 'ZASSET.ZSAVEDASSETTYPE',

    CASE ZASSET.ZSYNDICATIONSTATE
        WHEN 0 THEN '0 [Received SWY Synd Asset]'
        WHEN 1 THEN '1 [Sent SWY Synd Asset]'
        WHEN 2 THEN '2 [Manually Saved SWY Synd Asset]'
        WHEN 8 THEN '8 [SWY Linked Asset was Visible On Device User Deleted Link]'
        WHEN 10 THEN '10 [Manually Saved SWY Synd Asset User Deleted From LPL]'
        ELSE 'Unknown New Value: ' || ZASSET.ZSYNDICATIONSTATE || ''
    END AS 'ZASSET.ZSYNDICATIONSTATE',

    ZADDASSETATTR.ZSYNDICATIONHISTORY AS 'ZADDASSETATTR.ZSYNDICATIONHISTORY',
    zMedAnlyAstAttr.ZSYNDICATIONPROCESSINGVERSION AS 'zMedAnlyAstAttr.ZSYNDICATIONPROCESSINGVERSION',

    CASE zMedAnlyAstAttr.ZSYNDICATIONPROCESSINGVALUE
        WHEN 0 THEN '0 [NA]'
        WHEN 1 THEN '1 [Still Testing Wide Camera JPG]'
        WHEN 2 THEN '2 [Still Testing Telephoto Camear Lens]'
        WHEN 4 THEN '4 [Still Testing SWY Asset OrigAssetImport SystemPackageApp]'
        WHEN 16 THEN '16 [Still Testing]'
        WHEN 1024 THEN '1024 [Still Testing SWY Asset OrigAssetImport Native Camera]'
        WHEN 2048 THEN '2048 [Still Testing]'
        WHEN 4096 THEN '4096 [Still Testing SWY Asset Manually Saved]'
        ELSE 'Unknown New Value: ' || zMedAnlyAstAttr.ZSYNDICATIONPROCESSINGVALUE || ''
    END AS 'zMedAnlyAstAttr.ZSYNDICATIONPROCESSINGVALUE',

    CASE ZADDASSETATTR.ZDATECREATEDSOURCE
        WHEN 0 THEN '0 [Cloud Asset]'
        WHEN 1 THEN '1 [Local Asset EXIF]'
        WHEN 3 THEN '3 [Local Asset No EXIF]'
        ELSE 'Unknown New Value: ' || ZADDASSETATTR.ZDATECREATEDSOURCE || ''
    END AS 'ZADDASSETATTR.ZDATECREATEDSOURCE',

    ZADDASSETATTR.ZTIMEZONENAME AS 'ZADDASSETATTR.ZTIMEZONENAME',
    ZADDASSETATTR.ZTIMEZONEOFFSET AS 'ZADDASSETATTR.ZTIMEZONEOFFSET',
    ZADDASSETATTR.ZINFERREDTIMEZONEOFFSET AS 'ZADDASSETATTR.ZINFERREDTIMEZONEOFFSET',
    ZADDASSETATTR.ZEXIFTIMESTAMPSTRING AS 'ZADDASSETATTR.ZEXIFTIMESTAMPSTRING',

    CASE ZCLOUDMASTER.ZCLOUDLOCALSTATE
        WHEN 0 THEN '0 [Not Synced with Cloud]'
        WHEN 1 THEN '1 [Pending Upload]'
        WHEN 2 THEN '2 [Still Testing]'
        WHEN 3 THEN '3 [Synced with Cloud]'
        ELSE 'Unknown New Value: ' || ZCLOUDMASTER.ZCLOUDLOCALSTATE || ''
    END AS 'ZCLOUDMASTER.ZCLOUDLOCALSTATE',

    ZASSET.ZIMPORTSESSION AS 'ZASSET.ZIMPORTSESSION',
    ZADDASSETATTR.ZIMPORTSESSIONID AS 'ZADDASSETATTR.ZIMPORTSESSIONID',

    datetime(ZADDASSETATTR.ZALTERNATEIMPORTIMAGEDATE + 978307200, 'UNIXEPOCH') AS 'ZADDASSETATTR.ZALTERNATEIMPORTIMAGEDATE(UTC)',

    ZCLOUDMASTER.ZIMPORTSESSIONID AS 'ZCLOUDMASTER.ZIMPORTSESSIONID',

    datetime(ZASSET.ZCLOUDBATCHPUBLISHDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZCLOUDBATCHPUBLISHDATE(UTC)',
    datetime(ZASSET.ZCLOUDSERVERPUBLISHDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZCLOUDSERVERPUBLISHDATE(UTC)',

    ZASSET.ZCLOUDDOWNLOADREQUESTS AS 'ZASSET.ZCLOUDDOWNLOADREQUESTS',
    ZASSET.ZCLOUDBATCHID AS 'ZASSET.ZCLOUDBATCHID',

    datetime(ZADDASSETATTR.ZLASTUPLOADATTEMPTDATE + 978307200, 'UNIXEPOCH') AS 'ZADDASSETATTR.ZLASTUPLOADATTEMPTDATE(UTC)',

    ZADDASSETATTR.ZUPLOADATTEMPTS AS 'ZADDASSETATTR.ZUPLOADATTEMPTS',

    CASE ZASSET.ZLATITUDE
        WHEN -180.0 THEN '[-180.0]'
        ELSE ZASSET.ZLATITUDE
    END AS 'ZASSET.ZLATITUDE',

    ZEXTATTR.ZLATITUDE AS 'ZEXTATTR.ZLATITUDE',

    CASE ZASSET.ZLONGITUDE
        WHEN -180.0 THEN '[-180.0]'
        ELSE ZASSET.ZLONGITUDE
    END AS 'ZASSET.ZLONGITUDE',

    ZEXTATTR.ZLONGITUDE AS 'ZEXTATTR.ZLONGITUDE',

    CASE ZADDASSETATTR.ZGPSHORIZONTALACCURACY
        WHEN -1.0 THEN '-1.0'
        ELSE ZADDASSETATTR.ZGPSHORIZONTALACCURACY
    END AS 'ZADDASSETATTR.ZGPSHORIZONTALACCURACY',

    --hex(ZASSET.ZLOCATIONDATA) AS 'ZASSET.ZLOCATIONDATA(HEX)',
    --hex(ZADDASSETATTR.ZREVERSELOCATIONDATA) AS 'ZADDASSETATTR.ZREVERSELOCATIONDATA(HEX NSKeyed .plist)',

    CASE ZADDASSETATTR.ZSHIFTEDLOCATIONISVALID
        WHEN 0 THEN '0 [Shifted Location Not Valid]'
        WHEN 1 THEN '1 [Shifted Location Valid]'
    END AS 'ZADDASSETATTR.ZSHIFTEDLOCATIONISVALID',

    ZADDASSETATTR.ZSHIFTEDLOCATIONDATA AS 'ZADDASSETATTR.ZSHIFTEDLOCATIONDATA',
    ZADDASSETATTR.ZLOCATIONHASH AS 'ZADDASSETATTR.ZLOCATIONHASH',

    CASE AAAzCldMastMedData.Z_OPT
        WHEN 1 THEN '1 [Still Testing Cloud]'
        WHEN 2 THEN '2 [Still Testing This Device]'
        WHEN 3 THEN '3 [Still Testing Muted]'
        WHEN 4 THEN '4 [Still Testing Unknown]'
        WHEN 5 THEN '5 [Still Testing Unknown]'
        ELSE 'Unknown New Value: ' || AAAzCldMastMedData.Z_OPT || ''
    END AS 'AAAzCldMastMedData.Z_OPT',

    ZADDASSETATTR.ZMEDIAMETADATATYPE AS 'ZADDASSETATTR.ZMEDIAMETADATATYPE',
    --hex(AAAzCldMastMedData.ZDATA) AS 'AAAzCldMastMedData.ZDATA(HEX)',

    CASE CMzCldMastMedData.Z_OPT
        WHEN 1 THEN '1 [Still Testing Has CldMastAsset]'
        WHEN 2 THEN '2 [Still Testing Local Asset]'
        WHEN 3 THEN '3 [Still Testing Muted]'
        WHEN 4 THEN '4 [Still Testing Unknown]'
        WHEN 5 THEN '5 [Still Testing Unknown]'
        ELSE 'Unknown New Value: ' || CMzCldMastMedData.Z_OPT || ''
    END AS 'CMzCldMastMedData.Z_OPT',

    ZCLOUDMASTER.ZMEDIAMETADATATYPE AS 'ZCLOUDMASTER.ZMEDIAMETADATATYPE',
    --hex(CMzCldMastMedData.ZDATA) AS 'CMzCldMastMedData.ZDATA(HEX)',

    CASE ZASSET.ZSEARCHINDEXREBUILDSTATE
        WHEN 0 THEN '0 [Still Testing]'
        ELSE 'Unknown New Value: ' || ZASSET.ZSEARCHINDEXREBUILDSTATE || ''
    END AS 'ZASSET.ZSEARCHINDEXREBUILDSTATE',

    CASE ZASSET.ZORIENTATION
        WHEN 1 THEN '1 [Video Default/Adjustment/Horizontal Camera (left)]'
        WHEN 2 THEN '2 [Horizontal Camera (right)]'
        WHEN 3 THEN '3 [Horizontal Camera (right)]'
        WHEN 4 THEN '4 [Horizontal Camera (left)]'
        WHEN 5 THEN '5 [Vertical Camera (top)]'
        WHEN 6 THEN '6 [Vertical Camera (top)]'
        WHEN 7 THEN '7 [Vertical Camera (bottom)]'
        WHEN 8 THEN '8 [Vertical Camera (bottom)]'
        ELSE 'Unknown New Value: ' || ZASSET.ZORIENTATION || ''
    END AS 'ZASSET.ZORIENTATION',

    CASE ZADDASSETATTR.ZORIGINALORIENTATION
        WHEN 1 THEN '1 [Video Default/Adjustment/Horizontal Camera (left)]'
        WHEN 2 THEN '2 [Horizontal Camera (right)]'
        WHEN 3 THEN '3 [Horizontal Camera (right)]'
        WHEN 4 THEN '4 [Horizontal Camera (left)]'
        WHEN 5 THEN '5 [Vertical Camera (top)]'
        WHEN 6 THEN '6 [Vertical Camera (top)]'
        WHEN 7 THEN '7 [Vertical Camera (bottom)]'
        WHEN 8 THEN '8 [Vertical Camera (bottom)]'
        ELSE 'Unknown New Value: ' || ZASSET.ZORIENTATION || ''
    END AS 'ZADDASSETATTR.ZORIGINALORIENTATION',

    CASE ZINTERNALRESOURCE.ZORIENTATION
        WHEN 0 THEN '0 [NA]'
        WHEN 1 THEN '1 [Video Default/Adjustment/Horizontal Camera (left)]'
        WHEN 2 THEN '2 [Horizontal Camera (right)]'
        WHEN 3 THEN '3 [Horizontal Camera (right)]'
        WHEN 4 THEN '4 [Horizontal Camera (left)]'
        WHEN 5 THEN '5 [Vertical Camera (top)]'
        WHEN 6 THEN '6 [Vertical Camera (top)]'
        WHEN 7 THEN '7 [Vertical Camera (bottom)]'
        WHEN 8 THEN '8 [Vertical Camera (bottom)]'
        ELSE 'Unknown New Value: ' || ZINTERNALRESOURCE.ZORIENTATION || ''
    END AS 'ZINTERNALRESOURCE.ZORIENTATION',

    CASE ZASSET.ZKIND
        WHEN 0 THEN '0 [Photo]'
        WHEN 1 THEN '1 [Video]'
    END AS 'ZASSET.ZKIND',

    CASE ZASSET.ZKINDSUBTYPE
        WHEN 0 THEN '0 [Still Photo]'
        WHEN 2 THEN '2 [Live Photo]'
        WHEN 10 THEN '10 [SpringBoard Screenshot]'
        WHEN 100 THEN '100 [Video]'
        WHEN 101 THEN '101 [Slow Mo Video]'
        WHEN 102 THEN '102 [Time lapse Video]'
        WHEN 103 THEN '103 [Replay Screen Recording]'
        ELSE 'Unknown New Value: ' || ZASSET.ZKINDSUBTYPE || ''
    END AS 'ZASSET.ZKINDSUBTYPE',

    CASE ZADDASSETATTR.ZCLOUDKINDSUBTYPE
        WHEN 0 THEN '0 [Still Photo]'
        WHEN 1 THEN '1 [Still Testing]'
        WHEN 2 THEN '2 [Live Photo]'
        WHEN 3 THEN '3 [Screenshot]'
        WHEN 10 THEN '10 [SpringBoard Screenshot]'
        WHEN 100 THEN '100 [Video]'
        WHEN 101 THEN '101 [Slow Mo Video]'
        WHEN 102 THEN '102 [Time lapse Video]'
        WHEN 103 THEN '103 [Replay Screen Recording]'
        ELSE 'Unknown New Value: ' || ZADDASSETATTR.ZCLOUDKINDSUBTYPE || ''
    END AS 'ZADDASSETATTR.ZCLOUDKINDSUBTYPE',

    CASE ZASSET.ZPLAYBACKSTYLE
        WHEN 1 THEN '1 [Image]'
        WHEN 2 THEN '2 [Image Animated]'
        WHEN 3 THEN '3 [Live Photo]'
        WHEN 4 THEN '4 [Video]'
        WHEN 5 THEN '5 [Video Looping]'
        ELSE 'Unknown New Value: ' || ZASSET.ZPLAYBACKSTYLE || ''
    END AS 'ZASSET.ZPLAYBACKSTYLE',

    ZASSET.ZPLAYBACKVARIATION AS 'ZASSET.ZPLAYBACKVARIATION',
    ZASSET.ZDURATION AS 'ZASSET.ZDURATION',
    ZEXTATTR.ZDURATION AS 'ZEXTATTR.ZDURATION',
    ZASSET.ZVIDEOCPDURATIONVALUE AS 'ZASSET.ZVIDEOCPDURATIONVALUE',
    ZADDASSETATTR.ZVIDEOCPDURATIONTIMESCALE AS 'ZADDASSETATTR.ZVIDEOCPDURATIONTIMESCALE',
    ZASSET.ZVIDEOCPVISIBILITYSTATE AS 'ZASSET.ZVIDEOCPVISIBILITYSTATE',
    ZADDASSETATTR.ZVIDEOCPDISPLAYVALUE AS 'ZADDASSETATTR.ZVIDEOCPDISPLAYVALUE',
    ZADDASSETATTR.ZVIDEOCPDISPLAYTIMESCALE AS 'ZADDASSETATTR.ZVIDEOCPDISPLAYTIMESCALE',
    --[ZINTERNALRESOURCE.ZASSET = ZASSET.zPK]
    ZINTERNALRESOURCE.ZASSET AS 'ZINTERNALRESOURCE.ZASSET',
    ZINTERNALRESOURCE.Z_PK AS 'ZINTERNALRESOURCE.Z_PK',
    ZINTERNALRESOURCE.Z_ENT AS 'ZINTERNALRESOURCE.Z_ENT',
    ZINTERNALRESOURCE.Z_OPT AS 'ZINTERNALRESOURCE.Z_OPT',
    ZINTERNALRESOURCE.ZQUALITYSORTVALUE AS 'ZINTERNALRESOURCE.ZQUALITYSORTVALUE',

    CASE ZINTERNALRESOURCE.ZDATASTORECLASSID
        WHEN 0 THEN '0 [LPL Asset CPL Asset]'
        WHEN 1 THEN '1 [Still Testing]'
        WHEN 2 THEN '2 [Photo Cloud Sharing Asset]'
        WHEN 3 THEN '3 [SWY Syndication Asset]'
        ELSE 'Unknown New Value: ' || ZINTERNALRESOURCE.ZDATASTORECLASSID || ''
    END AS 'ZINTERNALRESOURCE.ZDATASTORECLASSID',

    CASE ZASSET.ZCLOUDPLACEHOLDERKIND
        WHEN 0 THEN '0 [Local&CloudMaster Asset]'
        WHEN 1 THEN '1 [Still Testing]'
        WHEN 2 THEN '2 [Still Testing]'
        WHEN 3 THEN '3 [JPG Asset Only PhotoData/Thumb/V2]'
        WHEN 4 THEN '4 [LPL JPG Asset CPL Asset HEIC JPG JPEG MOV PNG]'
        WHEN 5 THEN '5 [Asset synced via iCloud Photos 2 Device]'
        WHEN 6 THEN '6 [Still Testing]'
        WHEN 7 THEN '7 [LPL poster JPG Asset CPL Asset MP4]'
        WHEN 8 THEN '8 [LPL JPG Asset CPL Asset LivePhoto MOV]'
        WHEN 9 THEN '9 [CPL MP4 Asset Saved 2 LPL]'
        ELSE 'Unknown New Value: ' || ZASSET.ZCLOUDPLACEHOLDERKIND || ''
    END AS 'ZASSET.ZCLOUDPLACEHOLDERKIND',

    CASE ZINTERNALRESOURCE.ZLOCALAVAILABILITY
        WHEN -1 THEN '(-1) [IR Asset Not Available Local Device]'
        WHEN 1 THEN '1 [IR Asset Available Local Device]'
        WHEN -32768 THEN '(-32768) [IR Asset SWY Linked Asset]'
        ELSE 'Unknown New Value: ' || ZINTERNALRESOURCE.ZLOCALAVAILABILITY || ''
    END AS 'ZINTERNALRESOURCE.ZLOCALAVAILABILITY',

    CASE ZINTERNALRESOURCE.ZLOCALAVAILABILITYTARGET
        WHEN 0 THEN '0 [Still Testing]'
        ELSE 'Unknown New Value: ' || ZINTERNALRESOURCE.ZLOCALAVAILABILITYTARGET || ''
    END AS 'ZINTERNALRESOURCE.ZLOCALAVAILABILITYTARGET',

    CASE ZINTERNALRESOURCE.ZCLOUDLOCALSTATE
        WHEN 0 THEN '0 [IR Asset Not Synced No IR CldMast Date Created]'
        WHEN 1 THEN '1 [IR Asset Pening Upload]'
        WHEN 2 THEN '2 [IR Asset Photo Cloud Share Asset On Local Device]'
        WHEN 3 THEN '3 [IR Asset Synced iCloud]'
        ELSE 'Unknown New Value: ' || ZINTERNALRESOURCE.ZCLOUDLOCALSTATE || ''
    END AS 'ZINTERNALRESOURCE.ZCLOUDLOCALSTATE',

    CASE ZINTERNALRESOURCE.ZREMOTEAVAILABILITY
        WHEN 0 THEN '0 [IR Asset Not Available Remotely]'
        WHEN 1 THEN '1 [IR Asset Available Remotely]'
        ELSE 'Unknown New Value: ' || ZINTERNALRESOURCE.ZREMOTEAVAILABILITY || ''
    END AS 'ZINTERNALRESOURCE.ZREMOTEAVAILABILITY',

    CASE ZINTERNALRESOURCE.ZREMOTEAVAILABILITYTARGET
        WHEN 0 THEN '0 [Still Testing]'
        WHEN 1 THEN '1 [Still Testing]'
        ELSE 'Unknown New Value: ' || ZINTERNALRESOURCE.ZREMOTEAVAILABILITYTARGET || ''
    END AS 'ZINTERNALRESOURCE.ZREMOTEAVAILABILITYTARGET',

    ZINTERNALRESOURCE.ZTRANSIENTCLOUDMASTER AS 'ZINTERNALRESOURCE.ZTRANSIENTCLOUDMASTER',
    ZINTERNALRESOURCE.ZSIDECARINDEX AS 'ZINTERNALRESOURCE.ZSIDECARINDEX',
    ZINTERNALRESOURCE.ZFILEID AS 'ZINTERNALRESOURCE.ZFILEID',

    CASE ZINTERNALRESOURCE.ZVERSION
        WHEN 0 THEN '0 [IR Asset Standard]'
        WHEN 1 THEN '1 [Still Testing]'
        WHEN 2 THEN '2 [IR Asset Adjustments Mutation]'
        WHEN 3 THEN '3 [IR Asset No IR CldMastDateCreated]'
        ELSE 'Unknown New Value: ' || ZINTERNALRESOURCE.ZVERSION || ''
    END AS 'ZINTERNALRESOURCE.ZVERSION',

    ZADDASSETATTR.ZORIGINALFILESIZE AS 'ZADDASSETATTR.ZORIGINALFILESIZE',

    CASE ZINTERNALRESOURCE.ZRESOURCETYPE
        WHEN 0 THEN '0 [Photo]'
        WHEN 1 THEN '1 [Video]'
        WHEN 3 THEN '3 [Live Photo]'
        WHEN 5 THEN '5 [Adjustement Data]'
        WHEN 6 THEN '6 [Screenshot]'
        WHEN 9 THEN '9 [Alternate Photo 3rdPartyApp Still Testing]'
        WHEN 13 THEN '13 [Movie]'
        WHEN 14 THEN '14 [Wallpaper]'
        ELSE 'Unknown New Value: ' || ZINTERNALRESOURCE.ZRESOURCETYPE || ''
    END AS 'ZINTERNALRESOURCE.ZRESOURCETYPE',

    hex(ZINTERNALRESOURCE.ZDATASTOREKEYDATA) AS 'ZINTERNALRESOURCE.ZDATASTOREKEYDATA',

    CASE ZINTERNALRESOURCE.ZDATASTORESUBTYPE
        WHEN 0 THEN '0 [No Cloud Inter Resource]'
        WHEN 1 THEN '1 [Main Asset Orig Size]'
        WHEN 2 THEN '2 [Photo with Adjustments]'
        WHEN 3 THEN '3 [JPG Large Thumb]'
        WHEN 4 THEN '4 [JPG Med Thumb]'
        WHEN 5 THEN '5 [JPG Small Thumb]'
        WHEN 6 THEN '6 [Video Med Data]'
        WHEN 7 THEN '7 [Video Small Data]'
        WHEN 8 THEN '8 [MP4 Cloud Share]'
        WHEN 9 THEN '9 [Still Testing]'
        WHEN 10 THEN '10 [3rdPartyApp thumb Still Testing]'
        WHEN 11 THEN '11 [Still Test]'
        WHEN 12 THEN '12 [Still Test]'
        WHEN 13 THEN '13 [PNG Optimized CPLAsset]'
        WHEN 14 THEN '14 [Wallpaper]'
        WHEN 15 THEN '15 [Has Markup and Adjustments]'
        WHEN 16 THEN '16 [Video with Adjustments]'
        WHEN 17 THEN '17 [RAW Photo]'
        WHEN 18 THEN '18 [Live Photo Video Optimized CPLAsset]'
        WHEN 19 THEN '19 [Live Photo with Adjustments]'
        WHEN 20 THEN '20 [Still Test]'
        WHEN 21 THEN '21 [Still Test]'
        WHEN 22 THEN '22 [Adjust Mutation AAE Asset]'
        WHEN 23 THEN '23 [Still Test]'
        WHEN 24 THEN '24 [Still Test]'
        WHEN 25 THEN '25 [Still Test]'
        WHEN 26 THEN '26 [MOV Optimized CPLAsset]'
        WHEN 27 THEN '27 [Still Test]'
        WHEN 28 THEN '28 [MOV Med hdr Data]'
        ELSE 'Unknown New Value: ' || ZINTERNALRESOURCE.ZDATASTORESUBTYPE || ''
    END AS 'ZINTERNALRESOURCE.ZDATASTORESUBTYPE',

    CASE ZINTERNALRESOURCE.ZCLOUDSOURCETYPE
        WHEN 0 THEN '0 [NA]'
        WHEN 1 THEN '1 [Main Asset Orig Size]'
        WHEN 2 THEN '2 [Photo with Adjustments]'
        WHEN 3 THEN '3 [JPG Large Thumb]'
        WHEN 4 THEN '4 [JPG Med Thumb]'
        WHEN 5 THEN '5 [JPG Small Thumb]'
        WHEN 6 THEN '6 [Video Med Data]'
        WHEN 7 THEN '7 [Video Small Data]'
        WHEN 8 THEN '8 [MP4 Cloud Share]'
        WHEN 9 THEN '9 [Still Testing]'
        WHEN 10 THEN '10 [3rdPartyApp thumb Still Testing]'
        WHEN 11 THEN '11 [Still Test]'
        WHEN 12 THEN '12 [Still Test]'
        WHEN 13 THEN '13 [PNG Optimized CPLAsset]'
        WHEN 14 THEN '14 [Wallpaper]'
        WHEN 15 THEN '15 [Has-Markup and Adjustments]'
        WHEN 16 THEN '16 [Video with Adjustments]'
        WHEN 17 THEN '17 [RAW_Photo]'
        WHEN 18 THEN '18 [Live Photo Video Optimized CPLAsset]'
        WHEN 19 THEN '19 [Live Photo with Adjustments]'
        WHEN 20 THEN '20 [Still Test]'
        WHEN 21 THEN '21 [Still Test]'
        WHEN 22 THEN '22 [Adjust Mutation AAE Asset]'
        WHEN 23 THEN '23 [Still Test]'
        WHEN 24 THEN '24 [Still Test]'
        WHEN 25 THEN '25 [Still Test]'
        WHEN 26 THEN '26 [MOV Optimized CPLAsset]'
        WHEN 27 THEN '27 [Still Test]'
        WHEN 28 THEN '28 [MOV-Med-hdr-Data]'
        ELSE 'Unknown New Value: ' || ZINTERNALRESOURCE.ZCLOUDSOURCETYPE || ''
    END AS 'ZINTERNALRESOURCE.ZCLOUDSOURCETYPE',

    ZINTERNALRESOURCE.ZDATALENGTH AS 'ZINTERNALRESOURCE.ZDATALENGTH',

    CASE ZINTERNALRESOURCE.ZRECIPEID
        WHEN 0 THEN '0 [OrigFileSize match DataLength or Optimized]'
        WHEN 65739 THEN '65739 [JPG Large Thumb]'
        WHEN 65741 THEN '65741 [Various Asset Types or Thumbs]'
        WHEN 65743 THEN '65743 [ResouType Photo 5003 or 5005 JPG Thumb]'
        WHEN 65749 THEN '65749 [LocalVideoKeyFrame JPG Thumb]'
        WHEN 65938 THEN '65938 [FullSizeRender Photo or plist]'
        WHEN 131072 THEN '131072 [FullSizeRender Video or plist]'
        WHEN 131079 THEN '131079 [medium MP4 Adj Mutation Asset]'
        WHEN 131081 THEN '131081 [ResouType Video 5003 or 5005 JPG Thumb]'
        WHEN 131272 THEN '131272 [FullSizeRender Video LivePhoto Adj Mutation]'
        WHEN 131275 THEN '131275 [medium MOV LivePhoto]'
        WHEN 131277 THEN '131277 [No IR Asset LivePhoto iCloud Sync Asset]'
        WHEN 131475 THEN '131475 [medium hdr MOV]'
        WHEN 327683 THEN '327683 [JPG Thumb for 3rdParty Still Testing]'
        WHEN 327687 THEN '627687 [Wallpape  Compute Resource]'
        ELSE 'Unknown New Value: ' || ZINTERNALRESOURCE.ZRECIPEID || ''
    END AS 'ZINTERNALRESOURCE.ZRECIPEID',

    CASE ZINTERNALRESOURCE.ZCLOUDLASTPREFETCHDATE
        WHEN 0 THEN '0 [N/A]'
        ELSE datetime(ZINTERNALRESOURCE.ZCLOUDLASTPREFETCHDATE + 978307200, 'UNIXEPOCH')
    END AS 'ZINTERNALRESOURCE.ZCLOUDLASTPREFETCHDATE(UTC)',

    ZINTERNALRESOURCE.ZCLOUDPREFETCHCOUNT AS 'ZINTERNALRESOURCE.ZCLOUDPREFETCHCOUNT',

    datetime(ZINTERNALRESOURCE.ZCLOUDLASTONDEMANDDOWNLOADDATE + 978307200, 'UNIXEPOCH') AS 'ZINTERNALRESOURCE.ZCLOUDLASTONDEMANDDOWNLOADDATE(UTC)',

    CASE ZINTERNALRESOURCE.ZUTICONFORMANCEHINT
        WHEN 0 THEN '0 [NA/Doesnt Conform]'
        WHEN 1 THEN '1 [UT Type Image]'
        WHEN 2 THEN '2 [Still Testing]'
        WHEN 3 THEN '3 [UT Type Movie]'
        ELSE 'Unknown New Value: ' || ZINTERNALRESOURCE.ZUTICONFORMANCEHINT || ''
    END AS 'ZINTERNALRESOURCE.ZUTICONFORMANCEHINT',

    CASE ZINTERNALRESOURCE.ZCOMPACTUTI
        WHEN 1 THEN '1 [jpeg/thm]'
        WHEN 3 THEN '3 [heic]'
        WHEN 6 THEN '6 [png]'
        WHEN 7 THEN '7 [Still Testing]'
        WHEN 23 THEN '23 [jpeg/heic/quicktime mov]'
        WHEN 24 THEN '24 [mpeg4]'
        WHEN 36 THEN '36 [Wallpaper]'
        WHEN 37 THEN '37 [Adj/Mutation Data]'
        ELSE 'Unknown New Value: ' || ZINTERNALRESOURCE.ZCOMPACTUTI || ''
    END AS 'ZINTERNALRESOURCE.ZCOMPACTUTI',

    ZASSET.ZUNIFORMTYPEIDENTIFIER AS 'ZASSET.ZUNIFORMTYPEIDENTIFIER',
    ZASSET.ZORIGINALCOLORSPACE AS 'ZASSET.ZORIGINALCOLORSPACE',
    ZCLOUDMASTER.ZUNIFORMTYPEIDENTIFIER AS 'ZCLOUDMASTER.ZUNIFORMTYPEIDENTIFIER',

    CASE ZCLOUDMASTER.ZFULLSIZEJPEGSOURCE
        WHEN 0 THEN '0 [CldMast JPEG Source Video]'
        WHEN 1 THEN '1 [CldMast JPEG Source Other]'
        ELSE 'Unknown New Value: ' || ZCLOUDMASTER.ZFULLSIZEJPEGSOURCE || ''
    END AS 'ZCLOUDMASTER.ZFULLSIZEJPEGSOURCE',

    ZASSET.ZHDRGAIN AS 'ZASSET.ZHDRGAIN',

    CASE ZASSET.ZHDRTYPE
        WHEN 0 THEN '0 [No HDR]'
        WHEN 3 THEN '3 [HDR Photo]'
        WHEN 4 THEN '4 [Non-HDR Version]'
        WHEN 5 THEN '5 [HEVC Movie]'
        WHEN 6 THEN '6 [Panorama]'
        WHEN 10 THEN '10 [HDR Gain]'
        ELSE 'Unknown New Value: ' || ZASSET.ZHDRTYPE || ''
    END AS 'ZASSET.ZHDRTYPE',

    ZEXTATTR.ZCODEC AS 'ZEXTATTR.ZCODEC',
    ZINTERNALRESOURCE.ZCODECFOURCHARCODENAME AS 'ZINTERNALRESOURCE.ZCODECFOURCHARCODENAME',
    ZCLOUDMASTER.ZCODECNAME AS 'ZCLOUDMASTER.ZCODECNAME',
    ZCLOUDMASTER.ZVIDEOFRAMERATE AS 'ZCLOUDMASTER.ZVIDEOFRAMERATE',
    ZCLOUDMASTER.ZPLACEHOLDERSTATE AS 'ZCLOUDMASTER.ZPLACEHOLDERSTATE',

    CASE ZASSET.ZDEPTHTYPE
        WHEN 0 THEN '0 [Not Portrait]'
        ELSE 'Portrait: ' || ZASSET.ZDEPTHTYPE || ''
    END AS 'ZASSET.ZDEPTHTYPE',

    ZASSET.ZAVALANCHEUUID AS 'ZASSET.ZAVALANCHEUUID',

    CASE ZASSET.ZMONOSKITYPE
        WHEN 0 THEN '0 [Still Testing No-Monoski]'
        ELSE 'Unknown New Value: ' || ZASSET.ZMONOSKITYPE || ''
    END AS 'ZASSET.ZMONOSKITYPE',

    CASE ZASSET.ZAVALANCHEPICKTYPE
        WHEN 0 THEN '0 [NA/Single Asset Burst UUID]'
        WHEN 2 THEN '2 [Burst Asset Not Selected]'
        WHEN 4 THEN '4 [Burst Asset PhotosApp Picked KeyImage]'
        WHEN 8 THEN '8 [Burst Asset Selected for LPL]'
        WHEN 16 THEN '16 [Top Burst Asset in Stack KeyImage]'
        WHEN 32 THEN '32 [Still Testing]'
        WHEN 52 THEN '52 [Burst Asset Visible LPL]'
        ELSE 'Unknown New Value: ' || ZASSET.ZAVALANCHEPICKTYPE || ''
    END AS 'ZASSET.ZAVALANCHEPICKTYPE',

    CASE ZADDASSETATTR.ZCLOUDAVALANCHEPICKTYPE
        WHEN 0 THEN '0 [NA/Single Asset Burst UUID]'
        WHEN 2 THEN '2 [Burst Asset Not Selected]'
        WHEN 4 THEN '4 [Burst Asset PhotosApp Picked KeyImage]'
        WHEN 8 THEN '8 [Burst Asset Selected for LPL]'
        WHEN 16 THEN '16 [Top Burst Asset in Stack KeyImage]'
        WHEN 32 THEN '32 [Still Testing]'
        WHEN 52 THEN '52 [Burst Asset Visible LPL]'
        ELSE 'Unknown New Value: ' || ZADDASSETATTR.ZCLOUDAVALANCHEPICKTYPE || ''
    END AS 'ZADDASSETATTR.ZCLOUDAVALANCHEPICKTYPE',

    CASE ZADDASSETATTR.ZCLOUDRECOVERYSTATE
        WHEN 0 THEN '0 [Still Testing]'
        WHEN 1 THEN '1 [Still Testing]'
        ELSE 'Unknown New Value: ' || ZADDASSETATTR.ZCLOUDRECOVERYSTATE || ''
    END AS 'ZADDASSETATTR.ZCLOUDRECOVERYSTATE',

    ZADDASSETATTR.ZCLOUDSTATERECOVERYATTEMPTSCOUNT AS 'ZADDASSETATTR.ZCLOUDSTATERECOVERYATTEMPTSCOUNT',
    ZASSET.ZDEFERREDPROCESSINGNEEDED AS 'ZASSET.ZDEFERREDPROCESSINGNEEDED',
    ZASSET.ZVIDEODEFERREDPROCESSINGNEEDED AS 'ZASSET.ZVIDEODEFERREDPROCESSINGNEEDED',
    ZADDASSETATTR.ZDEFERREDPHOTOIDENTIFIER AS 'ZADDASSETATTR.ZDEFERREDPHOTOIDENTIFIER',
    ZADDASSETATTR.ZDEFERREDPROCESSINGCANDIDATEOPTIONS AS 'ZADDASSETATTR.ZDEFERREDPROCESSINGCANDIDATEOPTIONS',

    CASE ZASSET.ZHASADJUSTMENTS
        WHEN 0 THEN '0 [No]'
        WHEN 1 THEN '1 [Yes]'
        ELSE 'Unknown New Value: ' || ZASSET.ZHASADJUSTMENTS || ''
    END AS 'ZASSET.ZHASADJUSTMENTS',

    --[ZUNMANAGEDADJUSTMENT.ZASSETATTRIBUTES = ZADDASSETATTR.Z_PK]
    ZUNMANAGEDADJUSTMENT.ZASSETATTRIBUTES AS 'ZUNMANAGEDADJUSTMENT.ZASSETATTRIBUTES',
    --[ZADDASSETATTR.ZUNMANAGEDADJUSTMENT = ZUNMANAGEDADJUSTMENT.Z_PK]
    ZADDASSETATTR.ZUNMANAGEDADJUSTMENT AS 'ZADDASSETATTR.ZUNMANAGEDADJUSTMENT',
    --[ZUNMANAGEDADJUSTMENT.Z_PK = ZADDASSETATTR.ZUnmanAdj]
    ZUNMANAGEDADJUSTMENT.Z_PK AS 'ZUNMANAGEDADJUSTMENT.Z_PK',
    ZUNMANAGEDADJUSTMENT.ZUUID AS 'ZUNMANAGEDADJUSTMENT.ZUUID',

    datetime(ZASSET.ZADJUSTMENTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZADJUSTMENTTIMESTAMP(UTC)',
    datetime(ZUNMANAGEDADJUSTMENT.ZADJUSTMENTTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZUNMANAGEDADJUSTMENT.ZADJUSTMENTTIMESTAMP(UTC)',

    ZADDASSETATTR.ZEDITORBUNDLEID AS 'ZADDASSETATTR.ZEDITORBUNDLEID',
    ZUNMANAGEDADJUSTMENT.ZEDITORLOCALIZEDNAME AS 'ZUNMANAGEDADJUSTMENT.ZEDITORLOCALIZEDNAME',
    ZUNMANAGEDADJUSTMENT.ZADJUSTMENTFORMATIDENTIFIER AS 'ZUNMANAGEDADJUSTMENT.ZADJUSTMENTFORMATIDENTIFIER',
    ZADDASSETATTR.ZMONTAGE AS 'ZADDASSETATTR.ZMONTAGE',

    CASE ZUNMANAGEDADJUSTMENT.ZADJUSTMENTRENDERTYPES
        WHEN 0 THEN '0 [Standard or Portrait with erros]'
        WHEN 1 THEN '1 [Still Testing]'
        WHEN 2 THEN '2 [Portrait]'
        WHEN 3 THEN '3 [Still Testing]'
        WHEN 4 THEN '4 [Still Testing]'
        ELSE 'Unknown New Value: ' || ZUNMANAGEDADJUSTMENT.ZADJUSTMENTRENDERTYPES || ''
    END AS 'ZUNMANAGEDADJUSTMENT.ZADJUSTMENTRENDERTYPES',

    CASE ZUNMANAGEDADJUSTMENT.ZADJUSTMENTFORMATVERSION
        WHEN 1.0 THEN '1.0 [Markup]'
        WHEN 1.1 THEN '1.1 [Slow-Mo]'
        WHEN 1.2 THEN '1.2 [Still Testing]'
        WHEN 1.3 THEN '1.3 [Still Testing]'
        WHEN 1.4 THEN '1.4 [Filter]'
        WHEN 1.5 THEN '1.5 [Adjust]'
        WHEN 1.6 THEN '1.6 [Video Trim]'
        WHEN 1.7 THEN '1.7 [Still Testing]'
        WHEN 1.8 THEN '1.8 [Still Testing]'
        WHEN 1.9 THEN '1.9 [Still Testing]'
        WHEN 2.0 THEN '2.0 [Screenshot Services]'
        ELSE 'Unknown New Value: ' || ZUNMANAGEDADJUSTMENT.ZADJUSTMENTFORMATVERSION || ''
    END AS 'ZUNMANAGEDADJUSTMENT.ZADJUSTMENTFORMATVERSION',

    ZUNMANAGEDADJUSTMENT.ZADJUSTMENTBASEIMAGEFORMAT AS 'ZUNMANAGEDADJUSTMENT.ZADJUSTMENTBASEIMAGEFORMAT',

    CASE ZASSET.ZFAVORITE
        WHEN 0 THEN '0 [Asset Not Favorite]'
        WHEN 1 THEN '1 [Asset Favorite]'
    END AS 'ZASSET.ZFAVORITE',

    CASE ZASSET.ZHIDDEN
        WHEN 0 THEN '0 [Asset Not Hidden]'
        WHEN 1 THEN '1 [Asset Hidden]'
        ELSE 'Unknown New Value: ' || ZASSET.ZHIDDEN || ''
    END AS 'ZASSET.ZHIDDEN',

    CASE ZASSET.ZTRASHEDSTATE
        WHEN 0 THEN '0 [Asset Not In Trash]'
        WHEN 1 THEN '1 [Asset In Trash]'
        ELSE 'Unknown New Value: ' || ZASSET.ZTRASHEDSTATE || ''
    END AS 'ZASSET.ZTRASHEDSTATE',

    datetime(ZASSET.ZTRASHEDDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZTRASHEDDATE(UTC)',

    CASE ZASSET.ZDELETEREASON
        WHEN 1 THEN '1 [Still Testing]'
        WHEN 2 THEN '2 [Still Testing]'
        WHEN 3 THEN '3 [Still Testing]'
        ELSE 'Unknown New Value: ' || ZASSET.ZDELETEREASON || ''
    END AS 'ZASSET.ZDELETEREASON',

    CASE ZASSET.ZTRASHEDBYPARTICIPANT
        WHEN 1 THEN '1 [Asset Trashed by Participant]'
        ELSE 'Unknown New Value: ' || ZASSET.ZTRASHEDBYPARTICIPANT || ''
    END AS 'ZASSET.ZTRASHEDBYPARTICIPANT',

    CASE ZINTERNALRESOURCE.ZTRASHEDSTATE
        WHEN 0 THEN '0 [Not In Trash]'
        WHEN 1 THEN '1 [In Trash]'
        ELSE 'Unknown New Value: ' || ZINTERNALRESOURCE.ZTRASHEDSTATE || ''
    END AS 'ZINTERNALRESOURCE.ZTRASHEDSTATE',

    datetime(ZINTERNALRESOURCE.ZTRASHEDDATE + 978307200, 'UNIXEPOCH') AS 'ZINTERNALRESOURCE.ZTRASHEDDATE(UTC)',

    CASE ZASSET.ZCLOUDDELETESTATE
        WHEN 0 THEN '0 [Cloud Asset Not Deleted]'
        WHEN 1 THEN '1 [Cloud Asset Deleted]'
        ELSE 'Unknown New Value: ' || ZASSET.ZCLOUDDELETESTATE || ''
    END AS 'ZASSET.ZCLOUDDELETESTATE',

    CASE ZINTERNALRESOURCE.ZCLOUDDELETESTATE
        WHEN 0 THEN '0 [Cloud IntResou Not Deleted]'
        WHEN 1 THEN '1 [Cloud IntResou Deleted]'
        ELSE 'Unknown New Value: ' || ZINTERNALRESOURCE.ZCLOUDDELETESTATE || ''
    END AS 'ZINTERNALRESOURCE.ZCLOUDDELETESTATE',

    CASE ZADDASSETATTR.ZPTPTRASHEDSTATE
        WHEN 0 THEN '0 [PTP Not in Trash]'
        WHEN 1 THEN '1 [PTP In Trash]'
        ELSE 'Unknown New Value: ' || ZADDASSETATTR.ZPTPTRASHEDSTATE || ''
    END AS 'ZADDASSETATTR.ZPTPTRASHEDSTATE',

    CASE ZINTERNALRESOURCE.ZPTPTRASHEDSTATE
        WHEN 0 THEN '0 [PTP IntResou Not in Trash]'
        WHEN 1 THEN '1 [PTP IntResou In Trash]'
        ELSE 'Unknown New Value: ' || ZINTERNALRESOURCE.ZPTPTRASHEDSTATE || ''
    END AS 'ZINTERNALRESOURCE.ZPTPTRASHEDSTATE',

    ZINTERNALRESOURCE.ZCLOUDDELETEASSETUUIDWITHRESOURCETYPE AS 'ZINTERNALRESOURCE.ZCLOUDDELETEASSETUUIDWITHRESOURCETYPE',

    datetime(zMedAnlyAstAttr.ZMEDIAANALYSISTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'zMedAnlyAstAttr.ZMEDIAANALYSISTIMESTAMP(UTC)',
    datetime(ZASSET.ZANALYSISSTATEMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZANALYSISSTATEMODIFICATIONDATE(UTC)',

    ZADDASSETATTR.ZPENDINGVIEWCOUNT AS 'ZADDASSETATTR.ZPENDINGVIEWCOUNT',
    ZADDASSETATTR.ZVIEWCOUNT AS 'ZADDASSETATTR.ZVIEWCOUNT',
    ZADDASSETATTR.ZPENDINGPLAYCOUNT AS 'ZADDASSETATTR.ZPENDINGPLAYCOUNT',
    ZADDASSETATTR.ZPLAYCOUNT AS 'ZADDASSETATTR.ZPLAYCOUNT',
    ZADDASSETATTR.ZPENDINGSHARECOUNT AS 'ZADDASSETATTR.ZPENDINGSHARECOUNT',
    ZADDASSETATTR.ZSHARECOUNT AS 'ZADDASSETATTR.ZSHARECOUNT',

    datetime(ZASSET.ZLASTSHAREDDATE + 978307200, 'UNIXEPOCH') AS 'ZASSET.ZLASTSHAREDDATE(UTC)',

    ZADDASSETATTR.ZSHAREORIGINATOR AS 'ZADDASSETATTR.ZSHAREORIGINATOR',

    CASE ZADDASSETATTR.ZALLOWEDFORANALYSIS
        WHEN 0 THEN '0 [Asset Not Allowed For Analysis]'
        WHEN 1 THEN '1 [Asset Allowed for Analysis]'
        ELSE 'Unknown New Value: ' || ZADDASSETATTR.ZALLOWEDFORANALYSIS || ''
    END AS 'ZADDASSETATTR.ZALLOWEDFORANALYSIS',

    ZADDASSETATTR.ZSCENEANALYSISVERSION AS 'ZADDASSETATTR.ZSCENEANALYSISVERSION',

    CASE ZADDASSETATTR.ZSCENEANALYSISISFROMPREVIEW
        WHEN 0 THEN '0 [No]'
        ELSE 'Unknown New Value: ' || ZADDASSETATTR.ZSCENEANALYSISISFROMPREVIEW || ''
    END AS 'ZADDASSETATTR.ZSCENEANALYSISISFROMPREVIEW',

    datetime(ZADDASSETATTR.ZSCENEANALYSISTIMESTAMP + 978307200, 'UNIXEPOCH') AS 'ZADDASSETATTR.ZSCENEANALYSISTIMESTAMP(UTC)',

    CASE ZASSET.ZDUPLICATEASSETVISIBILITYSTATE
        WHEN 0 THEN '0 [No Duplicates]'
        WHEN 1 THEN '1 [Has Duplicate]'
        WHEN 2 THEN '2 [Is a Duplicate]'
        ELSE 'Unknown New Value: ' || ZASSET.ZDUPLICATEASSETVISIBILITYSTATE || ''
    END AS 'ZASSET.ZDUPLICATEASSETVISIBILITYSTATE',

    CASE ZADDASSETATTR.ZDESTINATIONASSETCOPYSTATE
        WHEN 0 THEN '0 [No Copy]'
        WHEN 1 THEN '1 [Has A Copy]'
        WHEN 2 THEN '2 [Has A Copy]'
        ELSE 'Unknown New Value: ' || ZADDASSETATTR.ZDESTINATIONASSETCOPYSTATE || ''
    END AS 'ZADDASSETATTR.ZDESTINATIONASSETCOPYSTATE',

    --hex(ZSCENEPRINT.ZDATA) AS 'ZSCENEPRINT.ZDATA(HEX NSKeyed .plist)',
    --hex(ZSCENEPRINT.ZDUPLICATEMATCHINGDATA) AS 'ZSCENEPRINT.ZDUPLICATEMATCHINGDATA(HEX NSKeyed .plist)',
    --hex(ZSCENEPRINT.ZDUPLICATEMATCHINGALTERNATEDATA) AS 'ZSCENEPRINT.ZDUPLICATEMATCHINGALTERNATEDATA(HEX NSKeyed .plist)',
    ZADDASSETATTR.ZSOURCEASSETFORDUPLICATIONSCOPEIDENTIFIER AS 'ZADDASSETATTR.ZSOURCEASSETFORDUPLICATIONSCOPEIDENTIFIER',
    ZCLOUDMASTER.ZSOURCEMASTERFORDUPLICATIONSCOPEIDENTIFIER AS 'ZCLOUDMASTER.ZSOURCEMASTERFORDUPLICATIONSCOPEIDENTIFIER',
    ZADDASSETATTR.ZSOURCEASSETFORDUPLICATIONIDENTIFIER AS 'ZADDASSETATTR.ZSOURCEASSETFORDUPLICATIONIDENTIFIER',
    ZCLOUDMASTER.ZSOURCEMASTERFORDUPLICATIONIDENTIFIER AS 'ZCLOUDMASTER.ZSOURCEMASTERFORDUPLICATIONIDENTIFIER'


FROM ZASSET
    LEFT JOIN ZADDITIONALASSETATTRIBUTES ZADDASSETATTR ON ZADDASSETATTR.Z_PK = ZASSET.ZADDITIONALATTRIBUTES
    LEFT JOIN ZEXTENDEDATTRIBUTES ZEXTATTR ON ZEXTATTR.Z_PK = ZASSET.ZEXTENDEDATTRIBUTES
    LEFT JOIN ZINTERNALRESOURCE ON ZINTERNALRESOURCE.ZASSET = ZASSET.Z_PK
    LEFT JOIN ZSCENEPRINT ON ZSCENEPRINT.Z_PK = ZADDASSETATTR.ZSCENEPRINT
    LEFT JOIN Z_28ASSETS ON Z_28ASSETS.Z_3ASSETS = ZASSET.Z_PK
    LEFT JOIN ZGENERICALBUM zGenAlbum ON zGenAlbum.Z_PK = Z_28ASSETS.Z_28ALBUMS
    LEFT JOIN ZUNMANAGEDADJUSTMENT ON ZADDASSETATTR.ZUNMANAGEDADJUSTMENT = ZUNMANAGEDADJUSTMENT.Z_PK
    LEFT JOIN Z_27ALBUMLISTS ON Z_27ALBUMLISTS.Z_27ALBUMS = zGenAlbum.Z_PK
    LEFT JOIN ZALBUMLIST ON ZALBUMLIST.Z_PK = Z_27ALBUMLISTS.Z_2ALBUMLISTS
    LEFT JOIN ZGENERICALBUM ParentzGenAlbum ON ParentzGenAlbum.Z_PK = zGenAlbum.ZPARENTFOLDER
    LEFT JOIN ZCLOUDMASTER ON ZASSET.ZMASTER = ZCLOUDMASTER.Z_PK
    LEFT JOIN ZCLOUDMASTERMEDIAMETADATA AAAzCldMastMedData ON AAAzCldMastMedData.Z_PK = ZADDASSETATTR.ZMEDIAMETADATA
    LEFT JOIN ZCLOUDMASTERMEDIAMETADATA CMzCldMastMedData ON CMzCldMastMedData.Z_PK = ZCLOUDMASTER.ZMEDIAMETADATA
    LEFT JOIN ZMEDIAANALYSISASSETATTRIBUTES zMedAnlyAstAttr ON ZASSET.ZMEDIAANALYSISATTRIBUTES = zMedAnlyAstAttr.Z_PK
    LEFT JOIN ZSHARE ON ZSHARE.Z_PK = ZASSET.ZMOMENTSHARE


WHERE
    ZASSET.ZFILENAME IS 'IMG_7162.WEBP' OR
    ZASSET.ZFILENAME IS 'IMG_9012.WEBP' OR
    ZASSET.ZFILENAME IS 'IMG_9402.WEBP' OR
    ZASSET.ZFILENAME IS 'IMG_3956.WEBP' OR
    ZASSET.ZFILENAME IS '1043747.jpg' OR
    ZASSET.ZFILENAME IS '1043749.jpg' OR
    ZASSET.ZFILENAME IS '1043751.jpg' OR
    ZASSET.ZFILENAME IS '1043750.jpg' OR
    ZASSET.ZFILENAME IS '1043748.jpg' OR
    ZASSET.ZFILENAME IS '1043752.jpg' OR
    ZASSET.ZFILENAME IS '1043753.jpg' OR
    ZASSET.ZFILENAME IS '1043754.jpg' OR
    ZASSET.ZFILENAME IS '1043757.jpg' OR
    ZASSET.ZFILENAME IS '1043755.jpg' OR
    ZASSET.ZFILENAME IS '1043759.jpg' OR
    ZASSET.ZFILENAME IS '1043758.jpg' OR
    ZASSET.ZFILENAME IS '1043756.jpg' OR
    ZASSET.ZFILENAME IS '1043762.jpg' OR
    ZASSET.ZFILENAME IS '1043763.jpg' OR
    ZASSET.ZFILENAME IS '1043761.jpg' OR
    ZASSET.ZFILENAME IS '1043760.jpg' OR
    ZASSET.ZFILENAME IS '1043766.jpg' OR
    ZASSET.ZFILENAME IS '1043764.jpg' OR
    ZASSET.ZFILENAME IS '1043765.jpg' OR
    ZASSET.ZFILENAME IS '982872.jpg' OR
    ZASSET.ZFILENAME IS '982871.jpg' OR
    ZASSET.ZFILENAME IS '982873.jpg' OR
    ZASSET.ZFILENAME IS '982875.jpg' OR
    ZASSET.ZFILENAME IS '982876.jpg' OR
    ZASSET.ZFILENAME IS '982874.jpg' OR
    ZASSET.ZFILENAME IS '982878.jpg' OR
    ZASSET.ZFILENAME IS '982877.jpg' OR
    ZASSET.ZFILENAME IS '982879.jpg' OR
    ZASSET.ZFILENAME IS '982880.jpg' OR
    ZASSET.ZFILENAME IS '982881.jpg' OR
    ZASSET.ZFILENAME IS '982884.jpg' OR
    ZASSET.ZFILENAME IS '982883.jpg' OR
    ZASSET.ZFILENAME IS '982882.jpg' OR
    ZASSET.ZFILENAME IS '982885.jpg' OR
    ZASSET.ZFILENAME IS '982887.jpg' OR
    ZASSET.ZFILENAME IS '982889.jpg' OR
    ZASSET.ZFILENAME IS '982890.jpg' OR
    ZASSET.ZFILENAME IS '982886.jpg' OR
    ZASSET.ZFILENAME IS '982888.jpg' OR
    ZASSET.ZFILENAME IS '982891.jpg' OR
    ZASSET.ZFILENAME IS '982892.jpg' OR
    ZASSET.ZFILENAME IS '982893.jpg' OR
    ZASSET.ZFILENAME IS '982896.jpg' OR
    ZASSET.ZFILENAME IS '982895.jpg' OR
    ZASSET.ZFILENAME IS '982894.jpg' OR
    ZASSET.ZFILENAME IS '982898.jpg' OR
    ZASSET.ZFILENAME IS '982897.jpg' OR
    ZASSET.ZFILENAME IS '982900.jpg' OR
    ZASSET.ZFILENAME IS '982899.jpg' OR
    ZASSET.ZFILENAME IS '982903.png' OR
    ZASSET.ZFILENAME IS '982902.jpg' OR
    ZASSET.ZFILENAME IS '982904.jpg' OR
    ZASSET.ZFILENAME IS '982905.jpg' OR
    ZASSET.ZFILENAME IS '982908.jpg' OR
    ZASSET.ZFILENAME IS '982909.jpg' OR
    ZASSET.ZFILENAME IS '982906.jpg' OR
    ZASSET.ZFILENAME IS '982907.jpg' OR
    ZASSET.ZFILENAME IS '982901.jpg' OR
    ZASSET.ZFILENAME IS '982912.jpg' OR
    ZASSET.ZFILENAME IS '982913.jpg' OR
    ZASSET.ZFILENAME IS '982911.jpg' OR
    ZASSET.ZFILENAME IS '982914.jpg' OR
    ZASSET.ZFILENAME IS '982916.jpg' OR
    ZASSET.ZFILENAME IS '982915.jpg' OR
    ZASSET.ZFILENAME IS '982910.jpg' OR
    ZASSET.ZFILENAME IS '982920.jpg' OR
    ZASSET.ZFILENAME IS '982917.jpg' OR
    ZASSET.ZFILENAME IS '982921.jpg' OR
    ZASSET.ZFILENAME IS '982919.jpg' OR
    ZASSET.ZFILENAME IS '982918.jpg' OR
    ZASSET.ZFILENAME IS '00DD1D4D-EE70-46A3-95A1-369FE84F5490.jpeg' OR
    ZASSET.ZFILENAME IS '012E4248-8E5C-42CB-AD60-B2D5068E5724.jpeg' OR
    ZASSET.ZFILENAME IS '0729112A-ED62-43AB-B261-DC2561D54E90.jpeg' OR
    ZASSET.ZFILENAME IS '09F4F020-96F1-4221-A6FB-87F7EC368AC1.jpeg' OR
    ZASSET.ZFILENAME IS '0B9AE241-45EC-4FE1-916A-57864F096FA6.jpeg' OR
    ZASSET.ZFILENAME IS '10CF5255-FD7E-431A-9E97-A113E6DA66FA.jpeg' OR
    ZASSET.ZFILENAME IS '12AAFA5A-B257-4D4D-9ECC-471D880EAE60.jpeg' OR
    ZASSET.ZFILENAME IS '1553141E-AE54-451F-B60E-332E0EC762AA.jpeg' OR
    ZASSET.ZFILENAME IS '19CB9BA7-B901-43E0-976B-299F89CDCED3.jpeg' OR
    ZASSET.ZFILENAME IS '1A432329-FAF2-4C39-99FD-761F98D3B6E9.jpeg' OR
    ZASSET.ZFILENAME IS '1BF8046B-A09D-4404-A2D8-DCD86D596041.jpeg' OR
    ZASSET.ZFILENAME IS '1F6898A0-54FE-4E99-B0BC-33C34D69D757.jpeg' OR
    ZASSET.ZFILENAME IS '205B62B0-D4E5-4DB6-ADD9-18516E0DBBCF.jpeg' OR
    ZASSET.ZFILENAME IS '20DBA8DF-5068-48EB-825C-3073A98D3106.jpeg' OR
    ZASSET.ZFILENAME IS '24056466-79AA-4ADB-86A0-39B81497F612.jpeg' OR
    ZASSET.ZFILENAME IS '26C7B6D1-256A-4EAF-8F01-94BBC9DE2848.jpeg' OR
    ZASSET.ZFILENAME IS '28ECD795-19E6-4F6C-B475-833643112B62.jpeg' OR
    ZASSET.ZFILENAME IS '3308F0E9-D9A0-4F76-83E2-DD652F74B622.jpeg' OR
    ZASSET.ZFILENAME IS '3706ADC1-0491-4C30-830F-B6FBBEAF277F.jpeg' OR
    ZASSET.ZFILENAME IS '3B48A60E-CA95-4495-AC8E-7221EC61ED1E.jpeg' OR
    ZASSET.ZFILENAME IS '45639712-F8DD-4E6B-B4A5-FF50153D1A70.jpeg' OR
    ZASSET.ZFILENAME IS '4923B6AA-5349-4B7B-BFF1-4252AE9F01B1.jpeg' OR
    ZASSET.ZFILENAME IS '49F62B09-B087-4EE0-8F35-AA704E47A501.jpeg' OR
    ZASSET.ZFILENAME IS '4A317171-76B7-493E-AC97-7F460E67A7FE.png' OR
    ZASSET.ZFILENAME IS '4E4EF37C-D289-4AF6-8A44-E87B6DEFD054.jpeg' OR
    ZASSET.ZFILENAME IS '4F739A18-9D8D-412B-8165-4B7E71E35177.jpeg' OR
    ZASSET.ZFILENAME IS '51182AEA-BAB9-498F-80F1-BDDBB8625780.jpeg' OR
    ZASSET.ZFILENAME IS '52A85BCC-C1C8-4359-BB33-FCEA5893D9D9.jpeg' OR
    ZASSET.ZFILENAME IS '54510980-FA61-44C7-AC6D-6335F35C40EF.jpeg' OR
    ZASSET.ZFILENAME IS '57A6D23D-9E84-44DD-82A2-D9E1A451744C.jpeg' OR
    ZASSET.ZFILENAME IS '582B2394-320F-48CF-AE84-ABE68D97EAA2.jpeg' OR
    ZASSET.ZFILENAME IS '5C52C59D-0D7C-4CC7-9200-8B475D8FA36D.jpeg' OR
    ZASSET.ZFILENAME IS '5FBBF469-1DDC-4CD5-ADF2-591827B72D35.jpeg' OR
    ZASSET.ZFILENAME IS '61C5B3C3-618E-4DFF-89A9-ADA9CA1BE19B.jpeg' OR
    ZASSET.ZFILENAME IS '63D6842E-53C2-42BE-9B1B-BD99EE29B875.jpeg' OR
    ZASSET.ZFILENAME IS '738649BE-0475-4700-8821-12E969D00622.jpeg' OR
    ZASSET.ZFILENAME IS '7B9B2AAA-F76A-49CD-8E58-DE01D987771C.jpeg' OR
    ZASSET.ZFILENAME IS '7C417FDB-F7F3-4454-A289-EB6DB8466727.jpeg' OR
    ZASSET.ZFILENAME IS '8162ACD8-ED32-4DB7-BC3F-4E5F53DCC59B.jpeg' OR
    ZASSET.ZFILENAME IS '841A1B51-5007-459C-ABDE-B612B77190EF.jpeg' OR
    ZASSET.ZFILENAME IS '89F1E281-9005-4E04-AD1C-F440EC21AFE3.jpeg' OR
    ZASSET.ZFILENAME IS '8B89710E-FF7E-49B8-B3F5-226F7DA796B1.jpeg' OR
    ZASSET.ZFILENAME IS '8CFD3EE2-C488-4286-B82E-447745774BD9.jpeg' OR
    ZASSET.ZFILENAME IS '9117051C-C1BD-4674-BAE0-02E1BBE36078.jpeg' OR
    ZASSET.ZFILENAME IS '91D0EEBB-B058-4051-B79A-9247331E00A9.jpeg' OR
    ZASSET.ZFILENAME IS '92FE77A0-C31B-4CC2-B55B-5555BD851176.jpeg' OR
    ZASSET.ZFILENAME IS '937E53A1-7EF0-4C43-BA55-08CBE3DE6181.jpeg' OR
    ZASSET.ZFILENAME IS '95D65415-7A78-479C-901B-020B9D0F1055.jpeg' OR
    ZASSET.ZFILENAME IS '992B809F-8E31-43C1-B188-D7E72FEB09EF.jpeg' OR
    ZASSET.ZFILENAME IS '98FF097A-93C8-4E75-82D6-C240FB804FBB.jpeg' OR
    ZASSET.ZFILENAME IS 'A2746ECD-6B9B-4A79-89A2-28D6305DCDC3.jpeg' OR
    ZASSET.ZFILENAME IS 'A75B0471-101E-4281-B627-4978B9E0B014.jpeg' OR
    ZASSET.ZFILENAME IS 'ABEA34DA-EA64-4C3C-9D82-205694961C8F.jpeg' OR
    ZASSET.ZFILENAME IS 'AF08DBE7-53E7-459D-A392-5486B8C79F50.jpeg' OR
    ZASSET.ZFILENAME IS 'B06D08F9-1B48-4157-AAA7-36AFFBE66886.jpeg' OR
    ZASSET.ZFILENAME IS 'BBE17094-746E-4B08-8F81-8AF10B425837.jpeg' OR
    ZASSET.ZFILENAME IS 'C235FC05-BCBD-4443-8F80-465705DA3240.jpeg' OR
    ZASSET.ZFILENAME IS 'C35F0BD0-9789-4A86-BBC8-B9DCAD3C78BC.jpeg' OR
    ZASSET.ZFILENAME IS 'C78FEA80-1FCC-4BA2-BBC6-6F5DE1CA87F9.jpeg' OR
    ZASSET.ZFILENAME IS 'CA6F58A8-460C-4850-A347-BBC60B283F29.jpeg' OR
    ZASSET.ZFILENAME IS 'CEA36C4F-4F10-41FA-9E9A-BF2EF31EAA2C.jpeg' OR
    ZASSET.ZFILENAME IS 'D075FFEB-3EB3-4854-A308-B73376819AB0.jpeg' OR
    ZASSET.ZFILENAME IS 'D4DFE77A-6798-4D2E-901E-13F6DC24DDAE.jpeg' OR
    ZASSET.ZFILENAME IS 'DC79750A-5E3C-4B93-994E-0053EAA0443F.jpeg' OR
    ZASSET.ZFILENAME IS 'E1A29B2D-D488-4E7B-8502-7F9E11A0ACF7.jpeg' OR
    ZASSET.ZFILENAME IS 'E830B799-1C88-42C0-AE97-61B61A5CF5F9.jpeg' OR
    ZASSET.ZFILENAME IS 'ECD70D32-E715-42F4-BDB4-53BEE36DCFA5.jpeg' OR
    ZASSET.ZFILENAME IS 'ED921EFD-482E-4E0D-93A3-989915A66985.jpeg' OR
    ZASSET.ZFILENAME IS 'F278D94B-8F99-4CBC-B013-B3DB79132940.jpeg' OR
    ZASSET.ZFILENAME IS 'FC7557A7-6375-458B-ADD2-131A71E913DE.jpeg' OR
    ZASSET.ZFILENAME IS 'FFD68FD3-A8E8-4714-B118-FC1AB6F94CE3.jpeg' OR
    ZASSET.ZFILENAME IS '8162ACD8-ED32-4DB7-BC3F-4E5F53DCC59B_1_102_o.jpeg' OR
    ZASSET.ZFILENAME IS '8162ACD8-ED32-4DB7-BC3F-4E5F53DCC59B_4_5005_c.jpeg' OR
    ZASSET.ZFILENAME IS '[www.18y.tube] @nikitinaliiis video (10).mp4' OR
    ZASSET.ZFILENAME IS '[www.18y.tube] @nikitinaliiis video (12).mp4' OR
    ZASSET.ZFILENAME IS '[www.18y.tube] @nikitinaliiis video (3).mp4' OR
    ZASSET.ZFILENAME IS '[www.18y.tube] @nikitinaliiis video (2).mp4' OR
    ZASSET.ZFILENAME IS '[www.18y.tube] @nikitinaliiis video (1).mp4' OR
    ZASSET.ZFILENAME IS '[www.18y.tube] @nikitinaliiis video (5).mp4' OR
    ZASSET.ZFILENAME IS '[www.18y.tube] @nikitinaliiis video (4).mp4' OR
    ZASSET.ZFILENAME IS '[www.18y.tube] @nikitinaliiis video (13).mp4' OR
    ZASSET.ZFILENAME IS '[www.18y.tube] @nikitinaliiis video (6).mp4' OR
    ZASSET.ZFILENAME IS '[www.18y.tube] @nikitinaliiis video (8).mp4' OR
    ZASSET.ZFILENAME IS '[www.18y.tube] @nikitinaliiis video (9).mp4' OR
    ZASSET.ZFILENAME IS '[www.18y.tube] @nikitinaliiis video (7).mp4' OR
    ZASSET.ZFILENAME IS 'liinaliiis lovee 10.mp4' OR
    ZASSET.ZFILENAME IS '[www.18y.tube] @nikitinaliiis video.mp4' OR
    ZASSET.ZFILENAME IS 'liinaliiis lovee 11.mp4' OR
    ZASSET.ZFILENAME IS 'liinaliiis lovee 6.mp4' OR
    ZASSET.ZFILENAME IS 'liinaliiis lovee 7.mp4' OR
    ZASSET.ZFILENAME IS 'liinaliiis lovee 12 asmr cleaning.mp4' OR
    ZASSET.ZFILENAME IS 'liinaliiis lovee 9.mp4' OR
    ZASSET.ZFILENAME IS 'liinaliiis lovee 8.mp4' OR
    ZASSET.ZFILENAME IS '[www.18y.tube] @nikitinaliiis video (11).mp4' OR
    ZASSET.ZFILENAME IS '0BA00582-A59C-42E4-AC18-2BCE7E909CA5.mp4' OR
    ZASSET.ZFILENAME IS '12A103F1-31C2-488F-87CC-3F1984AA2A27.mp4' OR
    ZASSET.ZFILENAME IS '1F6B1C4C-5113-4DC6-8AF6-31056A26A077.mp4' OR
    ZASSET.ZFILENAME IS '214D5A70-EE64-43DD-B9C5-90B1291F596E.mp4' OR
    ZASSET.ZFILENAME IS '4CB7D18D-76E2-4711-8764-CC2CF6CC5C35.mp4' OR
    ZASSET.ZFILENAME IS '56905895-B57D-4DA5-90A3-A37F5EEE04E7.mp4' OR
    ZASSET.ZFILENAME IS '56F14483-E730-4E9E-8A5F-3F5F122C9954.mp4' OR
    ZASSET.ZFILENAME IS '5BA90331-122C-4CE1-A8EB-673A9B239DAF.mp4' OR
    ZASSET.ZFILENAME IS '5AB60C3F-FF6F-4E2C-B6C0-A0232F9F2A5A.mp4' OR
    ZASSET.ZFILENAME IS '5F42CE0F-20EE-4292-944C-B0CBA71001AB.mp4' OR
    ZASSET.ZFILENAME IS '79CA77D0-44F1-474B-976C-BC6E35CD71F6.mp4' OR
    ZASSET.ZFILENAME IS '8303316B-0D93-465C-9D40-87386F23B587.mp4' OR
    ZASSET.ZFILENAME IS '9167371F-F66F-4A4F-A186-4209A71C71EA.mp4' OR
    ZASSET.ZFILENAME IS 'BB316806-3918-4616-A223-F46C9C9F64C3.mp4' OR
    ZASSET.ZFILENAME IS 'BF68C376-9EA6-445B-B3F2-227EC38AD4EA.mp4' OR
    ZASSET.ZFILENAME IS 'C2A66D71-92F2-4B5F-A73B-47686960EFEA.mp4' OR
    ZASSET.ZFILENAME IS 'E1A903F3-6DFB-4A60-8815-91F75089B96A.mp4' OR
    ZASSET.ZFILENAME IS 'E46D356D-4C0B-4B9C-B5AE-A11A3317D96A.mp4' OR
    ZASSET.ZFILENAME IS 'F3AC6ECB-F5C1-4F1F-BF72-87D4A7BA61C4.mp4' OR
    ZASSET.ZFILENAME IS 'F56067E9-AFA3-4989-8487-124440D9178F.mp4' OR
    ZASSET.ZFILENAME IS 'F67425A4-FE23-4A41-BA6C-828136EDC129.mp4'



ORDER BY ZASSET.ZADDEDDATE
